### ISSUE TITLE
Joining a World

### ISSUE THREAD

**Issue by Mattabase** [McJty/InControl#1]
https://goo.gl/yRCHtg

**Comment by McJty** [comment]
Can you show me your spawn.json?

**Comment by Mattabase** [comment]
[
  {
    "minheight": 50,
    "hostile": true,
    "result": "deny"
  },
  {
    "maxheight": 50,
    "block": ["minecraft:stone", "minecraft:cobblestone"],
    "result": "allow"
  },
  {
    "result": "deny"
  }
]

**Comment by McJty** [comment]
I'll add some crash protection

**Comment by McJty** [comment]
Fixed next release
