### ISSUE TITLE
InControl still effecting pack even after its removed

### ISSUE THREAD

**Issue by Dr-Mic** [McJty/InControl#106]
I added InControl in hopes to limit/eliminate passive mobs from spawning. I used this script in the spawn config folder:
[
  {
    "passive": true,
    "dimension": 0,
    "onjoin": true,
    "result": "deny"
  }
]

However, I didn't realize this would also prevent passive mobs from spawning even when using the spawn egg. I switched the "result" line to "allow" and this did not fix the issue. I tried a few other things all with the same result. I resorted to removing the mod and its config folder in hopes to start over, but the effect is still in the game even with it gone. plz help

**Comment by McJty** [comment]
In Control can literally not do anything if it is not in the game so that's impossible. My guess is something else is going on.
