### ISSUE TITLE
Cannot find first mob in each Potential Spawn 'remove'

### ISSUE THREAD

**Issue by naqaden** [McJty/InControl#116]
I started with a simple potentialspawn.json like so:
```
[
  {
    "remove": "minecraft:skeleton",
    "dimension": -1
  }
]
```
resulting in **[Server thread/ERROR] [incontrol]: Cannot find mob '"minecraft:skeleton"'!**

For science, I tried:
```
[
  {
    "remove":
    [
      "minecraft:zombie",
      "minecraft:skeleton"
    ]
  }
]
```
and.. **[Server thread/ERROR] [incontrol]: Cannot find mob '"minecraft:zombie"'!**

It seems like it's picking on whatever comes first, even if it's a legitimate mob. If I have multiple "remove" blocks, it will complain about the first mob in each block.

**Comment by McJty** [comment]
What version of In Control? Can you try 'Zombie' and 'Skeleton' as well (without 'minecraft:' and with the capital first letter)

**Comment by naqaden** [comment]
I'm using v3.9.6 on MC 1.12.2, and after a little more testing, the errors start with v3.9.4. The same config is fine in prior versions.

I tried "Skeleton" and it still complained.

**Comment by McJty** [comment]
I will investigate this

**Comment by McJty** [comment]
Fixed next release
