### ISSUE TITLE
Options damagemultiply and healthmultiply may be working incorrectly?

### ISSUE THREAD

**Issue by coryjreid** [McJty/InControl#123]
I'm just experimenting with this mod to make sure it works and will fulfill my needs. In testing, I have turned off all mob spawns except for skeletons, and have attempted to multiply their health by 2. My `spawn.json` file is shown below:

https://gist.github.com/coryjreid/1ae9b2c5d58d613d4db3b613b9e10c47

**Expected Result:** All skeletons spawn with 20 hearts (40 health).
**Actual Result:** Skeletons spawn with a variety of health values from the expected to 512 hearts (1024 health).

Am I doing something wrong? I also tried using `damagemultiply` to reduce the strength of the skeletons (my ultimate goal) but it appeared to have zero effect. No errors were produced in the log via debug mode or otherwise.

Is this an incompatibility with the newer Forge version? Needed the newer version because of JEI and Morpheus.

**Minecraft Version:** 1.12.2
**Forge Version:** 14.23.5.2836
**Mods Present:** https://i.imgur.com/ULLTERb.png (please forgive my screenshot, I was too lazy to type it all out)

**Comment by Insane96** [comment]
Having the same issue
```json
[{
		"mob": ["minecraft:skeleton"],
		"nbt": {
			"HandDropChances": [ -327.67, -327.67 ]
		},
		"healthmultiply": 2,
		"result": "default"
}]

```
Skeletons have no double health or the correct HandDropChances

**Comment by McJty** [comment]
What does HandDropChances do?
Also what is the entire rule file?

**Comment by coryjreid** [comment]
My entire file is included in the linked Gist. All my other files are empty.

I personally have no idea what that NBT tag is.

**Comment by Insane96** [comment]
Changes the drop chances for items in main-hand and off-hand (e.g. Bows for skellys)

Full _spawn.json_
https://gist.github.com/Insane96/660ae540242bb70e0c1535ae0df3ddfc

**Comment by McJty** [comment]
How are you actually spawning the zombies? The rules only fire for natural spawns

**Comment by Insane96** [comment]
Yep, eggs spawn do not work. Natural spawns have doubled health but have no modified NBT

**Comment by McJty** [comment]
Ok, so maxhealth is working correctly then. The modified NBT problem is related to another issue which is that you cannot apparently modify all NBT with the method I'm using. For example, customName isn't supported either. I guess I'll have to provide custom actions for those NBT values that are not working.  Can someone explain to me what those HandDropChances are exactly?

**Comment by Insane96** [comment]
HandDropChances: List of float values representing the chance for a handheld item to drop.
ArmorDropChances: List of float values representing the chance for a worn armor item to drop.

**Comment by coryjreid** [comment]
I've been exploring this a bit more and wanted to update with my results.

**History**
I didn't specify but should have: all of this testing was occurring in single player. I was building a modpack at the time and so testing configurations locally and via LAN games to make sure things worked as desired. 

**Latest Mods In Use**
I removed all mods except:
- In Control!
- The One Probe
- OptiFine

I discovered in testing that OptiFine is 100% the culprit (big surprise - not).

**Steps to Reproduce**
1. Setup In Control! `spawn.json` config file as follows:
```
[
    {
        "mob": [
            "minecraft:skeleton"
        ],
        "healthmultiply": 0.5,
        "result": "default"
    },
    {
        "result": "deny"
    }
]
```
2. Add OptiFine (1.12.2_HD_U_E4_pre4), In Control! (1.12-3.9.10), and The One Probe (1.12-1.4.28)
3. Launch the game and make a new world (creative, seed: 1)
4. Fly around checking skeleton health

With OptiFine installed: skeletons have between 0 and 10 health
Without OptiFine installed: skeletons always have 10 health (as desired)

I have since tested `damagemultiply` as well by setting its value to `0` in an effort to make it impossible for skeletons to damage the player. This does not appear to work as skeletons can still damage the player, but I wonder: is this possibly related to the fact that skeletons shoot arrows and the _arrow_ is what actually damages the player? If so, is it possible to adjust the damage the arrows do but only to players (I assume probably not)? I ask this because if I multiply zombies' damage by 0, they are incapable of hurting me (as expected).

So in the end - I would say that the original issue that I reported seems not to be an issue afterall. And I wonder if you, @McJty, can shed some light on the possibility of adjusting arrow damage (as asked above)?

**Comment by Zhang-Wei-666** [comment]
I also encountered the same problem in my modpack.

``` json
[{
    "result": "default",
    "mob": "minecraft:*",
    "healthmultiply": 3,
    "damagemultiply": 3
}]
```

https://github.com/Minecraft-Origin/Minecraft-Origin/tree/d948a5c5b65e4157ef1b8ebfa4c429d7bf621044

**Comment by McJty** [comment]
Add "onjoin": true to your rules. Damage and health options must be set in onjoin rules

**Comment by tyon2006** [comment]
Hey! I'm having this exact same issue. I removed optifine and added the "onjoin:" true rule, but its adding health 2 or 3 times on a single mob. If i spawn with an egg, it works 100% of the time. If the mobs spawn naturally, its almost always wrong at a 2-3 times rate.In the screenshot, I would expect 430HP (+400hp as my rule indicates, but its applied 3 times).

Spawn.json is here:
https://pastebin.com/K2YfWUHm

Example:
![image](https://user-images.githubusercontent.com/26413035/86993192-6056fc00-c171-11ea-9f46-5799c1568316.png)
