### ISSUE TITLE
[Feature Request] Scale Maxcount/Mincount by the number of players 

### ISSUE THREAD

**Issue by Darkere** [McJty/InControl#126]
Setting a max count for entities works great if you only have a single group of players on a server.

It doesn't work so well when there are multiple groups of players who should ideally face the same amount of mobs. 

Thus the option to scale the max count with the number of players online.

**Comment by MechanosG** [comment]
I second this suggestion.  Or alternatively, have the max count affect each player locally.  That way an individual that's already hit his mob count, can't just take up the rest too.

**Comment by McJty** [comment]
I have plans for this. I also plan to do it like vanilla does (per loaded chunk)

**Comment by McJty** [comment]
Will be implemented next release

**Comment by MechanosG** [comment]
Awesome.  Thanks!
