### ISSUE TITLE
Mobkill Command

### ISSUE THREAD

**Issue by Terpo** [McJty/InControl#13]
It would be very helpful for testing if you would add a command for mob control and killing.

something like a /killall type ["hostile","passive"]

A good example of a failed experiment:
![2017-04-09_11 55 20](https://cloud.githubusercontent.com/assets/4256058/24836510/e0e6141a-1d1d-11e7-8dec-a1d60c558bb3.png)

**Comment by McJty** [comment]
Implemented next release
