### ISSUE TITLE
How do I properly use minlight/maxlight?

### ISSUE THREAD

**Issue by MechanosG** [McJty/InControl#130]
So the variable naming and wiki's wording has got me a little confused.  If I were to do something like..

```{
{
	"hostile": true,
	"minlight": 2,
	"result": "deny"
}
```

Would that prevent hostile mobs from spawning unless light level is 2 or lower?  Or would that prevent them from spawning if light level is 2 or higher?

**Comment by McJty** [comment]
Sorry for the late reply. Have been busy

But basically it means that the rule will fire if the light is at least 2. And if the rule fires the spawn is denied. So this means that mob spawning will be denied if light is more then 2

**Comment by MechanosG** [comment]
Ok, thx.
