### ISSUE TITLE
add entities to list of spawnables

### ISSUE THREAD

**Issue by PrincessAlkimza** [McJty/InControl#136]
Is there way to add entities to the list that spawn.json can list, there are a considerable few that can't be applied to the config file.

**Comment by McJty** [comment]
All mobs are already available. What do you mean exactly?

**Comment by PrincessAlkimza** [comment]
I disagree. When I entered the command to view the list it was missing several available mobs. I thought the server might be clipping the list short, but when I put in the names for some mobs that were not listed it claimed them unknown. The ghast and blaze were two such mobs which is what I really found odd. 
Server thread/ERROR [incontrol]: Unknown mob 'minecraft.ghast'!
Server thread/ERROR [incontrol]: Unknown mob 'minecraft.blaze'!

This is exactly as it said. If it helps I'm using the modpack All the Mods 3

**Comment by McJty** [comment]
You used a dot instead of a colon. Use minecraft:ghast instead of minecraft.ghast

**Comment by PrincessAlkimza** [comment]
... I apologize.
