### ISSUE TITLE
Did the last few updates completely break prior jsons?

### ISSUE THREAD

**Issue by Boolyman** [McJty/InControl#140]
I had functional spawn and potential spawn jsons prior to the last few updates.  Now mobs are spawning nonstop until the entity count makes the game slow to a crawl.  I see that you added more functions to the spawn syntax, but nothing I read should have made my files not work anymore.

This is how my potentialspawn is formatted:
                            {
        "dimension": 0,
        "mob": "ftrsquids:rocketsquid",
        "weight": 8,
        "groupcountmin": 1,
        "groupcountmax": 2
      }

This is how my spawn file is formatted

  {
        "mob": "ftrsquids:rocketsquid",  
    "mincount": 6,
    "result": "deny"
  }

This USED to cap their spawn at 6.... but now they, and every other mob, spawn dozens nonstop.

**Comment by McJty** [comment]
What version are you using?

**Comment by Boolyman** [comment]
If I use version 3.9.10 the script works fine.... any versions after that make the spawns go crazy.

![2019-07-19 06_22_19-Greenshot](https://user-images.githubusercontent.com/24765883/61532042-3fd8e380-a9ee-11e9-9e5a-459bf04723ee.png)

**Comment by McJty** [comment]
Can you be more specific on which version it is failing. The reason I ask is that there is an important difference

**Comment by Boolyman** [comment]
3.9.12

On a side note, I have an open ticket over on your FX Control mod as well.  If you get a chance, I know you just got back from vacation, so you probably have your hands full.

**Comment by McJty** [comment]
I fixed the issue in InControl. Will be fixed next release. I'll check out FxControl later
