### ISSUE TITLE
The refreshed creature does not respond correctly to the healthmultiply option

### ISSUE THREAD

**Issue by Zhang-Wei-666** [McJty/InControl#145]
**spawn.json**
``` json
[{
    "onjoin": true,
    "result": "default",
    "mob": "minecraft:*",
    "healthmultiply": 3,
    "damagemultiply": 3
}]
```

The amount of blood that naturally refreshes the creature becomes extremely exaggerated, but the amount of blood produced by the Spawn Egg is normal.

**Screenshot**: [1](https://raw.githubusercontent.com/Zhang-Wei-666/Issues/master/McJtyMods/InControl/1/1.png) | [2](https://raw.githubusercontent.com/Zhang-Wei-666/Issues/master/McJtyMods/InControl/1/2.png) | [Use Spawn Egg](https://raw.githubusercontent.com/Zhang-Wei-666/Issues/master/McJtyMods/InControl/1/3.png)

**Modpack**: [Minecraft-Origin](https://github.com/Minecraft-Origin/Minecraft-Origin/tree/13ec928ea122204e741bcb6b1e46dfabba875f3a)
**Minecraft Version**: 1.12.2
**Forge Version**: 14.23.5.2838
**Mod Version**: 3.9.13

**Comment by McJty** [comment]
In Control has no effect on mobs spawned using spawn eggs

**Comment by Zhang-Wei-666** [comment]
@McJty But if you look at the screenshot, the blood volume of the monster using spawn eggs is normal. The naturally generated monster blood volume is wrong.

**Screenshot**: [Screenshot 1](https://raw.githubusercontent.com/Zhang-Wei-666/Issues/master/McJtyMods/InControl/1/1.png) | [Screenshot 2](https://raw.githubusercontent.com/Zhang-Wei-666/Issues/master/McJtyMods/InControl/1/2.png) | [Use Spawn Egg](https://raw.githubusercontent.com/Zhang-Wei-666/Issues/master/McJtyMods/InControl/1/3.png)

**Comment by McJty** [comment]
i don't understand what I'm seeing on those screenshots? Why is the one using spawn egg ok and the others not?

**Comment by Zhang-Wei-666** [comment]
@McJty The normal pig's blood volume is 10, the healthmultiply option is 3, and the pig's blood volume should be 30.
However, in Screenshot 1 and Screenshot 2, the pig's blood volume is 90 and 270.

**Comment by McJty** [comment]
Ah with amount of blood you mean the health. I was confused by that terminology :-)

**Comment by Zhang-Wei-666** [comment]
Google Translate :stuck_out_tongue_closed_eyes:
