### ISSUE TITLE
[Question] I want villagers to spawn in DIM 0 on emerald blocks. (That doesn't work)

### ISSUE THREAD

**Issue by ghost** [McJty/InControl#150]
I guess, that after putting an emerald block villagers have to spawn.
I did everything using a wiki, but after a few attemps nothing happend.
Maybe i made a mistake.
In potentialspawn.json i wrote this:
  {
    "dimension": 0,
    "mobs": [
      {
        "mob": "minecraft:villager",
        "weight": 5,
        "groupcountmin": 1,
        "groupcountmax": 5
      }
    ]
  }
And villagers began to spawn in enormous amount everywhere, but after adding to spawn.json this:
  {
    "mob": "minecraft:villager",
    "block": "minecraft:emerald_block",
    "mincount": 1,
    "maxcount": 5,
    "result": "allow"
  },
  {
    "mob": "minecraft:villager",
    "result": "deny"
  }
They stopped spawning at all (nor on the grass as they did before nor on the emerald blocks)
Any suggestions?
P.S. Thanks for any help!

**Comment by McJty** [comment]
By combining 'mincount' and 'maxcount' that rule will never fire. Only use maxcount. The 'mincount' 1 prevents the rule from working if there is no villager in the world

**Comment by ghost** [comment]
I will try now.

**Comment by ghost** [comment]
Thanks, it works.
