### ISSUE TITLE
Having (more) Issues With Mob Spawns Not Working Right

### ISSUE THREAD

**Issue by Boolyman** [McJty/InControl#155]
I'm trying to get some passive farm animals to spawn only on Mycelium in my skyblock pack.  As you probably already know, Mycelium does not prevent spawns, its the Mushroom island biome that prevents spawns... so spawning on mycelium should not be a problem.  However, they simply don't spawn... at all.  I have copied and modified the syntax directly from your wiki.  Pastebins are below.

Potential Spawn JSON:  https://pastebin.com/VRZDfdZ3

Spawn JSON:  https://pastebin.com/wFZ95Lmu

I'm including the full files, since there may be something wrong in other parts of the syntax that is effecting the part that spawns passives.

**Comment by McJty** [comment]
One remark. You can put multiple mobs in the 'mob' statement using a list. So your spawn.json can be a LOT smaller (and faster) by combining multiple rules.

And since your rule file is so big it is a bit hard for me to determine what should happen. What exactly is going wrong? What is not spawning what should spawn?

**Comment by Boolyman** [comment]
On the bottom of both files are the rules for passive spawns... I want players to be able to set up a large area of Mycelium to attract passive mobs to spawn on their skyblock base.  So I set the potential spawn to be on block "minecraft:mycelium".  And set the spawn json to deny all spawns from those animals if not on myelium.  

However, after loading the game and creating a large mycelium area to test this, nothing happens.  I even tested it in a non-skyblock dimension, which is why the potential spawn says dimension 32.  But that dimension also didnt work.   The passive mobs simply dont spawn at all.

**Comment by McJty** [comment]
Hmm again. The rule files are bit big so it is hard to make sense of them but I spot one thing:

Potential spawn for dimension 32:
{
        "mob": "minecraft:pig",
        "weight": 5,
        "groupcountmin": 1,
        "groupcountmax": 2
      }

spawn for dimension 0:
 {
    "dimension": 0,
    "mob": "minecraft:pig",
    "block": "minecraft:mycelium",
    "result": "allow"
  },

Shouldn't that also be 32? At least the dimensions don't seem to match

**Comment by Boolyman** [comment]
Are you messing around with me McJTY? lol... Im explaining everything... and specifically addressed the reason why one said dimension 32.  Even if they dont match, according to this syntax, there should be a bunch of pigs spawning on mycelium in dimension 32... which there are not.  It's your mod, I'm sure you know that already.   The passive mobs aren't spawning in dimension 32... and they weren't when it said dimension 0 either.

**Comment by Boolyman** [comment]
Ok, here, I broke down the files into JUST the parts that reference the animals in question

potential spawn json = https://pastebin.com/GSfVigwF

spawn josn = https://pastebin.com/MKX8CS1v

**Comment by McJty** [comment]
Try to remove the block criterium in potential spawn but keep the ones in spawn. Maybe that helps

**Comment by Boolyman** [comment]
Ok, that seems to be working.  Thank you.
