### ISSUE TITLE
Incontrol crashing on server

### ISSUE THREAD

**Issue by JarDayne** [McJty/InControl#156]
It's fine when I run the files on the client, but the server just crashes.

[crash-2019-09-29_00.20.12-server.txt](https://github.com/McJtyMods/InControl/files/3666384/crash-2019-09-29_00.20.12-server.txt)

**Comment by McJty** [comment]
Show me your in control rule files

**Comment by JarDayne** [comment]
Sorry, it works now. I just removed the ‘maxcount’ rule from all of the spawn config and it works now. The issue I believe was adding that rule to allow mobs to spawn, I use ‘mincount’ to deny any further spawns.
