### ISSUE TITLE
Mobs spawning despite rules stating otherwise

### ISSUE THREAD

**Issue by Boolyman** [McJty/InControl#159]
Im getting HUNDREDS of mobs spawning... the spawn.json is being completely ignored.

Spawn.json = https://pastebin.com/PpDrKFJJ

Potentialspawn.json = https://pastebin.com/9KVSkKGu

**Comment by McJty** [comment]
Your spawn.json is totally wrong. On line 4 you start a new { nesting level:
  "mobs":[
    {"mob": "tfa:tfa_shark",

Why? That doesn't work. Check the wiki for how to actually write the rules: https://wiki.mcjty.eu/mods/index.php?title=ControlMods

**Comment by Boolyman** [comment]
Why?  To group all mobs from that dimension together.  I'm very familiar with your wiki already... obviously I came here for some help because I am not understanding something..  If you could offer me  some assistance instead of just sending me to the wiki and closing the ticket, I would appreciate it.

**Comment by McJty** [comment]
Well the syntax doesn't allow grouping like that. After 'mobs' you can only have a list of mobs. But you have a list of condition expressions after mobs. That doesn't work. i.e. I'm talking about this snippet:

 "mobs":[
 {"mob": "tfa:tfa_shark",
 "onjoin": true,  
 "mincount": 6,
 "result": "deny"
 },

You can only do something like:

  "mobs": ["mob": "tfa:tfa_shark", "othermob", ..."],
  "onjoin": true,  
  "mincount": 6,
  "result": "deny"

Hope this helps
