### ISSUE TITLE
Find and Resolve Issue With Animania

### ISSUE THREAD

**Issue by VinterNacht** [McJty/InControl#167]
Animania does not seem to respect the spawn limits imposed by In Control (Unless, notably, Custom Mob Spawner is also used in the same modpack), resulting in thousands of a given mob spawning even when Mincount and Maxcount are used appropriately.

Could the source of this issue be identified and collaboration be done to attempt to solve this concern?

**Comment by AechtRob** [comment]
Use Animania's own spawn settings in it's own config?
