### ISSUE TITLE
Mob Size Control (New Feature?)

### ISSUE THREAD

**Issue by VinterNacht** [McJty/InControl#168]
I would love to be able to control the size of mobs from mods that have variable size ranges (Such as ZAWA, Dr. Zharks, Lycanites, etc).  If this is possible with the current format I'm not aware of how to utilize it.

**Comment by Enderkitty9** [comment]
Sadly there is no current way for someone to increase the size of a mob's hitbox or size appearance. The only way to increase any size would be through glitches with commands if you are interested:
[video explaining it better](https://www.youtube.com/watch?v=8FwmN7tmLwc)

unless you can somehow do it with the nbt action that I don't know about, it is not possible
[nbt actions](https://minecraft.gamepedia.com/Tutorials/Command_NBT_tags#Entities)

-note I am not the mod creator
