### ISSUE TITLE
Crash (during mod loading)

### ISSUE THREAD

**Issue by TheSnowyChickens** [McJty/InControl#170]
Hello,
I updated all the mods in "Sky Factory 4" for a custom modpack, based on SF4, and at the first start, I got a crash.

Ty :)

[crash-2019-11-25_01.38.52-client.txt](https://github.com/McJtyMods/InControl/files/3884365/crash-2019-11-25_01.38.52-client.txt)

All mods are up to date (visible in the crash log)
Forge: 2847
IC: incontrol-1.12-3.9.16

**Comment by McJty** [comment]
The problem is in one of the spawn.json rules. There is a JSON syntax error there. Feed your json to a json validator to see where the problem is

**Comment by TheSnowyChickens** [comment]
Okay

**Comment by TheSnowyChickens** [comment]
hmm, all jsons are correct. (I used: https://jsonformatter.curiousconcept.com/)

I try now to delete all jsons are write them new / copy it.
I think I can close this issue. (if not, reopen it xd )

But thx @McJty 

Edit: the problematic json is: 
[json file.zip](https://github.com/McJtyMods/InControl/files/3888458/json.file.zip)
