### ISSUE TITLE
1.15 perchunk/perplayer not ported yet

### ISSUE THREAD

**Issue by Darkere** [McJty/InControl#180]
Probably at least this todo https://github.com/McJtyMods/InControl/blob/9f8148d7d41c307184cb9db700df0151253e9f1a/src/main/java/mcjty/incontrol/rules/RuleCache.java#L161

**Comment by EnterFor** [comment]
When will it be effective.
My server monster could not control the quantity well, resulting in lag.....

**Comment by McJty** [comment]
Soon (TM). I hope in one of the next days

**Comment by EnterFor** [comment]
Thanks for your reply, I will keep an eye on it, I will die without this Mod...

**Comment by McJty** [comment]
I released this a few days ago
