### ISSUE TITLE
All Mobs Spawning Certain Item (and I don't want them to).

### ISSUE THREAD

**Issue by ghost** [McJty/InControl#182]
Here's the code I added to loot.json. I want only the mobs listed in each entry to drop the Heart Container item. Unfortunately, every single mob is not dropping the container. Can someone help?

  {
    "mob": "erebus:erebus.antlion_boss",
    "player": true,
	"random": 1,
    "item": "scalinghealth:heartcontainer",
    "itemcount": "1-1/1-1/1-1"
  },
  {
    "mob": "erebus:erebus.crushroom",
    "player": true,
	"random": 1,
    "item": "scalinghealth:heartcontainer",
    "itemcount": "1-1/1-1/1-1"
  },
  {
    "mob": "erebus:erebus.tarantula_mini_boss",
    "player": true,
	"random": 1,
    "item": "scalinghealth:heartcontainer",
    "itemcount": "1-1/1-1/1-1"
  },
  {
    "mob": "erebus:erebus.umber_golem_idol",
    "player": true,
	"random": 1,
    "item": "scalinghealth:heartcontainer",
    "itemcount": "1-1/1-1/1-1"
  },  {
    "mob": "twilightforest:snow_queen",
    "player": true,
	"random": 1,
    "item": "scalinghealth:heartcontainer",
    "itemcount": "1-1/1-1/1-1"
  },
  {
    "mob": "minecraft:elder_guardian",
    "player": true,
	"random": 1,
    "item": "scalinghealth:heartcontainer",
    "itemcount": "1-1/1-1/1-1"
  },
  {
    "mob": "twilightforest:naga",
    "player": true,
	"random": 1,
    "item": "scalinghealth:heartcontainer",
    "itemcount": "1-1/1-1/1-1"
  },
  {
    "mob": "twilightforest:lich",
    "player": true,
	"random": 1,
    "item": "scalinghealth:heartcontainer",
    "itemcount": "1-1/1-1/1-1"
  },
  {
    "mob": "twilightforest:minoshroom",
    "player": true,
	"random": 1,
    "item": "scalinghealth:heartcontainer",
    "itemcount": "1-1/1-1/1-1"
  },
  {
    "mob": "twilightforest:hydra",
    "player": true,
	"random": 1,
    "item": "scalinghealth:heartcontainer",
    "itemcount": "1-1/1-1/1-1"
  },
  {
    "mob": "twilightforest:ur_ghast",
    "player": true,
	"random": 1,
    "item": "scalinghealth:heartcontainer",
    "itemcount": "1-1/1-1/1-1"
  },
  {
    "mob": "twilightforest:yeti_alpha",
    "player": true,
	"random": 1,
    "item": "scalinghealth:heartcontainer",
    "itemcount": "1-1/1-1/1-1"
  },
  {
    "mob": "twilightforest:giant_miner",
    "player": true,
	"random": 1,
    "item": "scalinghealth:heartcontainer",
    "itemcount": "1-1/1-1/1-1"
  },
  {
    "mob": "twilightforest:knight_phantom",
    "player": true,
	"random": 1,
    "item": "scalinghealth:heartcontainer",
    "itemcount": "1-1/1-1/1-1"
  },
  {
    "mob": "aether_legacy:valkyrie_queen",
    "player": true,
	"random": 1,
    "item": "scalinghealth:heartcontainer",
    "itemcount": "1-1/1-1/1-1"
  },
  {
    "mob": "aether_legacy:slider",
    "player": true,
	"random": 1,
    "item": "scalinghealth:heartcontainer",
    "itemcount": "1-1/1-1/1-1"
  },
  {
    "mob": "aether_legacy:sun_spirit",
    "player": true,
	"random": 1,
    "item": "scalinghealth:heartcontainer",
    "itemcount": "1-1/1-1/1-1"
  },
  {
    "mob": "lost_aether:king_aerwhale",
    "player": true,
	"random": 1,
    "item": "scalinghealth:heartcontainer",
    "itemcount": "1-1/1-1/1-1"
  },
  {
    "mob": "atum:pharaoh",
    "player": true,
	"random": 1,
    "item": "scalinghealth:heartcontainer",
    "itemcount": "1-1/1-1/1-1"
  },  
  {
    "mob": "netherex:ghast_queen",
    "player": true,
	"random": 1,
    "item": "scalinghealth:heartcontainer",
    "itemcount": "1-1/1-1/1-1"
  },
  {
    "mob": "grue:entitygrue",
    "player": true,
	"random": 1,
    "item": "scalinghealth:heartcontainer",
    "itemcount": "1-1/1-1/1-1"
  },
  {
    "mob": "thebetweenlands:spirit_tree_face_large",
    "player": true,
	"random": 1,
    "item": "scalinghealth:heartcontainer",
    "itemcount": "1-1/1-1/1-1"
  },
  {
    "mob": "thebetweenlands:dreadful_mummy",
    "player": true,
	"random": 1,
    "item": "scalinghealth:heartcontainer",
    "itemcount": "1-1/1-1/1-1"
  },
  {
    "mob": "thebetweenlands:fortress_boss",
    "player": true,
	"random": 1,
    "item": "scalinghealth:heartcontainer",
    "itemcount": "1-1/1-1/1-1"
  },
  {
    "mob": "thebetweenlands:sludge_menace",
    "player": true,
	"random": 1,
    "item": "scalinghealth:heartcontainer",
    "itemcount": "1-1/1-1/1-1"
  },
  {
    "mob": "iceandfire:dragon",
    "player": true,
	"random": 1,
    "item": "scalinghealth:heartcontainer",
    "itemcount": "1-1/1-1/1-1"
  },
  {
    "mob": "iceandfire:icedragon",
    "player": true,
	"random": 1,
    "item": "scalinghealth:heartcontainer",
    "itemcount": "1-1/1-1/1-1"
  },
  {
    "mob": "iceandfire:seaserpent",
    "player": true,
	"random": 1,
    "item": "scalinghealth:heartcontainer",
    "itemcount": "1-1/1-1/1-1"
  },
  {
    "mob": "thaumcraft:eldritchgolem",
    "player": true,
	"random": 1,
    "item": "scalinghealth:heartcontainer",
    "itemcount": "1-1/1-1/1-1"
  },
  {
    "mob": "thaumcraft:eldritchwarden",
    "player": true,
	"random": 1,
    "item": "scalinghealth:heartcontainer",
    "itemcount": "1-1/1-1/1-1"
  },
  {
    "mob": "minecraft:ender_dragon",
    "player": true,
	"random": 1,
    "item": "scalinghealth:heartcontainer",
    "itemcount": "1-1/1-1/1-1"
  },
  {
    "mob": "specialmobs:huskzombie",
    "player": true,
	"random": 0.1,
    "item": "atum:scarab",
    "itemcount": "1-1/1-1/1-1"

**Comment by McJty** [comment]
Can you check the logs to see if there is an error there?

**Comment by ghost** [comment]
No errors came through on the log, but I did some testing and I don't think the issue is on InControl's side. Seems like in trying to edit the loot tables associated with the iceandfire:dragon mob, the drops of all entities are affected.
