### ISSUE TITLE
How do I block all mobs except for a couple?

### ISSUE THREAD

**Issue by Saereth** [McJty/InControl#192]
Basically im trying to figure out how I'd block all mobs in a certain dimension (got that part working) but I need to allow like 2 different mob types to still spawn. I dont see any methods for setting exceptions, how would I go about this?

**Comment by McJty** [comment]
First make rules for the two mobs that are allowed to spawn and then put "allow" as result for those rules. Then make a rule to deny the rest

**Comment by Saereth** [comment]
cool thanks!
