### ISSUE TITLE
[1.12.2] Spawn cap rules do not function whatsoever, including the wiki example! +other issues

### ISSUE THREAD

**Issue by property-owner** [McJty/InControl#205]
I'm trying to make certain mobs spawn in the nether fortress, but many things seem to now work as intended. I originally set them to spawn with "structure": "Fortress", though the mobs only spawn at one coordinate point, which is the point given by the /locate command. So this was a let down. (I was thinking maybe this could function if it worked by having the rule apply in a radius from the cords, on a specific block type, and between a min and max height relative to the point, though there is no way to specify radius!) The only way I could get the mob (the Vindicator) to spawn in the fortress is by using:
"dimension": -1,
"block": "minecraft:nether_brick"
Though spawn cap rules seem to not function in this mod, and hundreds of the mob spawn within a minute. The only thing close to a fix I could find is by adding " "random": 0.1 ", but they'll still spawn in huge amounts given enough time. I tested every combination and example of spawn limiting given by the wiki, in both the spawn.json and potentialspawn.json file, and this problem still consists. Then, I copy/pasted the example for skeleton limiting, I changed the value of 50 to 2, and did /ctrlreload, AND /kill @e[type=!player], and I looked up to see three skeletons nearby. The spawn limiting does not function!!! In addition, this is the code for the test with the skeletons:
  {
    "dimension": 0,
    "mob": "minecraft:skeleton",
    "mincount": {
      "amount": 2,
      "mod": "minecraft",
      "hostile": true,
      "perplayer": true
    },
    "result": "deny"
  }

 Hopefully its a matter of a quick bug fix. If this does get fixed, thanks in advance! :)

**Comment by McJty** [comment]
Spawn limiting sure does work. It's one of the most used feature of In Control by many people. But your report is somewhat confusing. Can you give me a simple rule for spawn, what you expect to happen and what is happening instead.

**Comment by property-owner** [comment]
> Spawn limiting sure does work. It's one of the most used feature of In Control by many people. But your report is somewhat confusing. Can you give me a simple rule for spawn, what you expect to happen and what is happening instead.

[
    {
        "dimension": 0,
        "mob": "minecraft:skeleton",
        "mincount": {
          "amount": 2,
          "mod": "minecraft",
          "hostile": true,
          "perplayer": true
        },
        "result": "deny"
      }
]
I'm in an empty superflat world with these rules, at nighttime. I'm expecting to only see up to two skeletons spawn in total, on the chunks loaded around me. But even after using "/ctrlreload", and killing all entities, there are more than two skeletons that spawn.
The only other mods I'm using at the moment are CraftTweaker, Just Enough Items, LootTableTweaker, Mantle, ModTweaker, MTLib, Xaero's Minimap, and Xaero's World Map.

**Comment by property-owner** [comment]
I just now created a completely new profile, with only this mod installed. The problem still consists when using the example rule from the wiki, but with 2 as the cap rather than 50.

**Comment by McJty** [comment]
Try removing 'mod': 'minecraft'.

**Comment by property-owner** [comment]
Oh wow, so, it works now, thanks man! 😂

**Comment by McJty** [comment]
I need to update the wiki

**Comment by property-owner** [comment]
> I need to update the wiki

btw, in the Spawn examples section, one of the examples says "seasky" rather than "seesky"

**Comment by McJty** [comment]
Thanks. I'll fix that too
