### ISSUE TITLE
Mod interaction incorrect with Ender IO

### ISSUE THREAD

**Issue by misterplus** [McJty/InControl#209]
In short, the Aversion Obelisk (which prevents mob spawns) won't work with incontrol installed. Whether it's a altered spawn, or unaltered. Seems like incontrol is not firing the MobSpawnEvent ?

**Comment by misterplus** [comment]
Minecracft version is 1.12.2, incontrol version 1.12-3.9.16, forge 2847

**Comment by McJty** [comment]
Can you describe what exactly you're doing? What are your rule files?

**Comment by misterplus** [comment]
This issue only appears with non-clean config files
potential spawn: https://paste.ubuntu.com/p/PV56YZ4kPr/
spawn: https://paste.ubuntu.com/p/YQKtGMP3tN/

**Comment by McJty** [comment]
The problem is that In Control spawning will override EnderIO (which is normal). So whenever you use 'allow' or 'default' it will change whatever EnderIO set. I have an idea for a feature to prevent this but this will not be for 1.12 I'm afraid as I no longer work in 1.12

**Comment by McJty** [comment]
Actually I'm wrong. It's already possible. You just must make sure you don't have any rules that specify 'allow'. Only deny mobs. Don't allow them and things will be ok

**Comment by misterplus** [comment]
https://paste.ubuntu.com/p/249NnMgMqm/ Just for anyone who may ran into this. A script like this works, just remove the "result": default/allow
