### ISSUE TITLE
[1.12.2] Vampirism ignores spawn rules.

### ISSUE THREAD

**Issue by Terra-B-Welch** [McJty/InControl#214]
Attempting to block vampirism vampires from spawning in the void biome, they just ignore the rule altogether and spawn anyway.

**Comment by McJty** [comment]
First: show me the rule file you use
Secondly: did you try to add 'onjoin':'true' to the spawn rules?
Thirdly: if this still fails its actually not a bug in In Control but in the other mod

**Comment by Terra-B-Welch** [comment]
I literally tried the bare bones spawn rule of the following.
`{
    "mod": "vampirism",
    "onjoin": true,
    "result": "deny"
  },`
Vampires continue to spawn regardless. This rule does not do anything.

**Comment by McJty** [comment]
Then there is nothing In Control can do. Some mods don't play by the spawning rules

**Comment by Terra-B-Welch** [comment]
That really sucks cause vampirism is naughty and spawns its mobs in the void...

**Comment by McJty** [comment]
Doesn't it have configs itself to control this? If not I would contact the author of that mod and see how to fix this

**Comment by Terra-B-Welch** [comment]
It does not have configs for it. But I do believe I found one way to fix my issue. Vampires are considered passive for some reason so adding in the following code and doing a kill command on all the vampires caused no more to spawn in the void.

`{
    "passive": true,
    "biometype": "VOID",
    "result": "deny"
  },`

I know it's a bandaid fix but it works for me nonetheless, I did the same with hostile mobs, since I don't want any natural spawns in the void biome anyway(for mystcraft I want void biome ages to never have spawns apart from mobs I bring in manually so this is perfect)

**Comment by McJty** [comment]
Hmm that's strange. Are you sure you got the MODID right then? Because if that last rule works then the first one you did should work too provided "vampirism" is right

**Comment by Terra-B-Welch** [comment]
I did check it, it is weird why the mod one didnt work but just doing global passive did, but regardless it seems to be fixed now. I guess this can be closed.

**Comment by kanzaki1201** [comment]
This is probably caused by Vampirism not inheriting their mobs from IMob by default. Forcing them to be IMob will resolve the issue.
See https://github.com/TeamLapen/Vampirism/issues/199 and https://github.com/TeamLapen/Vampirism/wiki/IMob-issue
