### ISSUE TITLE
[1.16.4] Crash on load

### ISSUE THREAD

**Issue by mathiashemmer** [McJty/InControl#222]
Crash on game load, after resource loading finishes
"InControl (incontrol) encoutered an error during the common_setup event phase"
**Exception**: java.lang.NoSuchFieldError: ACTION_CONTINUE
**Version**: 1.16-5.0.3

Was working fine until I installed some other mods... After a few reinstalls, found out it happens with some mods:
Large Ore Deposits (or its dependency  ForgeEndertech)
Cauldron Recipes (or its dependecy Bookshelf)
Geolosys

Pastbin (with Large Ore Deposits): https://pastebin.com/ifpJJJkC

<details>
<summary>spawn.json</summary>
`
[
    {
        "hostile": true,
        "healthmultiply": 2,
        "damagemultiply": 5
    },
    {
        "onjoin":true,
        "mob":"minecraft:slime",
        "result":"deny"
    }
]
`
</details>

**Comment by McJty** [comment]
Did you also report to those other mods. Not much I can do from my side I'm afraid

**Comment by mathiashemmer** [comment]
Well, as I tested with a few other mods, it seems that the problem could be on your side... Not sure what causes this to occur, but it only happens when there is something inside the spawn.json file.
Leaving it blank, loading the game, editing it and running \ctrl reload causes minecraft to die
The error is the same for any of the mods. Should I report for each and every other mod that I find it out? Would be nice to have a work around

Found out it happens with the River Redux mod too

**Comment by McJty** [comment]
I'll investigate tomorrow. Probably it has to do with the version of forge

**Comment by McJty** [comment]
I cannot reproduce this and I also don't understand how this can happen

**Comment by mathiashemmer** [comment]
Ive tried reinstalling some mods in a separete profile, and I can't seem to replicate it...  Maybe some config of some mod is bad behaving with In Controll... I'll try to find more information on this. If I can't by any means locate wth is going on, I'll just recreate my profile.

Anyways, I'll keep you informed.

**Comment by Yoskio** [comment]
im having this problem too was working fine until i edited it did /incontrol reload and game crashed. now it says "Exception message: java.lang.NoSuchFieldError: ACTION_CONTINUE". it says this no matter what if theres anything in the config files. when they empty it is fine though

**Comment by McJty** [comment]
Well people are using In Control on 1.16.4 with no problems so I have no clue what's going on

**Comment by McJty** [comment]
Finally found and fixed. To fix this bug you need to update FxControl
