### ISSUE TITLE
List latest Forge version

### ISSUE THREAD

**Issue by tir38** [McJty/InControl#225]
I had an issue with latest version of InControl not working with latest version of Forge. I see that you updated to latest Forge [only a few days ago](https://github.com/McJtyMods/InControl/commit/9ead2c2a4a7edf25b82bac813674fb22f6f72478). It would be helpful if you had "works with Forge version x.y.z" listed either in the README, wiki, or on CurseForge. That would have helped me troubleshot the problem much sooner.

P.S. thanks for building this in the first place.

**Comment by McJty** [comment]
What was the issue?

**Comment by tir38** [comment]
NM. My bad. I was trying to run 1.12 on a 1.16 server
