### ISSUE TITLE
[1.12.2] Block command not working on mobs

### ISSUE THREAD

**Issue by Drakkxs** [McJty/InControl#227]
This code does nothing, there are no errors, it just does nothing
https://pastebin.com/6BWG6PXx

**Comment by McJty** [comment]
How are you testing this? Can you describe things a bit more? How do you know it's not working?

**Comment by Drakkxs** [comment]
because there are no mobs spawning Where I want them to spawn
i want them to spawn on a specific block and they dont
even if i set the weight to 100 
in a fresh modpack with only incontrol and fx control:
(spawn.json)
[
{
"mob": "minecraft:pig",
"block": "minecraft:emerald_block",
"result": "allow"
},
{
"result": "deny"
}
]
(potentialspawn.json)
[
{
"mobs": [
{
"mob": "minecraft:pig",
"weight": 100,
"groupcountmin": 1,
"groupconuntmax": 2
}
]
}
]

then i reloaded rules and placed down some emerald blocks
no pigs are spawning but i get this when i turn in control debug on
[Server thread/INFO] [incontrol]: Potential 0: class net.minecraft.entity.passive.EntityPig
but no pigs on emerald blocks

**Comment by Drakkxs** [comment]
@McJty 
can you help me with this?

**Comment by McJty** [comment]
How far are you from the emerald blocks? Mobs don't spawn near the player

**Comment by Drakkxs** [comment]
@McJty
it still didn't work i went all the way until it was out of my render distance then came back and no pigs
is there any other way to make a mob spawn on a block?
I copy and pasted the example on the wiki, and it didn't work
i don't know what iam doing wrong

**Comment by DRAKKKS** [comment]
I copy and pasted the example on the wiki, and it didn't work

**Comment by DRAKKKS** [comment]
i don't know what iam doing wrong

**Comment by Drakkxs** [comment]
@McJty 
Is there another mob I can use to make a mob spawn on a block?

**Comment by Drakkxs** [comment]
@McJty  is  1.12.2 not supported any more?

**Comment by McJty** [comment]
I don't work on it anymore. I simply don't have the time and 1.12 is getting old

**Comment by Drakkxs** [comment]
Oh ok

**Comment by Drakkxs** [comment]
Thanks for the help anyway
