### ISSUE TITLE
ConcurrentModificationException in Minecraft 1.16.4

### ISSUE THREAD

**Issue by viktor141** [McJty/InControl#229]
mod version incontrol:1.16-5.0.3

https://pastebin.com/7SyMni6N

Do I need to say something?
I think you are trying to modify the HashMap in forEach. Just don't do it

**Comment by McJty** [comment]
Can I see your rule files?

**Comment by viktor141** [comment]
yes. I change only spawn.json
Other files are empty.

[
	{
    "mincount": {
      "amount": 20,
	  "hostile": true,
      "perplayer": true
    },
    "result": "deny"
	},
	{
	"maxspawndist": 50,
	"result": "deny"
	}
]

**Comment by pjc21** [comment]
Also getting an error like this whenever using 'mincount' in the spawn.json 
1.16.4 - forge 35.1.4
incontrol-1.16-5.1.5

If I try to create a new world with this [spawn.json](https://pastebin.com/NdJPRQyp) it will get stuck, sometime at 3% other times at 20% with below lanucher log after kill process.
[GDLauncherErrorLog](https://pastebin.com/eAkuFsDf)

If I create a new world and then add to the spawn.json and reload in-game it will wok for a little then crash.
[crash-2021-02-24_18.17.18-server.txt](https://pastebin.com/Zkv4ssuM)
[latest.log](https://pastebin.com/U6s0WJd0)

**Comment by McJty** [comment]
Will be fixed next release (soon)
