### ISSUE TITLE
Feature Request: Dimensional Awareness

### ISSUE THREAD

**Issue by ScottKillen** [McJty/InControl#23]
Perhaps add a spawn control check for dimension?

Great mod!

**Comment by McJty** [comment]
That's already there

**Comment by ScottKillen** [comment]
Sorry! 😀 

I read the documentation several times and only see it now that you pointed it out. I must be blind. 👓

**Comment by ScottKillen** [comment]
Sorry! 😀 

I read the documentation several times and only see it now that you pointed it out. I must be blind. 👓
