### ISSUE TITLE
[1.16.5] "Block" + "Mob" -Commands not working together in spawn.json, freezing World-Gen

### ISSUE THREAD

**Issue by Zothen1973** [McJty/InControl#235]
**spawn.json**
[
  {
    "mob": "minecraft:cow",
    "block": ["minecraft:stone", "minecraft:cobblestone"],
    "result": "allow"
  },
  {
    "mob": "minecraft:cow",
    "result": "deny"
  }
]

RESULT:

![grafik](https://user-images.githubusercontent.com/77007295/107130366-dfa9db00-68cc-11eb-8bcd-5a6d3600530c.png)

**Comment by McJty** [comment]
Fixed in the latest release
