### ISSUE TITLE
[1.16.4] Using onjoin causes chunks not to load & entities frozen 

### ISSUE THREAD

**Issue by pjc21** [McJty/InControl#241]
When using onjoin: true in spawn.json and loading into a world causes most chunks will not load & entities will be frozen in place.
Then when exiting world it will get stuck on saving world, need to then force kill. 

Upon restart MC and load world no chunks will show at all.

Removing the onjoin line then restart MC,  load world all fine again.

1.16.4 
Forge - 35.1.4
incontrol-1.16-5.1.5

```
[
  {
    "dimension": "minecraft:overworld",
    "mod": "alexsmobs",
    "onjoin": true,
    "seesky": true,
    "passive": true,
    "result": "default"
  }
]
```

![2021-02-24_20 33 11](https://user-images.githubusercontent.com/4660190/108983842-67705180-76e3-11eb-8004-be49ccc6865c.png)
![2021-02-24_20 39 05](https://user-images.githubusercontent.com/4660190/108983879-70f9b980-76e3-11eb-8a75-176ebc0d3185.png)
![2021-02-24_20 53 17](https://user-images.githubusercontent.com/4660190/108983895-75be6d80-76e3-11eb-9ccf-7d9d82840a9c.png)

Adding log but does not seem to show anything
[latest.log](https://pastebin.com/s9q2CLPb)

**Comment by McJty** [comment]
This should be already fixed next release (soon)
