### ISSUE TITLE
1.16 Hard caps?

### ISSUE THREAD

**Issue by BLSK** [McJty/InControl#242]
is this just areas people don't explore or is there something not allowed in Minecraft in newer versions?
is it possible to allow stats to be unlocked so mobs and what not can have say the 2b I think last I knew was max or can't it be done?

![2021-03-01_03 49 06](https://user-images.githubusercontent.com/8443396/109473528-66bc2000-7a41-11eb-8ea3-91ccdcb64b9c.png)

hopefully can... because a mob like this I can kill fairly easily... but it also makes me wonder if say the damagemultiplier of 250k also works... for a base world

**Comment by McJty** [comment]
That's a hard limit. You cannot go beyond that. It's simply not possible as the variable used to store that number can't hold more

**Comment by BLSK** [comment]
ok thanks for the info... guess I will adjust things accordingly then :)
too bad minecraft changed over the versions... love mojang :(
