### ISSUE TITLE
World Gen Freeze Bug with spawn.json

### ISSUE THREAD

**Issue by SgtSteakfries** [McJty/InControl#244]
It might be my ineptitude at JSON programming, but when I tried altering the spawn file, the game I run fails to save and quit.

Furthermore, the internal server basically shuts down, and when creating a new world, it would go for some time before indefinitely freezing (needing to shut off the game via Task Manager).

Here's the entire contents of spawn.json

[    
{
    "mob": "minecraft:blaze",
    "block": "minecraft:netherrack",
	"maxcount": {
        "amount": 20
    },
    "result": "allow"
},
{
    "mob": "minecraft:blaze",
    "result": "deny"
},
{
        "mob": "minecraft:creeper",
        "maxcount": {
            "amount": 3
        },
        "result": "deny"
},
{
        "mob": "minecraft:zombie",
        "maxcount": {
            "amount": 40
        },
        "result": "deny"
}

]

--------

Here's the potentialspawn.json file, the only other file I've touched

[
  {
    "dimension": 0,
    "mobs": [
      {
        "mob": "minecraft:blaze",
        "weight": 5,
        "groupcountmin": 1,
        "groupcountmax": 2
      }
    ]
  }
]

**Comment by SgtSteakfries** [comment]
I also couldn't find any debug messages in the in-game output either.

**Comment by McJty** [comment]
Version please

**Comment by SgtSteakfries** [comment]
Minecraft 1.15.2

Forge 31.2.44

**Comment by SgtSteakfries** [comment]
There was no documentation for 1.15.2, so I used the 1.14 documentation instead.

It seemed to work for the potentialspawn.json, but the freeze happened when I added to the spawn.json

**Comment by McJty** [comment]
The 1.15.2 versions are a bit dead right now. I recommend moving to 1.16.5. That's the version everyone is moving too

**Comment by SgtSteakfries** [comment]
Ah crap, I was using this for a modpack, but thanks anyway.

**Comment by Darkstar6423** [comment]
I'm on 1.16.5 and forge version 36.1.1 and am having the same issue
in my case it only happens on pre-existing worlds, but newly generated ones do not freeze until I restart the game

the Json files are here
https://pastebin.com/PaMMmeSv

**Comment by McJty** [comment]
@Darkstar6423 version of In Control?

**Comment by Darkstar6423** [comment]
5.1.6

**Comment by McJty** [comment]
I'll check it out

**Comment by Darkstar6423** [comment]
I don't know if you found the cause of the issue or not but I tried running it on a server and managed to get a crash report from it.
https://pastebin.com/Q2pp59AX
I hope this helps

**Comment by McJty** [comment]
This was fixed in the 1.16 version some time ago
