### ISSUE TITLE
Biome spawn config

### ISSUE THREAD

**Issue by JessMalFer** [McJty/InControl#246]
Hi, first of all sorry for my English. I´m trying to make a modpack with ice and fire and lotr mod for 1.15, I was trying to use incontrol to schedule the spawning of each mob based on the biome of lotr map. But the truth is I don't know how to program anything and I don't know the Json syntax. I was wondering if anyone has a template that I could work on, I just search for biome spawn and determine mob rarity.
Thank you!

**Comment by McJty** [comment]
The wiki has examples
