### ISSUE TITLE
[1.16.5] rules for mob stats not working for certain entities

### ISSUE THREAD

**Issue by Dyshonored** [McJty/InControl#249]
While I was able to give dynamically spawning mobs increased hit point pool, the health pool buff rules I have set up seems to have not effect on mobs that are generated with the world (ie when the chunk is generated for the first time). For example, enemies such as the illagers in a woodland mansion and piglin brutes in bastions does not benefit from the custom spawn rules at all.

In addition, rules for mob attack damage increase seem to have no effect as well (tested with spiders).

**Comment by McJty** [comment]
Try 'onjoin': true

**Comment by Dyshonored** [comment]
Thank you.
I also noticed that skeletons only spawns with bows despite I added swords and axes to the possible 'helditem' list
Will the above fix solve this problem as well?

**Comment by McJty** [comment]
'helditem' only works in combination with onjoin:true
