### ISSUE TITLE
Request: Weights for held items

### ISSUE THREAD

**Issue by Octopork** [McJty/InControl#25]
Just wondering if it would be possible to have weights for held items.

currently there appears to only be a way to spawn a mob with a selection of equipment
e.g.     "armorchest": ["minecraft:iron_chestplate", "minecraft:golden_chestplate"]

In it's current form it's not practical to have something with a high varience and/or multiple combinations.

if each item could be given a weight rather than just chosen at random from a list(e.g. iron with a 15% chance, gold with a 5% chance and 80% nothing) this functionality would be so much more powerful and useful.

An example of this is i want to add the thermal foundation armors to mobs, to get that many armors onto mobs with a reasonable distibution and balance is just not practically possible with the current system(or what's documented at least if i can already do this)

**Comment by McJty** [comment]
Will be implemented next release with the notation:

 "armorchest": ["5=minecraft:iron_chestplate", "1=minecraft:golden_chestplate"]

The actual values don't matter. It is how big they are relative to each other.

The old notation still works. In that case the value '1' is assumed
