### ISSUE TITLE
stop generation of biome

### ISSUE THREAD

**Issue by azk963** [McJty/InControl#251]
1.15.2 
I'm trying to disable generation of mushroom biome and cows. 
Not sure what i'm doing wrong, but i'm unable to create new worlds (MC gets stuck at the initial 'color squares'), and existing worlds become bugged (reaching world edge won't generate more chunks)
As per [legacy instructions](https://wiki.mcjty.eu/mods/index.php?title=ControlModsLegacy) , I use this code in spawn.json, any idea what i'm missing?
```
[
  {
    "mob": "minecraft:mooshroom",
    "onjoin": true,
    "result": "deny"
  },
  {
    "block": ["minecraft:brown_mushroom_block", "minecraft:red_mushroom_block", "minecraft:mushroom_stem"],
    "result": "deny"
  }
]
```

**Comment by McJty** [comment]
This was fixed in the 1.16 version some time ago
