### ISSUE TITLE
[1.16.5] Suggestion: New Spawner rule for spawning mobs from biome spawnlist

### ISSUE THREAD

**Issue by Zothen1973** [McJty/InControl#262]
I've got an idea for your new spawner system:

Could you add a rule to make the new spawner spawn entities around a player from the biome spawn list the player is actually in or even better, the biome the (random) spawn block in a defined radius is? 

Something like this, which would save a lot of rules for something like just increasing the vanilla spawn cap:

[
  {
    "mob": "minecraft:villager",
    "persecond": 0.5,
    "attempts": 20,
    "amount": {
      "minimum": 2,
      "maximum": 5
    },
    "conditions": {
      "dimension": "minecraft:overworld",
      "mindist": 5,
      "maxdist": 20,
      "maxpassive": 50,
      "fromspawnlist": true
    }
  }
]

**Comment by McJty** [comment]
This is implemented for the next version. It works as follows:

  {
    "mobsfrombiome": "monster",
    "persecond": 0.5,
    "attempts": 20,
    "amount": {
      "minimum": 2,
      "maximum": 5
    },
    "conditions": {
      "dimension": "minecraft:overworld",
      "mindist": 5,
      "maxthis": 150
    }
  }
