### ISSUE TITLE
Game froze with the spawner files

### ISSUE THREAD

**Issue by pwigary** [McJty/InControl#264]
Hi, when I use the spawner file with the spawn file the game froze. But when I use only the spawn file, it's fine. Here's the file:

[Spawn.txt](https://github.com/McJtyMods/InControl/files/6479982/Spawn.txt)
[Spawner.txt](https://github.com/McJtyMods/InControl/files/6479983/Spawner.txt)

The game will turn into something like:

https://ibb.co/9nBDS6k
https://ibb.co/2tbVNDz
https://ibb.co/fN2PMDq

I reproduced this by flying in spectator mode at around y 45, will always happen after less than a minute just by roaming. I had already narrow it down from 200 mods, I can however reproduce the result with only these mods running:

[modlist-15-05-2021_00.41.08.txt](https://github.com/McJtyMods/InControl/files/6480094/modlist-15-05-2021_00.41.08.txt)

Please help!

**Comment by pwigary** [comment]
@McJty

**Comment by McJty** [comment]
No need to ping me. I get to this in due time

**Comment by pwigary** [comment]
alright

**Comment by McJty** [comment]
Can you try to pinpoint which mob in spawner.json causes it? i.e. remove half of the entries and see if you can reproduce it still. Until you find the one that causes it. Thanks

**Comment by pwigary** [comment]
Okie, I'm doing it now

**Comment by pwigary** [comment]
So with enough testing, it seems only the "firefly" one causes the problem. It is true with or without its based mod [supplementary](https://www.curseforge.com/minecraft/mc-mods/supplementaries), and also true in the modpack. Glad it's minimal, I removed it for now.

**Comment by pwigary** [comment]
Update: the issue was gone after removing the condition _"inair": true_
