### ISSUE TITLE
Can't get blazes to spawn in OW with docs code

### ISSUE THREAD

**Issue by juliusedqvist** [McJty/InControl#266]
Hi,

Probably just me not getting something but I've been trying to get blazes to spawn in overworld for hours now =(

I'm using the json provided by docs but it doesnt seem to work

Minecraft version 1.12.2, In control! version 3.9.18

potentialspawn.json:

```
[
  {
    "dimension": 0,
    "mobs": [
      {
        "mob": "minecraft:blaze",
        "weight": 5,
        "groupcountmin": 1,
        "groupcountmax": 2
      }
    ]
  }
]
```
spawn.json:
```
[
   {
      "dimension": 0,
      "mob": "minecraft:blaze",
      "block": "minecraft:netherack",
      "result": "allow"
   },
   {
      "dimension": 0,
      "mob": "minecraft:blaze",
      "result": "deny"
   }
]
```
![image](https://user-images.githubusercontent.com/36112602/119467100-84014180-bd45-11eb-83cb-55d4e1f38167.png)

Image taken at night just after killing all entities, only overworld mobs spawning

**Comment by McJty** [comment]
Try with "Blaze" instead of "minecraft:blaze"

**Comment by juliusedqvist** [comment]
Still not working, I additionally tried with netherrack instead of minecraft:netherrack but without results

**Comment by McJty** [comment]
Don't do 'netherrack'. Change only the Blaze

**Comment by juliusedqvist** [comment]
Tried only changing blaze, didnt work unfortunately

**Comment by juliusedqvist** [comment]
Ok I removed the netherrack part completely and now it works, There's a typo in documentation that says netherack instead of netherrack. Someone should probably change that in case more people just try to copypaste like me lol

**Comment by McJty** [comment]
Why did you reopen this?

**Comment by juliusedqvist** [comment]
So someone would change docs
