### ISSUE TITLE
NBT tags getting overwritten

### ISSUE THREAD

**Issue by levaniphoenix** [McJty/InControl#268]
here is the spawn.json file i am using : https://pastebin.com/iSUh6kGg

This spawns a skeleton that has a bow in one hand and a custom tipped arrow in the other, while this does actually work it has a small bug because of which the tags "CustomPotionColor" and "CustomPotionEffects" (Which are specified in the tipped arrows' nbt data) seem to overwrite each other, if i get rid of "CustomPotionEffects: .... " then the "CustomPotionColor" tag gets applied to the arrow and you can see the color of it. If I put the "CustomPotionColor" tag after the "CustomPotionEffects" then the arrow has no potion effect but has color, they work separately but not together. (If you are curious about the potion id being 50,that's bcz its a modded effect.)
Also If you could tell me the proper syntax for using "CustomName" that would be lovely too..

**Comment by McJty** [comment]
That's not something I have control over. In Control simply takes the NBT and gives it to Minecraft. What MC does with it (i.e. overwriting or something) is not under my control
