### ISSUE TITLE
end spawning mobs

### ISSUE THREAD

**Issue by zachsai** [McJty/InControl#269]
mobs are not spawning when using the block restriction / modifier

`[
    {
        "mob": "minecraft:zombie",
        "persecond": 0.5,
        "attempts": 60,
        "amount": {
          "minimum": 1,
          "maximum": 1
        },
        "conditions": {
            "dimension": "minecraft:the_end",
            "norestrictions":true
        }
      }
]`

`[
  {
    "onjoin":true,
    "mob": "minecraft:zombie",
    "block":"minecraft:end_stone",
    "maxcount": {
      "amount": 40,
      "perplayer": true
    },
    "biome": "minecraft:end_midlands",
    "result": "allow"
  },
  {
    "mob": "minecraft:zombie",
    "result": "deny"
  }

]`

this is what I used

1.16.5
5.1.8

**Comment by McJty** [comment]
Fixed
