### ISSUE TITLE
"inwater": true rule applies to lava...

### ISSUE THREAD

**Issue by FrozenToothpaste** [McJty/InControl#270]
I keep seeing mobs die in lava. I am trying to make mobs spawn in the cave waters, and I fly around in spectator mode and see mobs dying in lava?? I used "inwater": true and "inair": false

Not sure if this is intentional or not... if it is then I guess I need to use mob counter? Or add "inlava" rule as a separate to "inwater"

And yes, the mobs are modded. Specifically ones from Odd Water in 1.16.5. I'm trying to get them spawn in the cavern water of Yung's Better Caves.

**Comment by McJty** [comment]
The 'inwater' test actually uses containsAnyLiquid which probably also qualifies for lava.
I'll see if I can give more precise control

**Comment by McJty** [comment]
I'll fix 'inwater' to only work for water. I'll add 'inliquid' to work for any liquid and 'inlava' to work for lava
