### ISSUE TITLE
[Enquiry] Spawn mobs with items of a specific enchantment

### ISSUE THREAD

**Issue by Dyshonored** [McJty/InControl#272]
Is there a way to give mobs equipment with specific enchantments with the configuration files? (For example, give newly spawned skeletons a bow with the power 3 enchantment.)

**Comment by pjc21** [comment]
Good timing I just posted an example of exactly that [here](https://www.reddit.com/r/feedthebeast/comments/o6j12n/incontrol_doesnt_work_even_with_the_examples_on/h339w8q?utm_source=share&utm_medium=web2x&context=3), but for some reason changing the skeleton helditem requires you to have the "onjoin": true in the rule.
