### ISSUE TITLE
[1.16.5]Unknown mobs.

### ISSUE THREAD

**Issue by bz001** [McJty/InControl#275]
Why did I enter the correct mobs ID,but it still told me unknown mobs?
Here is the my log:https://paste.ubuntu.com/p/k22qFgD6CW/
incontrol version:5.1.9
forger version:1.16.5-36.1.4

**Comment by McJty** [comment]
Are you sure those are the correct mob ids? How did you check that?
For example I see one error already: minecraft:sliverfish
That should be silverfish

minecraft:phatom is also wrong

mekanismaddition:baby_creeper is also wrong

rediscorverd:fish is probably wrong because I don't think the mod is called like that

**Comment by bz001** [comment]
But&nbsp;I've&nbsp;checked&nbsp;the&nbsp;wikis&nbsp;of&nbsp;these&nbsp;mods.&nbsp;These&nbsp;are&nbsp;the&nbsp;IDs&nbsp;of&nbsp;these&nbsp;mobs





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月2日(星期一) 下午2:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [McJtyMods/InControl] [1.16.5]Unknown mobs. (#275)





 
Are you sure those are the correct mob ids? How did you check that?
 For example I see one error already: minecraft:sliverfish
 That should be silverfish
 
minecraft:phatom is also wrong
 
mekanismaddition:baby_creeper is also wrong
 
rediscorverd:fish is probably wrong because I don't think the mod is called like that

**Comment by McJty** [comment]
What are you saying? I don't understand this:

>But&nbsp;I've&nbsp;checked&nbsp;the&nbsp;wikis&nbsp;of&nbsp;these&nbsp;mods.&nbsp;These&nbsp;are&nbsp;the&nbsp;IDs&nbsp;of&nbsp;these&nbsp;mobs

**Comment by McJty** [comment]
Ah now I see. Anyway no. The ids are wrong. Check them again. There are several errors in them. i.e. see the errors that I gave you

**Comment by bz001** [comment]
oh,i see




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月3日(星期二) 下午2:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [McJtyMods/InControl] [1.16.5]Unknown mobs. (#275)





 
Ah now I see. Anyway no. The ids are wrong. Check them again. There are several errors in them. i.e. see the errors that I gave you
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
