### ISSUE TITLE
[1.16.5] I am having issues with the spawning of mobs in groups

### ISSUE THREAD

**Issue by JonathanDI7** [McJty/InControl#276]
I am trying to make it so zombies spawn frequently in big groups
[
 {
  "dimension": 0
  "mob:[
  {
  "mob": "minecraft:zombie",
  "weight": 16,
  "minigroupcount": 15,
  "maxgroupcount": 30
 }  
] 

I am also not sure about the weight mechanic, I'm not sure what is seen as a high value or low or excessive.

**Comment by McJty** [comment]
Don't use potentialspawn in 1.16.5 (as the wiki clearly says). Use spawner.json
