### ISSUE TITLE
Test to swarm blaze on the surface of the overworld

### ISSUE THREAD

**Issue by Hequinoxe** [McJty/InControl#285]
I'm using version: 5.2.1

I do not understand why but I am unable to spawn blaze in overworld, I based my lines on the wiki for the version 1.16;

**In the spawn.json:**
[
  {
    "dimension": "minecraft:overworld",
    "mob": "minecraft:blaze",
	"seesky":true,
    "result": "allow"
  },
  {
    "dimension": "minecraft:overworld",
    "mob": "minecraft:blaze",
    "result": "deny"
  }
]

**In the spawner.json:**
[
  {
    "mob": "minecraft:blaze",
    "persecond": 1,
    "attempts": 600,
    "amount": {
      "minimum": 2,
      "maximum": 5
    },
    "conditions": {
      "dimension": "minecraft:overworld",
	  "inwater":false,
      "mindist": 24,
      "maxdist": 120,
      "minheight": 1,
      "maxheight": 256,
      "maxthis": 1000
    }
  }
]

If I understand correctly the example the ground should be covered with blaze. There's none. Also, before I added the seesky:true rule, there was only one blaze and it was underground.

**Comment by McJty** [comment]
Try adding 'norestrictions': true to spawner.json

**Comment by Hequinoxe** [comment]
That did the trick, thanks
