### ISSUE TITLE
spawning out of control

### ISSUE THREAD

**Issue by javiburatos** [McJty/InControl#291]
I have a question, why does the spawning of vanilla entities get out of control and increase so much?
(spawn.json)
[
  {
	"dimension": 0,
	"mob": "dungeonmobs:dmtroll",
	"result": "deny"
  },
  {
	"dimension": 0,
	"mob": "dungeonmobs:dmmanticore",
	"result": "deny"
  },
  {
	"dimension": 0,
	"mob": "minecraft:creeper",
    "result": "deny"
  },
  {
	"dimension": 0,
	"mob": "minecraft:zombie",
    "result": "deny"
  },
  {
	"dimension": 0,
	"mob": "minecraft:skeleton",
	"result": "allow"
  },
  {
	"dimension": 0,
	"mob": "minecraft:skeleton",
	"mincount": 
	{
      "amount": 10,
      "hostile": true,
      "perplayer": true
    },
    "result": "deny"
  },
  {
	"dimension": 0,
	"mob": "minecraft:spider",
    "result": "deny"
  },
  {
	"dimension": 0,
	"mob":"primitivemobs:haunted_tool",
    "result": "deny"
  },
  {
	"dimension": 0,
	"mob":"primitivemobs:rocket_creeper",
    "result": "deny" 
  },
  {
	"dimension": 0,
	"mob":"primitivemobs:festive_creeper",
    "result": "deny" 
  },
  {
	"dimension": 0,
	"mob":"primitivemobs:support_creeper",
    "result": "deny" 
  }, 
  {
	"dimension": 0,
	"mob":"primitivemobs:skeleton_warrior",
    "result": "deny" 
  },
  {
	"dimension": 0,
	"mob":"primitivemobs:mother_spider",
    "result": "deny" 
  }
]
potentialspawn.json
[
  {"dimension":0,
   "mobs":
   [
     {
	  "mob": "dungeonmobs:dmtroll",
	  "maxheight":55,
	  "weight":1
     }, 
	 {
	  "mob": "dungeonmobs:dmmanticore",
	  "maxheight":55,
	  "weight":1
     },
	 {
	  "mob": "minecraft:creeper",
	  "minheight":56,
	  "weight":1
     },
	 {
	  "mob": "minecraft:zombie",
	  "minheight":56,
	  "weight":1
     },
	 {
	  "mob": "minecraft:skeleton",
	  "minheight":56,
	  "weight":1
     },
	 {
	  "mob": "minecraft:spider",
	  "minheight":56,
	  "weight":1
     }
   ]  
  }
]

**Comment by McJty** [comment]
Your potentialspawn is totally wrong. That's not the syntax you should use. Look at the syntax on how to correctly use potentialspawn

**Comment by javiburatos** [comment]
give me an example of the skeleton pls, I used the syntax of the wiki but dont work
