### ISSUE TITLE
The code of spawn.json didn't work.

### ISSUE THREAD

**Issue by 854342681** [McJty/InControl#294]
Minecraft:1.16.5
forge:36.2.8
mod version:5.2.1
description:I use these code in _spawn.json_ to make wither skeleton only spawn on soul soil,but it doesn't work.Following the code.

```
 {
     "mob": "minecraft:wither_skeleton",
     "block":"minecraft:soul_soil",
     "result": "allow"
 },
 {
     "block": "minecraft:soul_soil",
     "result": "deny"
}

```

**Comment by McJty** [comment]
First describe what you mean by 'doesn't work'. Secondly that syntax is not correct. You are missing [ and ] around it

**Comment by 854342681** [comment]
No wither skeleton spawn on soul soil,and this code just a slice of whole code,I use [ and ] around it .
```
[{
    "mod":"mana-and-artifice:hulking_zombie",
    "dimension": ["minecraft:the_nether","minecraft:the_end"],
    "result": "deny"
},
{
    "mod":"mana-and-artifice",
    "dimension": "minecraft:overworld",
    "minheight": 100,
    "result": "deny"
},
{
    "mob": "minecraft:wither_skeleton",
    "block":"minecraft:soul_soil",
    "result": "allow"
},
{
    "mob":"minecarft:wither_skeleton",
    "result": "deny"
}
]
```

**Comment by McJty** [comment]
Note that spawn.json cannot add spawns. It can only restrict them. If wither skeletons didn't spawn on soul soil before then adding an 'allow' rule will not fix that. You need to add spawning rules to spawner.json in combination with the rules above

**Comment by 854342681** [comment]
Understand.My bad,thank you.
