### ISSUE TITLE
Crashing with incontrol.spawner.SpawnerSystem error

### ISSUE THREAD

**Issue by Boolyman** [McJty/InControl#295]
Hey there,
I am consistently getting a crash due to single ticks taking 180 seconds.  The crash report keeps referencing the incontrol.spawner.SpawnerSystem.getRandomPositionInBox  

I have reviewed my spawner.json and other files, but could not identify what could be causing the issue (or bug).  Below are my files, and the crash report.

Forge - 36.25.8
incontrol-1.16-5.2.1

Crash report: https://paste.gg/p/anonymous/05d9f949393642f4ba44fac1918b4b01

spawner.json: https://paste.gg/p/anonymous/1b1f3e63592644a9bbfbf2b69358ea54

spawn.json: https://paste.gg/p/anonymous/0605977294404ff0be030cda676da675

**Comment by McJty** [comment]
I will check it out

**Comment by McJty** [comment]
Latest version should hopefully fix this

**Comment by Boolyman** [comment]
Thank you.  Ill check it out.
