### ISSUE TITLE
wrong wiki link 

### ISSUE THREAD

**Issue by PiTTl** [McJty/InControl#298]
hello, maybe i missed something, but
https://github.com/McJtyMods/InControl/wiki leads back to https://github.com/McJtyMods/InControl.
Please fix it, thank you,

**Comment by McJty** [comment]
Why would I need to fix that? That's not the wiki. I keep the wiki here:

https://wiki.mcjty.eu/mods/index.php?title=ControlMods

**Comment by PiTTl** [comment]
ah thanks for the hint. I thought the link "wiki" leads to the wiki and was confused : -O
