### ISSUE TITLE
Issue Restricting on Spawn Distance Basis

### ISSUE THREAD

**Issue by Katad0ra** [McJty/InControl#303]
Started doing ATM 6 with a group of friends, and we added Lycanites mobs because we enjoyed it in other packs, but I'm seemingly unable to restrict them from spawning.

I have this in my spawn.json, and I've tried variations with other things such as "hostile":true and "spawner":false, but nothing seems to be working. 
{
    "dimension": "minecraft:overworld",
    "minspawndist":450,
    "result": "deny"
  },
Is this an issue with my addition to the file or am I doing something else wrong?

Full code below for details.

[
  {
    "dimension": "minecraft:overworld",
    "minspawndist":450,
    "result": "deny"
  },
  {
    "dimension": "twilightforest:twilightforest",
    "mob": [
      "iceandfire:siren",
      "iceandfire:sea_serpent",
      "iceandfire:hippocampus"
    ],
    "mincount": {
      "amount": 10,
      "perplayer": true
    },
    "result": "deny"
  },
  {
    "dimension": "allthemodium:the_other",
    "mob": [
      "iceandfire:hydra",
      "iceandfire:ghost",
      "iceandfire:dread_scuttler",
      "iceandfire:dread_beast",
      "iceandfire:dread_horse",
      "iceandfire:dread_thrall",
      "iceandfire:dread_ghoul",
      "iceandfire:dread_knight"
    ],
    "mincount": {
      "amount": 10,
      "perplayer": true
    },
    "result": "deny"
  },
  {
    "dimension": "twilightforest:twilightforest",
    "mod": [
      "ars_nouveau",
      "mana-and-artifice"
    ],
    "result": "deny"
  },
  {
    "dimension": "minecraft:overworld",
    "mob": "iceandfire:myrmex_queen",
    "result": "deny",
    "onjoin": true
  },
  {
    "dimension": "allthemodium:mining",
    "mod": "ars_nouveau",
    "result": "deny"
  },
  {
    "dimension": "compactmachines:compact_world",
    "mod": "ars_nouveau",
    "result": "deny"
  },
  {
    "mob": [
      "mana-and-artifice:demon_imp",
      "mana-and-artifice:hulking_zombie",
      "mana-and-artifice:lantern_wraith",
      "mana-and-artifice:mushroom_soldier",
      "mana-and-artifice:pixie",
      "mana-and-artifice:skeleton_assassin",
      "mana-and-artifice:spellbreaker"
    ],
    "mincount": {
      "amount": 1,
      "perplayer": true
    },
    "result": "deny"
  },
  {
    "mob": [
      "mana-and-artifice:witch_hunter"
    ],
    "result": "deny"
  }
]

**Comment by McJty** [comment]
Sorry for late reply. Try adding "onjoin": true to the rules. I'm closing this because it's likely no longer relevant. If it still is let me know
