### ISSUE TITLE
Mob not spawning/spawning in non-specified biomes.

### ISSUE THREAD

**Issue by CodWafer** [McJty/InControl#306]
I am trying to make a specific mob spawn in a specified biome. 

_**Spawner.json**_
```
{
    "mob": "alexsmobs:soul_vulture",
    "persecond": 0.5,
    "attempts": 5,
    "amount": {
      "minimum": 2,
      "maximum": 3
    },
    "conditions": {
      "dimension": "minecraft:the_end",
      "inair": "true"
    }
  }
```
_**Spawn.json**_
```
  {
    "mob": "alexsmobs:soul_vulture",
    "mincount": "2",
    "maxcount": "3",
    "dimension": "1",
    "biome": "betterendforge:shadow_forest",
    "result": "allow"
  },
  {
    "mob": "alexsmobs:soul_vulture",
    "result": "deny"
  }
```

Ok, so. By having what I have, it never spawns. By removing the bottem segment of spawn.json 
```
  {
    "mob": "alexsmobs:soul_vulture",
    "result": "deny"
  }
```
It spawns everywhere. I am currently trying a few other things, but as of right now? Nothing seems to work.

**Comment by McJty** [comment]
Ok, there are a number of errors in this. First in 1.16 or higher you cannot use "dimension": 1 anymore. Numeric dimension id's don't exist. This is explained in the wiki.

Secondly, combining mincount/maxcount in one rule is not useful. That means the rule will ONLY allow mobs to spawn if there are at least 2 and maximum 3 mobs already. So if there are no mobs this rule will never be able to cause mobs to spawn

**Comment by CodWafer** [comment]
So, in theory, I could just... remove them? They can only spawn in the end already

```
  {
    "mob": "alexsmobs:soul_vulture",
    "biome": "betterendforge:shadow_forest",
    "result": "allow"
  },
  {
    "mob": "alexsmobs:soul_vulture",
    "result": "deny"
  }
```
I thought the mincount-maxcount was the same as the minimum and max of the spawner.json
As for dimensions, the spawner.json already has a condition for dimension...

So something like this would work? I am currently launching it myself to make sure.

**Comment by McJty** [comment]
Yes if you put [] around the two rules of course

**Comment by CodWafer** [comment]
yea, I got that.
Worked, ty
