### ISSUE TITLE
Still getting crash "incontrol.spawner.SpawnerSystem.getRandomPositionInBox"

### ISSUE THREAD

**Issue by Boolyman** [McJty/InControl#308]
Hey there,
I am (still) getting a crash due to single ticks taking 180 seconds. The crash report keeps referencing the incontrol.spawner.SpawnerSystem.getRandomPositionInBox

Forge - 36.2.23
incontrol-1.16-5.2.2

Here is the Crash Report:  https://paste.gg/p/anonymous/f16b70514fc94066b92ac5b82e7aab57

**Comment by McJty** [comment]
What is your spawner.json?

**Comment by Boolyman** [comment]
https://paste.gg/p/anonymous/eee66aa4ea2e44099f134aff4eaf2b07

**Comment by Boolyman** [comment]
Any advice on what I can change?

**Comment by McJty** [comment]
It's a bug. I: need to fix it in my mod. Not sure what's wrong though and I currently got no time to check it out. I'll hope to do so soon

**Comment by Boolyman** [comment]
I have switched over to use another mod for spawning creatures.  I would still like to use your mod to enforce a cap on the number of mobs spawning.  Can you at least tell me if this bug is likely to be encountered if I am only using your mod's spawn.json to prevent spawns?

**Comment by McJty** [comment]
No that shouldn't be possible. It's only for spawner. I'll go check this out again though. I want to fix this

**Comment by McJty** [comment]
I think I managed to reproduce it. I might get a fix after all

**Comment by McJty** [comment]
Will be fixed next release

**Comment by McJty** [comment]
The last version of InControl fixes this problem
