### ISSUE TITLE
Feature Request 1.18.1: 

### ISSUE THREAD

**Issue by Tyrius1** [McJty/InControl#310]
I posted the following in your discord and someone else suggested i make a feature requested here so here I am :)

I'm using incontrol to prevent certain mobs from spawning based on ylvl and i am also using enhanced celestials to create blood moons. Is there a way I could add like an exception to spawning if cause by a mod? sort of like you can do an exception with spawners.

,
  {
    "minheight": 60,
    "spawner": false,
    "mob": [
      "biomemakeover:decayed",
      "minecraft:zombie",
      "minecraft:husk",
      "minecraft:zombie_villager",
      "minecraft:skeleton",
      "minecraft:drowned",
      "minecraft:glow_squid"
    ],
    "result": "deny"
  }

**Comment by McJty** [comment]
That's not possible I'm afraid. I have no way of knowing what mod caused a certain mob to spawn
