### ISSUE TITLE
Is there an API ?

### ISSUE THREAD

**Issue by Natank25** [McJty/InControl#313]
Honestly, i don't know where to ask this question, so i am writing it here.

Did you made an API to allow other mod dev to use some options of in control ? If yes, how to use it in our mods ?

**Comment by McJty** [comment]
Why do you need an API? Can you describe your usecase?

**Comment by Natank25** [comment]
What I need to do is disable mob spawning in a dimension i made and not in vanilla dimensions

**Comment by McJty** [comment]
In Control can disable spawning in any dimension. Just specify the dimension in the rule like yourmod:dimensionid

**Comment by Natank25** [comment]
In the rule like ?

**Comment by McJty** [comment]
Oh. My message was cut off. Fixed

**Comment by Natank25** [comment]
And when i download In Control into the mod folder of /run in my ide, i can't start any worlds and Minecraft crashes. So, how should i do to use In Control while creating my mod ?

**Comment by McJty** [comment]
Why do you need it during dev? Anyway. You can include In Control through a proper maven dependency in your build.gradle (using the curse maven). See how I do this for The One Probe: https://github.com/McJty/TutorialV3/blob/main/build.gradle#L139

**Comment by Natank25** [comment]
Ok, thank you for your help, but how do I get this `curse.maven:the-one-probe-245211:3550084` but for In Control ?

**Comment by McJty** [comment]
Go to the incontrol curseforge page. The first number is the id of the project. The second number the id of the file you want (the specific version you want to use)

**Comment by Natank25** [comment]
Ok, i understand now, thank you for your help, and have a great day !
