### ISSUE TITLE
onjoin in spawn.json not being applied correctly in the latest 1.18.1 update

### ISSUE THREAD

**Issue by Raidobw2** [McJty/InControl#315]
The "onjoin" keyword appears to be broken in the latest 1.18.1 update. The chat mentions it being invalid on a reload, and mob modifications no longer work (e.g. zombie with more HP works before the update, but not after)
![image](https://user-images.githubusercontent.com/17010632/158648668-74826111-86d9-46c7-bdda-57133dc959ea.png)

Versions:
Minecraft `1.18.1`
Forge `39.1.2`
InControl `incontrol-1.18-6.0.3.jar`

**Comment by McJty** [comment]
oh oops. I'll fix

**Comment by McJty** [comment]
Fixed

**Comment by Raidobw2** [comment]
It's working again with the bugfix, thank you and have a good day!
