### ISSUE TITLE
So many mob spawning 

### ISSUE THREAD

**Issue by ghost** [McJty/InControl#317]
Just wanted spawn SCP-173 in earth but after I put 
        "mob": "scp:killer_statue",
        "weight": 1,
        "groupcountmin": 1,
        "groupcountmax": 1
into potentialspawn and create new world, so many SCP-173 spawns around. 
      "  "weight": 1 " is uses integer number so I cannot use like this: "weight": 0.01,.
What command can I use? I want to spawn it with very low chance.
NOTE: I used " "mincount": 1, " command in spawn.json but after one spawn, mod not spawning another SCP-173 until I kill first one. I don't want this :(

**Comment by McJty** [comment]
Show me  your full rule files. Properly formatted
