### ISSUE TITLE
Potentialspawn Is Creating Hundreds of Mobs with no Cap

### ISSUE THREAD

**Issue by Boolyman** [McJty/InControl#32]
Someone else posted a similar topic regarding passive mobs, but I am unsure if the mob spawning rule is different, or if changes have been made since that issue.  When I add some mobs, like Blazes or Ghasts to spawn in the overworld, they spawn nonstop until hundreds of them are filling your screen.  See the attached screenshot.

![image](https://user-images.githubusercontent.com/24765883/30144833-8d99b014-9342-11e7-8300-aa45c9dec286.png)

It also completely ignores the other two mobs in the syntax... in my case it isn't spawning any Ender Dragon Zombies or Ghast mobs... just tons and tons of Blaze... despite the weight for both of these mobs being higher than Blaze.  

This is my potentialspawn file:

[
  {
    "dimension": 0,
    "mobs": [
      {
        "mob": "Blaze",
        "weight": 5,
        "groupcountmin": 1,
        "groupcountmax": 2
      },
            {
        "mob": "armorplus.ender_dragon_zombie",
        "weight": 15,
        "groupcountmin": 1,
        "groupcountmax": 2
      },
            {
        "mob": "Ghast",
        "weight": 25,
        "groupcountmin": 1,
        "groupcountmax": 2
      }
    ]
  }
]

**Comment by McJty** [comment]
Well without additional restrictions in spawn.json there is nothing preventing the blazes from keeping spawning. So you will want to add some restrictions to that.

Also is "armorplus.ender_dragon_zombie" the right name? Shouldn't that be a : instead of a .?

**Comment by Boolyman** [comment]
Got it working, thanks!

**Comment by MokahTGS** [comment]
How did you get this to work?  What are the restrictions that you added?
