### ISSUE TITLE
[1.16.5] Bees rapidly leaving/entering beehives when denying spawning with "onjoin":  true

### ISSUE THREAD

**Issue by Kadinumoto** [McJty/InControl#320]
I'm not the greatest at making working configs but following the tutorials and documentation I was under the impression that this is the way to deal with bees because they don't follow normal spawning rules. If this is my doing and not a bug then I'll gladly hear the solution! 

Added my spawn.json file just in case

[spawn.json.txt](https://github.com/McJtyMods/InControl/files/8599164/spawn.json.txt)

**Comment by McJty** [comment]
This is not a bug. Just a consequence of how this works. When a beehive is ready to spawn it will spawn until it succeeds. So canceling the spawn it will have weird effects. Nothing I can do about

**Comment by Kadinumoto** [comment]
> This is not a bug. Just a consequence of how this works. When a beehive is ready to spawn it will spawn until it succeeds. So canceling the spawn it will have weird effects. Nothing I can do about

Sorry if this is not the place to ask but what's the best way to deal with them then?

**Comment by McJty** [comment]
I have absolutely no idea. Mostly because I don't exactly know what you mean by 'deal with them'. What's your goal?

**Comment by Kadinumoto** [comment]
Removing all mobs unless from spawners and structures but my guess is that I'll have to disable the generation of beehives, correct?

**Comment by McJty** [comment]
yes, that might be the best solution here
