### ISSUE TITLE
Using the "PersistenceRequired" nbt field in spawn.json will cause the game to spawn thousands of mobs instantly

### ISSUE THREAD

**Issue by XM666-Dev** [McJty/InControl#324]
[
  {
    "hostile": true,
    "nbt": {
      "PersistenceRequired": true
    }
  }
]
Enter the above in spawn.json and see what happens
My English is not good so this is machine translation
(1.18.2)

**Comment by McJty** [comment]
Well that's not something I control. Apparently vanilla does something weird with that flag. Not a bug in In Control
