### ISSUE TITLE
(1.12.2) Health Multiply Rule doesn’t work correctly on mobs

### ISSUE THREAD

**Issue by NicksCraft2007** [McJty/InControl#326]
Everything in bold is what isn’t working properly. This is all written under spawn.json.

[ 
    {
    "mob": ["divinerpg:rainbour"],
    "result": "deny"
    },
    {
        "onjoin": true,
        "mob": "ageofabyssalcraft:jzaharhelpful",
        "result": "allow",
        "healthmultiply": 1,
        "damagemultiply": 1
    },
    {
        "onjoin": true,
        "mob": "ageofminecraft:enderdragonhelpful",
        "result": "allow",
        "healthmultiply": 1,
        "damagemultiply": 1
    },
    {
        "onjoin": true,
        "mob": "ageofminecraft:witherbosshelpful",
        "result": "allow",
        "healthmultiply": 1,
        "damagemultiply": 1
    },
    {
        "onjoin": true,
        "mob": "ageofminecraft:abomniablesnowmanhelpful",
        "result": "allow",
        "healthmultiply": 1,
        "damagemultiply": 1
    },
    **{
        "onjoin": true,
        "maxspawndist": 80,
        "result": "allow",
        "healthmultiply": 2,
        "damagemultiply": 1
    }**,
    {
        "onjoin": true,
        "minspawndist": 80,
        "result": "deny"
    }
]

Some mobs have their health multiplied by 4 when I make _“healthmultiply”: 2,_ in _{
        "onjoin": true,
        "maxspawndist": 80,
        "result": "allow",
        "healthmultiply": 2,
        "damagemultiply": 1
    }_

**Comment by McJty** [comment]
Isn't that normal? I don't understand the problem exactly?

**Comment by NicksCraft2007** [comment]
It seems to only happen to mobs 40+ blocks from the world spawn. Also, is there a way to make mobs spawn on bedrock using InControl?

**Comment by McJty** [comment]
What is 'it'. Can you please describe the problem better? What is happening and what shouldn't happen?

**Comment by NicksCraft2007** [comment]
I intended the rule shown above to double every mob's health. However, when mobs spawn, their health is usually multiplied randomly. For example, some mobs that spawn 40 blocks from the world spawn have triple or even 4x health. It's not extremely important, but I want them to take a little longer to be killed by J'zahar from AbyssalCraft. He kills most of them almost instantly. I want it to be a challenge, especially since he has such a strong damage resistance.
I've seen zombies that spawn naturally with 80 health points instead of 40 health points, which is what it should be.

**Comment by McJty** [comment]
Hmm not sure why that is happening to be honest

**Comment by NicksCraft2007** [comment]
It's ok, it's not a big problem.

**Comment by NicksCraft2007** [comment]
Also, is there a way to override spawning rules and make all mobs spawn on bedrock blocks? For a super flat world that is bedrock only.

**Comment by McJty** [comment]
Hmm not sure. I don't see why not? Haven't tried it myself though

**Comment by NicksCraft2007** [comment]
I tried this in spawn.json:

[

    {
        "block": "minecraft:bedrock",
        "result": "allow"
    }
]

**Comment by NicksCraft2007** [comment]
It doesn't do anything.
