### ISSUE TITLE
1.18.2 Server Crash - TNP Limitless 5 v2.4.0 - No World Found

### ISSUE THREAD

**Issue by Hachuurui** [McJty/InControl#327]
Server crashes when a player logs in citing no world found. 

OS: Linux
ServerOS: Cubecoder's AMP v2.3.2.12
Pack: TNP Limitless 5 v2.4.0
Forge: 40.1.0

Crash Report:
https://pste.me/v1/paste/hIwJ5_pZhKI/raw

spawn.json
https://pste.me/v1/paste/nLifmlgxbYM/raw

All other json files are empty json arrays []

Disabling incontrol and the server works fine. Not sure why it started doing this, but it was working fine till today. If you would like a copy of the world to help research this, let me know.

**Comment by Hachuurui** [comment]
I took a moment to look at the source for this section of code to see how the method works. I'm wondering if this might be a conflict between incontrol and All the biomes you'll go. The player was in a vanilla plains biome, but had an ABYG biome next to them and there is a dungeon near them. There is a pack update available as well. I'll update the server tonight and test this again to see if it persists post update.

**Comment by Hachuurui** [comment]
So this is still occurring. It seems related to Apotheosis spawners and all the biomes you'll go but not sure why. Again, if you need a copy of the world to trace this let me know.

**Comment by McJty** [comment]
Did you report this to BYG? I have checked the code and I don't see what I'm doing wrong or how I could do things differently. I suspect BYG is doing something wrong/unexpected

**Comment by Hachuurui** [comment]
> Did you report this to BYG? I have checked the code and I don't see what I'm doing wrong or how I could do things differently. I suspect BYG is doing something wrong/unexpected

I apologize on the delay on replying. Dealing with a ton of issues today involving this pack. 

I have not posted to them yet, but after looking at your source, I was coming to the same conclusion. Do you mind if I link to this issue as I post on theirs as well?

**Comment by McJty** [comment]
Feel free to link

**Comment by rmnaderdev** [comment]
@Hachuurui Did you ever make an issue in BYG?

**Comment by Hachuurui** [comment]
No @PotatoDotJar  I got wrapped up in basically everything else. We also need to make an issue for the array out of bounds conflict with Fastcraft and this mod as well. I apologize, I kinda dropped the ball on this one.

**Comment by Hachuurui** [comment]
Closing since this went stale and I haven't had a moment to follow up.
