### ISSUE TITLE
1.18.2 Worlds are Deadlocked

### ISSUE THREAD

**Issue by Cynadyde** [McJty/InControl#328]
I was putting together a forge modpack for 1.18.2 when I noticed each world would deadlock (does not crash; no logs are given; server simply stops ticking) when certain chunks get loaded.
I spent the past few hours narrowing down what was causing it.
Here are the versions being used:
```
Minecraft 1.18.2
forge-40.1.20
incontrol-1.18-6.0.8
```
In case it is helpful, here is a CurseForge modpack export that has incontrol as a single mod, the config i set for it, and one of the world saves that will deadlock:
[Test Modpack-1.0.zip](https://github.com/McJtyMods/InControl/files/8776496/Test.Modpack-1.0.zip)

Here is the `spawm.json` I'm using:
```json
[
  {
    "incontrol": true,
    "result": "default"
  },
  {
    "spawner": true,
    "result": "default"
  },
  {
    "onjoin": true,
    "dimension": "minecraft:overworld",
    "mob": "minecraft:phantom",
    "maxheight": 192,
    "result": "deny"
  },
  {
    "onjoin": true,
    "dimension": "minecraft:overworld",
    "mob": "minecraft:drowned",
    "structure": "minecraft:ocean_ruin",
    "result": "default"
  },
  {
    "onjoin": true,
    "dimension": "minecraft:overworld",
    "mob": "minecraft:drowned",
    "result": "deny"
  },
  {
    "onjoin": true,
    "dimension": "minecraft:overworld",
    "mob": [
      "minecraft:skeleton",
      "minecraft:zombie"
    ],
    "structure": "minecraft:mineshaft",
    "result": "default"
  },
  {
    "onjoin": true,
    "dimension": "minecraft:overworld",
    "mob": [
      "minecraft:skeleton",
      "minecraft:zombie"
    ],
    "result": "deny"
  },
  {
    "onjoin": true,
    "dimension": "minecraft:overworld",
    "mob": "minecraft:spider",
    "minlight": 1,
    "result": "deny"
  },
  {
    "onjoin": true,
    "dimension": "minecraft:overworld",
    "mob": "minecraft:witch",
    "seesky": false,
    "result": "deny"
  },
  {
    "onjoin": true,
    "dimension": "minecraft:overworld",
    "mob": "minecraft:enderman",
    "minheight": -32,
    "result": "deny"
  }
]
```

**Comment by McJty** [comment]
I need a server and/or crashlog

**Comment by Cynadyde** [comment]
Loading backup of the world with only InControl installed.
I try to type in chat but the world is immediately frozen and the game has to be terminated.
[latest.log](https://github.com/McJtyMods/InControl/files/8776587/latest.log)

Loading the same world with InControl removed.
The world runs
[latest.log](https://github.com/McJtyMods/InControl/files/8776603/latest.log)

Loading backup of the world with no mods installed.
The world still runs
[latest.log](https://github.com/McJtyMods/InControl/files/8776639/latest.log)

**Comment by McJty** [comment]
Would it be possible for you to figure out what rule in spawn.json is causing it? i.e. try by removing half the rules and see if it works or not. And so on until you pinpoint it. Thanks

**Comment by Cynadyde** [comment]
yes I can do that. I will post when I am able to.

**Comment by McJty** [comment]
Never mind. I found out what's causing it. Preparing a fix

**Comment by McJty** [comment]
Fixed
