### ISSUE TITLE
[1.18.2] Serene Seasons Compatablity?

### ISSUE THREAD

**Issue by TheGoldenAxe001** [McJty/InControl#329]
I'm looking to make phases for the day and night of the seasons in Serene Seasons. The wiki says it's incompatible for 1.16 but nothing about 1.18. I'm unsure if it's incompatible or if I'm doing this wrong. Here are my summer day/night phases as examples:

{
      "name": "summerday",
      "conditions": {
        "mintime": 0,
        "maxtime": 11999,
        "summer": true
      }
    },
    {
      "name": "summernight",
      "conditions": {
        "mintime": 12000,
        "maxtime": 23999,
        "summer": true
      }
    }

**Comment by McJty** [comment]
This was fixed a while ago
