### ISSUE TITLE
Having trouble with files

### ISSUE THREAD

**Issue by illraccoon** [McJty/InControl#330]
I was trying to figure out how to use the mod, but my programming skills are very low, could someone help me with changing the spawn.json?
I just want to know how to write a setting that stops the following mobs to spawn;

Evoker
Vindicator
Pillager
Ravager
Ravager Jockey
Vex
Chicken Jockey
Endermite
Guardian
Elder Guardian
Shulker
Phantom
Blaze
Creeper
Ghast
Silverfish
Slime
Drowned
Wither Skeleton
Hoglin
Zoglin
Piglin Brute

**Comment by McJty** [comment]
Did you check the wiki? There are examples there
