### ISSUE TITLE
Fast zombies at night, slow zombies at day

### ISSUE THREAD

**Issue by Zalazim** [McJty/InControl#331]
Hello !

I am trying to **spawn zombies** and skeletons **night only**, **and with more speed** (like 1.5 but here it's 3 for test reasons).
So I want them to get their **normal speed back at daytime**, but is does not work.

I **tried to spawn zombies at daytime** and they indeed **have a normal speed**, but **nightime spawned zombies still have a high speed**.

**How can I give them back their normal speed ?**
And if it isn't possible with this mod, how could I do it ?

Here is spawn.json :
`[
  {
    "mob": ["minecraft:skeleton","minecraft:zombie"],
    "phase": "nighttime_after_day1",
    "result": "allow",
    "speedmultiply": 3
  },
  {
    "mob": ["minecraft:skeleton","minecraft:zombie"],
    "phase": "daytime",
    "result": "deny",
    "speedmultiply": 1
  },
  {
    "mob": ["minecraft:skeleton","minecraft:zombie"],
    "incontrol": false,
    "result": "deny"
  }
]`
Here is phases.json :
`[
  {
    "name": "nighttime_after_day1",
    "conditions": {
      "mindaycount": 1,
      "mintime": 12500,
      "maxtime": 23500
    }
  },
  {
    "name": "daytime",
    "conditions": {
      "mintime": 23501,
      "maxtime": 12499
    }
  }
]`

Thank you in advance !

**Comment by McJty** [comment]
In Control can only influence mob spawns. It can't change stats of mobs that are already spawned
