### ISSUE TITLE
Reallowing Spawns

### ISSUE THREAD

**Issue by Radlongstaff** [McJty/InControl#332]
Hi, I am having trouble figuring out the system and was looking for help in regards to denying and allowing mobs.

this is on version 1.16.5

the context is that I am looking to disable mobs from a mod, in this case Lycanitesmobs,  until a certain phase is reached

within my spawn.json file this is what I have so far 

[
        {
            "dimension": "minecraft:overworld",
            "mod": "lycanitesmobs",
            "result": "deny"
        }
]

and this certainly works, but, I thought that doing this afterwards in spawn.json would work
[

    {
        "phase": "after_day5",
        "dimension": "minecraft:overworld",
        "mod": "lycanitesmobs",
        "result": "allow"
    }
]

however, Lycanitesmobs do not start spawning normally after the 5th day. Is there something i'm missing? Any help would be appreciated, thank you.

**Comment by McJty** [comment]
Rules are evaluated in order. From top to bottom. As soon as it reaches that 'deny' rule it will not try further rules as it already found a rule that works. You need to put the allow rule first
