### ISSUE TITLE
1.19 Biome Blacklist Crash

### ISSUE THREAD

**Issue by Tyrius1** [McJty/InControl#333]
MC 1.19
Forge 41.0.38
incontrol-1.19-7.0.0.jar

Got a crash when attempting to prevent squids from spawning in rivers:
https://pastebin.com/MVEUtJU2

The above crash report happened with the following config:
[
    {
        "mob": "minecraft:squid",
        "biome": "minecraft:river",
        "result": false
    }
]

Attempted to use the string format out of curiosity sake and also got a crash:
https://pastebin.com/yBdujjYB
The above crash report happened with the following config:
[
    {
        "biome": [
            "minecraft:river"
        ],
        "mob": [
            "minecraft:squid"
        ],
        "result": "deny"
    }
]

**Comment by McJty** [comment]
Fixed in 7.0.1
