### ISSUE TITLE
[1.18.2] Pigs stop spawning naturally when preventing any other mob from spawning.

### ISSUE THREAD

**Issue by Gbergz** [McJty/InControl#338]
Title^

Somehow pigs stop spawning naturally when the script below is used. Don't know why, it's weird.
Correct the script if it's wrong. Pigs are not listed to be stopped from spawning.

Script - spawn.json : https://gist.github.com/Gbergz/3b2f1a2b71bef73219f88610449803c3

MC: 1.18.2
Forge: 40.1.60
In-Control: 6.0.12

**-** Gbergz

**Comment by McJty** [comment]
That means one of those mob id's is invalid and then it will default to pigs

**Comment by Gbergz** [comment]
Ahhh, makes sense. 
Thanks for the swift reply!
