### ISSUE TITLE
[1.16.5] Blockoffset example?

### ISSUE THREAD

**Issue by Terra-B-Welch** [McJty/InControl#342]
Any chance of sharing a blockoffset example for mob spawns? Like having it so mobs won't spawn withing say... 32 blocks of a specific block? If that's possible?

**Comment by McJty** [comment]
That's not possible. Checking if a block exists in 32 radius is a HUGE number of blocks to test. That would slow down Minecraft to a crawl

**Comment by Terra-B-Welch** [comment]
Even if it was a single manmade block?

Also I find it hilarious that it took like... half a year to get a response.

**Comment by McJty** [comment]
Well only if the mod that provided the manmade block had some system to communicate where it is. But that requires another mod

**Comment by BigMartin58** [comment]
[1.19] 

Could you still give a generic example of how "blockoffset" is used? I kinda know json but there are no examples in the documentation and I'm basically just guessing as to how it's structured or what terms might be used.

"blockoffset": {
          "x": 0,
          "y": -5,
          "z": 0
}



Edit: I seem to only be able to get it to work when I use "offset" within "blockoffset" like this:

{
    "blockoffset": {
		"offset": {
			"x": 0,
			"y": 0,
			"z": 0
			}
		}
}

I noticed in the changelog of version 7.0.15 that you could directly add the "x", "y", and "z" tags without "offset".

**Comment by Terra-B-Welch** [comment]
Why did you gravedig this issue instead of just making a new one?

**Comment by BigMartin58** [comment]
> Why did you gravedig this issue instead of just making a new one?

Because I also wanted an example and he never gave one?

**Comment by Terra-B-Welch** [comment]
then make a new issue, this one is closed, the guy will likely never read it unless you make a new one...
