### ISSUE TITLE
[1.16.5] nbt tag unbreakable ?

### ISSUE THREAD

**Issue by doublefcd** [McJty/InControl#343]
do you known how to write nbt tag unbreakable ?, i try a lot of time and still error

{
    "mob": "minecraft:drowned",
    "player": true,
    "item": "minecraft:trident",
    "nbt": {
      "Unbreakable": ["1b"]},
    }

**Comment by McJty** [comment]
Well you have a } too many after ["1b"]

**Comment by McJty** [comment]
Always be specific. You say you got an error. It is useful for me to know what error you got

**Comment by doublefcd** [comment]
I follow this example zombies will drop an enchanted diamond sword to write another nbt, but i don't know how to write true a nbt tags, i put your example in my loot.json, it's not have error but a diamond sword drop from zombie not have enchant

  {
    "mob": "minecraft:zombie",
    "player": true,
    "item": "minecraft:diamond_sword",
    "nbt": {
      "ench": [
        {
          "lvl": 3,
          "id": 22
        }
      ]
    }
  }
  
i try a lot of time to write nbt tags unbreakable but still error, i can't see the tutorital write nbt tag in your wiki or i blink
  
  {
"mob": "minecraft:drowned",
"player": true,
"item": "minecraft:trident",
"nbt": {
"Unbreakable": ["1b"]},
}

  the error i got is
  
 JSON error in 'loot.json': check log for details (com.google.gson.stream.MalformedJonException: Expected name at line 7 column 2 path $[0].nbt)
  
  another question, u write nbt tag with example zombies will drop an enchanted diamond sword
"id" = 22 , 22 from what, if that is enchanted iron sword, the number i put in id = ? , or other item ?
