### ISSUE TITLE
minecraft 1.18.2 hostiles spawn control

### ISSUE THREAD

**Issue by alessandriLuca** [McJty/InControl#344]
Hi, this is my spawn.json and since i have some mobs from the nether spawning in the overworld I would like to block them in the light but apparently this wont work. Can you help me? Thanks . Also i was trying to make another rule in order to kill all the hostile creatures once every day at mid day, but I'm kind of confused about the commands. Thanks 
[
{
	"hostile":true
	"dimension": 0,
	"minlight": 4,
	"seesky": true,
	"result": "deny"
}
]

**Comment by McJty** [comment]
0 is not a valid dimension. You are using syntax from the 1.12 version. Check the correct wiki for you version

**Comment by alessandriLuca** [comment]
Hi, thank you  for your answer and sorry for the mistake. By the way even tough i changed the config and checked that the syntax belong to the 1.18.2 this code wont stop the mob spawning under the light 

[
  {
    "maxlight": 4,
    "hostile": true,
    "result": "deny"
  }
]

**Comment by McJty** [comment]
You need minlight. Not maxlight

**Comment by alessandriLuca** [comment]
i tried wit both maxlight and minlight 
[
{
"maxlight": 4,
"hostile": true,
"result": "deny"
}
]




[
{
"minlight": 4,
"hostile": true,
"result": "deny"
}
]

but none is working

**Comment by alessandriLuca** [comment]
I tried in several ways but the behaviour is weird, I cannot find a combination in which the hostiles spawn only in the dark. I even tried with "passive":"false"

**Comment by McJty** [comment]
Can you give an example of a mob that spawns wrong?

**Comment by alessandriLuca** [comment]
Ok here a better recap with all the try, so we can understand where is the problem. I think there is a problem in the tagging in the doomMC mod so, i will use instead of the tag hostile or passive, just the mob name. I modified the config of the doomMC mod in order to let the creature spawn not only in the nether but also in the overworld. Since they are creature of the nether they are not affected by light for the spawning, that's why i tought of using inControl mod  in order to make them spawn in the dark and not in the light. Taking a sample creature here is all the try and what they led to : 
 { "mob":"doom:arachnotron","maxlight"=15 ,"result": "deny" }--> it doesnt spawn neither in the light nor in the dark 
 { "mob":"doom:arachnotron","maxlight"=0 ,"result": "deny" } --> spawn in light and night but looks like that happen only close to light source
 { "mob":"doom:arachnotron","minlight"=0 ,"result": "deny" }--> it doesnt spawn neither in the light nor in the dark
 { "mob":"doom:arachnotron","minlight"=15 ,"result": "deny" } --> spawn in light and night 
 { "mob":"doom:arachnotron","minlight"=7 ,"result": "deny" } --> spawn in light and night 
 { "mob":"doom:arachnotron","maxlight"=7 ,"result": "deny" } --> spawn in light and night 

Thanks! I'm available for other testing also ! 

Here is the full json file, just imagine that i put the same previous velues to all of the mobs in every test 

Luca 

[
 { "mob":"doom:arachnotron","maxlight"=7 ,"result": "deny" },
 { "mob":"doom:arachnotroneternal","maxlight"=7 ,"result": "deny" },
 { "mob":"doom:arch_maykr","maxlight"=7 ,"result": "deny" },
 { "mob":"doom:archvile","maxlight"=7 ,"result": "deny" },
 { "mob":"doom:armoredbaron","maxlight"=7 ,"result": "deny" },
 { "mob":"doom:baron","maxlight"=7 ,"result": "deny" },
 { "mob":"doom:baron2016","maxlight"=7 ,"result": "deny" },
 { "mob":"doom:blood_maykr","maxlight"=7 ,"result": "deny" },
 { "mob":"doom:cacodemon","maxlight"=7 ,"result": "deny" },
 { "mob":"doom:chaingunner","maxlight"=7 ,"result": "deny" },
 { "mob":"doom:cueball","maxlight"=7 ,"result": "deny" },
 { "mob":"doom:cyberdemon","maxlight"=7 ,"result": "deny" },
 { "mob":"doom:doom_hunter","maxlight"=7 ,"result": "deny" },
 { "mob":"doom:dreadknight","maxlight"=7 ,"result": "deny" },
 { "mob":"doom:firebronebaron","maxlight"=7 ,"result": "deny" },
 { "mob":"doom:gargoyle","maxlight"=7 ,"result": "deny" },
 { "mob":"doom:gladiator","maxlight"=7 ,"result": "deny" },
 { "mob":"doom:gore_nest","maxlight"=7 ,"result": "deny" },
 { "mob":"doom:hellknight","maxlight"=7 ,"result": "deny" },
 { "mob":"doom:hellknight2016","maxlight"=7 ,"result": "deny" },
 { "mob":"doom:iconofsin","maxlight"=7 ,"result": "deny" },
 { "mob":"doom:imp","maxlight"=7 ,"result": "deny" },
 { "mob":"doom:mancubus","maxlight"=7 ,"result": "deny" },
 { "mob":"doom:marauder","maxlight"=7 ,"result": "deny" },
 { "mob":"doom:maykr_drone","maxlight"=7 ,"result": "deny" },
 { "mob":"doom:mechazombie","maxlight"=7 ,"result": "deny" },
 { "mob":"doom:motherdemon","maxlight"=7 ,"result": "deny" },
 { "mob":"doom:painelemental","maxlight"=7 ,"result": "deny" },
 { "mob":"doom:pinky","maxlight"=7 ,"result": "deny" },
 { "mob":"doom:possessed_scientist","maxlight"=7 ,"result": "deny" },
 { "mob":"doom:possessed_soldier","maxlight"=7 ,"result": "deny" },
 { "mob":"doom:possessed_worker","maxlight"=7 ,"result": "deny" },
 { "mob":"doom:prowler","maxlight"=7 ,"result": "deny" },
 { "mob":"doom:revenant","maxlight"=7 ,"result": "deny" },
 { "mob":"doom:revenant2016","maxlight"=7 ,"result": "deny" },
 { "mob":"doom:shotgunguy","maxlight"=7 ,"result": "deny" },
 { "mob":"doom:spectre","maxlight"=7 ,"result": "deny" },
 { "mob":"doom:spidermastermind","maxlight"=7 ,"result": "deny" },
 { "mob":"doom:spidermastermind2016","maxlight"=7 ,"result": "deny" },
 { "mob":"doom:stone_imp","maxlight"=7 ,"result": "deny" },
 { "mob":"doom:summoner","maxlight"=7 ,"result": "deny" },
 { "mob":"doom:tentacle","maxlight"=7 ,"result": "deny" },
 { "mob":"doom:turret","maxlight"=7 ,"result": "deny" },
 { "mob":"doom:unwilling","maxlight"=7 ,"result": "deny" },
 { "mob":"doom:whiplash","maxlight"=7 ,"result": "deny" },
 { "mob":"doom:zombieman", "maxlight"=7 ,"result": "deny" }
]

**Comment by McJty** [comment]
Ah they are not vanilla mobs. Then it's possible you have to add "onjoin": true

Also I see you are still using maxlight. Don't do that. It must be minlight

**Comment by alessandriLuca** [comment]
Hi, thank you for the reply 
So i tried in the following ways 
 {"onjoin": "true","mob":"doom:arachnotron","minlight"=0 ,"result": "deny" } -> dont spawn neither in the day nor in the night
 {"onjoin": "true","mob":"doom:arachnotron","minlight"=1 ,"result": "deny" } -> spawn during the day and during the night
 {"onjoin": "true","mob":"doom:arachnotron","minlight"=15 ,"result": "deny" } -> spawn during the day and during the night
 {"onjoin": "true","mob":"doom:arachnotron","minlight"=14 ,"result": "deny" } -> spawn during the day and during the night

**Comment by alessandriLuca** [comment]
Hi, so I managed to control this spawn in another way, simply using the day time and the incity parameter in order to not let them spawn during the day and in the night they spawn only outside the cities. Now i have another problem. I have a lot of pigs spawning. Do you think is possible that in some way minecraft try to spawn the "doom" entities but your mod prevent them from spawning so minecraft "have" to spawn something and simply make pigs spawn like crazy?  Do you have any suggestion?

**Comment by alessandriLuca** [comment]
So I have done some debugging and I can confirm what I said in the previous post, preventing them to spawn force minecraft to spawn something else, and for some reason it choose pigs. 
I tried to play with the onjoin paramether setting it to true, false and also removing it totally but I have the same result. 
Attached you can find the json (i had to call it txt otherwise github didnt let me upload the file)
[spawn - Copy.json.txt](https://github.com/McJtyMods/InControl/files/9457784/spawn.-.Copy.json.txt)

**Comment by McJty** [comment]
Looks like a problem in the doomMC mod to be honest. Never heared someone report this with InControl and I also don't see how InControl could do this

**Comment by alessandriLuca** [comment]
ok thanks , I will report it to the doomMC mod author , meanwhile I solved with the combination of spawn and spawner. your mod is really super cool XD I will put here both the json and then I will close the issue , thanks again !

**Comment by alessandriLuca** [comment]
Here the two files that let me solve the problem! 
Thanks again! 
[incontrolConfig.zip](https://github.com/McJtyMods/InControl/files/9463180/incontrolConfig.zip)
