### ISSUE TITLE
Unable to cancel custom spawns using other mods

### ISSUE THREAD

**Issue by PssbleTrngle** [McJty/InControl#345]
Hi, I made the mod [Brazier](https://github.com/PssbleTrngle/Brazier), which adds a structure to prevent mob spawns in a certain radius.
It does so by using the `LivingSpawnEvent.CheckSpawn` event & denying it.

This does not work for custom in-control spawners. The event does get called for these mobs, but even setting it to `DENY` on  the lowest as well as the highest event priority does not cancel them.

Maybe the event has to be called manually [here](https://github.com/McJtyMods/InControl/blob/235498f73827e0fcc256b0546f43ddbdd599e24f/src/main/java/mcjty/incontrol/spawner/SpawnerSystem.java#L217), but I would also guess that's what `checkSpawnRules` already does, so I'm a bit lost

**Comment by McJty** [comment]
Well this is a bit intentional. In Control is supposed to be the master for controlling spawns. If someone wants to specifically allow spawns inside your structure using In Control then that should be possible. After all, that's what my mod is about
