### ISSUE TITLE
Spawn.json doesn't recognize zombies?

### ISSUE THREAD

**Issue by kaidenart** [McJty/InControl#347]
I keep on getting the error

JSON error in 'spawn.json': check log for details (Non [a-z0-9/._-] character in path location: minecraft:Zombie)

I tested your example slow but strong zombie code to make sure im not going insane and i still got this error.

**Comment by McJty** [comment]
It's minecraft:zombie. Not minecraft:Zombie

**Comment by kaidenart** [comment]
But I copied your sample code?

**Comment by McJty** [comment]
From where did you copy that? I think you copied from the 1.12 wiki. You need to check the correct wiki
