### ISSUE TITLE
[1.18.2] Random Crash

### ISSUE THREAD

**Issue by Reshy** [McJty/InControl#348]
https://pastebin.com/hGY7cN4C

Got a crash while moving around the world from In Control according to the logs.

**Comment by McJty** [comment]
I need to see your rules

**Comment by Reshy** [comment]
They're very minimal at this point.

[
  {
    "mob": "minecraft:bat",
    "result": "deny"
  },
  {
    "mob": "alexsmobs:moose",
    "mincount": 8,
    "result": "deny"
  },
  {
    "mob": "cnb:sporeling",
    "mincount": 8,
    "result": "deny"
  },
  {
    "mob": "cnb:sporeling",
    "mincount": 8,
    "result": "deny"
  },
  {
    "mob": "terraincognita:butterfly",
    "mincount": 8,
    "result": "deny"
  },
  {
    "mob": "alexsmobs:fly",
    "mincount": 8,
    "result": "deny"
  },
  {
    "mob": "earthmobsmod:jumbo_rabbit",
    "mincount": 8,
    "result": "deny"
  },
  {
    "mob": "alexsmobs:gelada_monkey",
    "mincount": 8,
    "result": "deny"
  },
  {
    "mob": "alexsmobs:raccoon",
    "mincount": 8,
    "result": "deny"
  },
  {
    "mob": "biomemakeover:blightbat",
    "result": "deny"
  },
  {
    "mob": "earthmobsmod:hyper_rabbit",
    "mincount": 8,
    "result": "deny"
  }
]

**Comment by McJty** [comment]
I expect this to be fixed by now. If not please let me know
