### ISSUE TITLE
[1.18.2] Is it possible to reverse game stage checks?

### ISSUE THREAD

**Issue by Saereth** [McJty/InControl#349]
It is often more useful to check if a player doesn't have a stage and dissallow the spawn than to forcibly allow the spawn when they do have a stage. For example

```
[
  {
    "mob": ["SomeReallyHardMob", "SuperSkeleton"],
    "gamestage": "reallyhardmobs"
    "result": "deny"
  }
]
```

Except, I'd need to invert the game stage check to only deny the hard mob if they don't have the hard stage. I can't seem to find any way to currently invert the check in inControl.

I could forcibly allow the mob if they have the stage instead, but this badly interferes with other mods that prevent spawning or alter spawn rules such as magnum torch etc. so I tend to avoid explicit allows. In general, though, an inverse or NOT check for most of the conditionals could be useful as well.

**Comment by McJty** [comment]
Sorry for late reply
Reversing a check is not possible. However it's also not needed. You can do two rules. One with the gamestage and allow and then another without gamestage and deny. That's how you reverse tests in In Control
