### ISSUE TITLE
[1.19.2] Really bad worldgen lag with non-empty `spawn.json`

### ISSUE THREAD

**Issue by saltyseadoggo** [McJty/InControl#351]
When I enter any world in 1.19.2 with In Control 7.0.8 loaded and anything in `spawn.json`, worldgen is slowed down to a crawl. You can easily move to the edge of the loaded area in creative mode and beyond it as chunks generate very, very slowly. The game shows signs of lag, such as hitting a mob and it taking a bit for the game to register the hit and make it flash red.
In addition, creating a new world is also very slow, as the square loading icon that gets bigger as the percent goes up seems to freeze over and over at regular intervals, and the percentage with it.
These factors make the mod pretty much unusable.
This can be tested with just In Control 7.0.8 running on Forge 43.1.33, with the first example `spawn.json` script from the wiki put into `spawn.json` in the `incontrol` folder.

**Comment by McJty** [comment]
Which spawn.json is that exactly?

**Comment by saltyseadoggo** [comment]
```
[
  {
    "biome": "minecraft:plains",
    "result": "allow"
  },
  {
    "result": "deny"
  }
]

**Comment by McJty** [comment]
I will test it out. Weird though. Have not experienced this before though. I wonder if there is a conflict with another mod or something. Very strange

**Comment by saltyseadoggo** [comment]
It shouldn't be a mod conflict, as I replicated this with *only* In Control loaded, as per my instructions.

**Comment by McJty** [comment]
You have anything in spawner.json? Can I see your log?

**Comment by saltyseadoggo** [comment]
`spawner.json` is empty; it was freshly generated by the mod when it was loaded the first time.
Here's a log. In this log, I just started the game, created a new world, wandered at the edge of the very slowly generating chunks for a moment, and then saved and quit to title.
[latest.log](https://github.com/McJtyMods/InControl/files/9743215/latest.log)

**Comment by McJty** [comment]
I can reproduce the problem and I think it has to do with biome checking. I'm investigating

**Comment by McJty** [comment]
Fixed. It was the biome test
