### ISSUE TITLE
wrong forge version for 1.19.2

### ISSUE THREAD

**Issue by Heptagram064** [McJty/InControl#352]
Latest stable forge version is 43.1.1, yet this mod uses 43.1.30

Fortunately optifine seems to still work, even tho the developer only supports 43.1.1 officially.

It remains a nuisance...

PS: 43.1.30 is not even the latest preview forge lol

**Comment by McJty** [comment]
Well I need that forge. You should always use recent forge as it has more bugfixes. The stable annotation doesn't mean anything

**Comment by Heptagram064** [comment]
From experience with other software it is a little bit counter intuitive, as unstable releases usually contain more bugs than stable ones due to preview features. But i guess for minecraft forge it works different, taking your word for it (As i have yet to encounter any issues).
