### ISSUE TITLE
[1.18.2] World frozen on Join / or randomly when exploring

### ISSUE THREAD

**Issue by itsdinkd** [McJty/InControl#353]
Updated from 6.0.12  to 6.0.16 and now when I create worlds ticks will freeze on join. If it doesn't on world creation, it will after exploring overworld a bit, or the end, or nether. 

Nothing in logs indicate why. however, due to binary searching, it fixes when in control is downgraded. 

```
[
  {
    "mob": ["stalwart_dungeons:awful_ghast"],
    "result": "default",
    "healthmultiply": 14,
    "damagemultiply": 3,
    "speedmultiply": 1.3,
    "onjoin": true
  },
  {
    "mob": ["stalwart_dungeons:nether_keeper"],
    "result": "default",
    "healthmultiply": 10,
    "damagemultiply": 2.5,
    "speedmultiply": 1.2,
    "onjoin": true
  },
  {
    "mob": ["cataclysm:ignis"],
    "result": "default",
    "healthmultiply": 12,
    "damagemultiply": 2.4,
    "speedmultiply": 1.1,
    "onjoin": true
  },
  {
    "mob": ["cataclysm:netherite_monstrosity"],
    "result": "default",
    "healthmultiply": 12,
    "damagemultiply": 2.1,
    "speedmultiply": 1.1,
    "onjoin": true
  },
  {
    "mob": ["undergarden:masticator"],
    "result": "default",
    "healthmultiply": 2,
    "damagemultiply": 2.61,
    "speedmultiply": 1.05,
    "onjoin": true
  },
  {
    "mob": ["goblinsanddungeons:goblin_king"],
    "result": "default",
    "healthmultiply": 3,
    "damagemultiply": 2.2,
    "onjoin": true
  },
  {
    "mob": ["cataclysm:ender_golem"],
    "result": "default",
    "healthmultiply": 15,
    "damagemultiply": 2.2,
    "speedmultiply": 1.1,
    "onjoin": true
  },
  {
    "mob": ["cataclysm:ender_guardian"],
    "result": "default",
    "healthmultiply": 12,
    "damagemultiply": 2.15,
    "speedmultiply": 1.1,
    "onjoin": true
  },
  {
    "mob": ["stalwart_dungeons:shelterer"],
    "result": "default",
    "healthmultiply": 10,
    "damagemultiply": 4,
    "speedmultiply": 1.2,
    "onjoin": true    
  },
  {
    "mob": ["minecraft:creeper"],
    "result": "default",
    "speedmultiply": 1.3,
    "damagemultiply": 1.7,
    "random": 0.2
  },
  {
    "mod": "stalwart_dungeons",
    "result": "default",
    "healthmultiply": 1.4,
    "damagemultiply": 1.5,
    "random": 0.85
  },
  {
    "mod": "cataclysm",
    "result": "default",
    "healthmultiply": 2.0,
    "damagemultiply": 1.5,
    "random": 0.85,
    "onjoin": true
  },
  {
    "mod": "weirdmobs",
    "result": "default",
    "healthmultiply": 1.8,
    "damagemultiply": 1.35,
    "random": 0.85,
    "onjoin": true
  },
  {
    "mod": "orcz",
    "result": "default",
    "healthmultiply": 1.8,
    "damagemultiply": 1.4,
    "onjoin": true
  }
]
```

**Comment by Dyshonored** [comment]
Have the same issue here as well. Removing in control seems to fix the freezes.

**Comment by Dyshonored** [comment]
tried the mod on 1.19.2. Seems to have the same freezing issues.

**Comment by McJty** [comment]
@itsdinkd try updating to 6.0.23

@Dyshonored can you give more information? Logs? Also what rules you are using? Version?

**Comment by Dyshonored** [comment]
Forge Version is 40.1.73 (1.18). In control version is 6.0.24.
For 1.19 I used forge 43.1.52 with in control version 7.0.15.

The config file are the same between the two versions and is provided below. Only the spawn file is used.

Spawn.json
[
  {
    "mob": "minecraft:skeleton",
    "onjoin": true,
	"seesky": false,
	"dimension": "minecraft:overworld",
	"helditem": ["2=magistuarmory:rusted_heavymace", "1=magistuarmory:rusted_bastardsword", "5=minecraft:bow"],
	"armorhelmet": ["1=magistuarmory:rustedbarbute", "1=magistuarmory:rustedchainmail_helmet", "1=magistuarmory:rustedkettlehat", "1=magistuarmory:rustednorman_helmet"],
    "result": "default"
  },
  {
    "mob": "minecraft:skeleton",
    "onjoin": true,
	"dimension": "minecraft:the_nether",
    "nbt": {
      "HandItems": [
        {
          "id":"minecraft:bow",
          "Count": 1,
          "tag": {
            "Enchantments": [
              {
                "lvl": 1,
                "id": "minecraft:flame"
              }
            ]
          }
        },
        {}
      ]
    },
	"armorhelmet": ["1=magistuarmory:rustedchainmail_helmet", "1=magistuarmory:rustedkettlehat", "1=magistuarmory:rustednorman_helmet"],
	"armorchest": ["1=magistuarmory:rustedchainmail_chestplate", "1=magistuarmory:rustedcrusader_chestplate"],
	"armorlegs": ["magistuarmory:rustedchainmail_leggings"],
	"armorboots": ["1=magistuarmory:rustedchainmail_boots", "1=magistuarmory:rustedcrusader_boots"],
    "result": "default"
  },
  {
    "mob": "minecraft:stray",
    "onjoin": true,
	"potion": "minecraft:instant_damage,1,5",
	"helditem": ["2=contenttweaker:steel_guisarme", "2=contenttweaker:steel_concavehalberd", "2=contenttweaker:steel_morgenstern", "10=minecraft:bow"],
	"armorhelmet": ["1=magistuarmory:rustedchainmail_helmet", "1=magistuarmory:rustedkettlehat", "1=magistuarmory:rustednorman_helmet"],
	"armorchest": ["1=magistuarmory:rustedchainmail_chestplate", "1=magistuarmory:rustedcrusader_chestplate"],
	"armorlegs": ["magistuarmory:rustedchainmail_leggings"],
	"armorboots": ["1=magistuarmory:rustedchainmail_boots", "1=magistuarmory:rustedcrusader_boots"],
	"healthmultiply": 1.25,
    "result": "default"
  },
  {
    "mob": "minecraft:zombie",
	"onjoin": true,
	"seesky": false,
	"armorchest": ["1=magistuarmory:rustedchainmail_chestplate", "1=magistuarmory:rustedcrusader_chestplate", "1=magistuarmory:rustedhalfarmor_chestplate"],
	"armorlegs": ["magistuarmory:rustedchainmail_leggings"],
	"armorboots": ["1=magistuarmory:rustedchainmail_boots", "1=magistuarmory:rustedcrusader_boots"],
    "result": "default"
  },
  {
    "mob": "minecraft:husk",
	"onjoin": true,
	"healthmultiply": 1.5,
	"potion": "minecraft:instant_damage,1,5",
	"helditem": ["2=epicfight:stone_spear", "3=epicfight:stone_greatsword", "3=minecraft:iron_sword"],
	"armorhelmet": ["1=magistuarmory:rustedbarbute", "1=magistuarmory:rustedgreathelm", "1=magistuarmory:rustedkettlehat"],
	"armorchest": ["1=magistuarmory:rustedcrusader_chestplate", "1=magistuarmory:rustedhalfarmor_chestplate"],
	"armorlegs": ["magistuarmory:rustedchainmail_leggings"],
	"armorboots": ["1=magistuarmory:rustedchainmail_boots", "1=magistuarmory:rustedcrusader_boots"],
    "result": "default"
  },
  {
    "mob": "minecraft:drowned",
	"onjoin": true,
	"healthmultiply": 1.75,
	"helditem": ["3=minecraft:trident", "3=minecraft:iron_sword", "3=minecraft:iron_axe"],
	"potion": "minecraft:instant_damage,1,5",
    "result": "default"
  },
  {
    "mob": "minecraft:vindicator",
    "onjoin": true,
	"healthmultiply": 1.25,
	"potion": "minecraft:regeneration,720000,2",
    "result": "default"
  },
  {
    "mob": "minecraft:illusioner",
    "onjoin": true,
    "nbt": {
      "HandItems": [
        {
          "id":"minecraft:bow",
          "Count": 1,
          "tag": {
            "Enchantments": [
              {
                "lvl": 5,
                "id": "minecraft:power"
              }
            ]
          }
        },
        {}
      ]
    },
    "result": "default"
  },
  {
    "mob": ["minecraft:evoker", "minecraft:ravager", "minecraft:wither"],
    "onjoin": true,
	"potion": "minecraft:resistance,720000,2",
    "result": "default"
  },
  {
    "mob": "minecraft:blaze",
    "onjoin": true,
	"potion": "minecraft:resistance,720000,1",
    "result": "default"
  },
  {
    "mob": "minecraft:ghast",
    "result": "default",
	"onjoin": true,
	"potion": "minecraft:instant_health,1,4",
	"healthmultiply": 8.0
  },
  {
    "mob": "minecraft:wither_skeleton",
    "dimension": "minecraft:the_nether",
	"onjoin": true,
	"potion": "minecraft:instant_damage,1,5",
	"helditem": ["2=epicfight:netherite_longsword", "2=contenttweaker:netherite_flamebladedsword", "2=epicfight:netherite_greatsword", "2=minecraft:netherite_sword"],
	"armorhelmet": ["minecraft:netherite_helmet"],
	"armorchest": ["minecraft:netherite_chestplate"],
	"armorlegs": ["minecraft:netherite_leggings"],
	"armorboots": ["minecraft:netherite_boots"],
    "result": "default"
  },
  {
    "mob": ["minecraft:piglin_brute", "minecraft:hoglin"],
    "onjoin": true,
	"potion": ["minecraft:instant_health,1,5", "minecraft:regeneration,720000,3"],
    "result": "allow"
  },
  {
    "mob": "minecraft:ender_dragon",
    "onjoin": true,
	"potion": ["minecraft:instant_health,1,5", "minecraft:resistance,720000,2"],
    "result": "default",
	"healthmultiply": 2.0
  },
  {
    "mob": "minecraft:horse",
    "result": "allow",
	"onjoin": true,
	"potion": ["minecraft:resistance,9999999,3", "minecraft:regeneration,9999999,1"]
  },
  {
    "mob": "minecraft:iron_golem",
    "result": "allow",
	"onjoin": true,
	"potion": "minecraft:regeneration,9999999,1"
  }
]

The logs seem normal with no error reported. It usually gets stuck on preparing spawn area at 94% but some times it can load into the world successfully but freezes after a short time (in this case the log just stops dead with no new chunk saving messages which it usually produces every minute or so). No crash report is ever generated. However, upon using task manager to force exit Minecraft the launcher would give me the error code -1 message every time.

**Comment by Dyshonored** [comment]
The json file format got removed in my above message. It is supposed to have indentations.

**Comment by T0mt4ru** [comment]
I'm using Forge 40.2.0 with incontrol-1.18-6.1.1 and this issue still exists. 
There is nothing in the logs to indicate any problems. The game won't save or quit and needs to be forced to end with the task manager.

**Comment by McJty** [comment]
I'll check it out soon. Sorry for neglecting this

**Comment by McJty** [comment]
It's possible that the latest version fixes this. Let me know if it does

**Comment by T0mt4ru** [comment]
I updated to and tested Version [1.18-6.1.2] and travelled a good amount of blocks (about 50k) and no tick freeze has been observed.

Thank you!
