### ISSUE TITLE
Game Keeps Crashing while trying to load up the game [1.12.2]

### ISSUE THREAD

**Issue by GodsServant0317** [McJty/InControl#354]
Every time I try to load up the game Incontrol just crashes my game before I even get to the Menu screen. The Same thing seems to happen no matter what. I tried to change settings and it crashed and after I deleted the mod and config file and re downloading it it still crashed

**Comment by McJty** [comment]
Show me your jsons. Also post the crashlog

**Comment by RayBlazar** [comment]
similar issue
[crash-2022-11-12_22.17.20-client.txt](https://github.com/McJtyMods/InControl/files/9996507/crash-2022-11-12_22.17.20-client.txt)
spawn.json
[
   {
    "mob": "mocreatures:lion",
	"biome": "Savanna",
	"seesky": true,
	"maxcount": 9,
	"result": "allow"
  }
]

potentialspawn.json
[  
  {
    "dimension": 0,
    "mobs": [
   {
     "mob": "mocreatures:lion",
     "weight": 5,
     "groupcountmin": 3,
     "groupcountmax": 5
   }
]

**Comment by McJty** [comment]
First, your spawn.json doesn't do anything because allow is default. Mobs are allowed to spawn already. You need to reverse the logic and deny if there are too many or if the biome/seesky isn't right.

Secondly, there is a } missing before the last ] in potentialspawn

**Comment by RayBlazar** [comment]
Can I continue to ask you questions here, or is there a discord? Whether its you or someone else. There doesn't seem to be any resource other then the wiki

**Comment by McJty** [comment]
My discord is at: https://discord.gg/YaWr7Zb
