### ISSUE TITLE
[1.15.2]InControl question

### ISSUE THREAD

**Issue by 2929762171** [McJty/InControl#356]
When I use this rule,they are no longer spawn anywhere.....
And "dimension": "mmorpg:resettable_dungeon" is the same situation.
(I just want to know how it works.)

{
	"mob": ["mutantbeasts:mutant_creeper","mutantbeasts:mutant_zombie","mutantbeasts:mutant_skeleton"],
	"dimensionmod": "mineandslash",
	"onjoin": true,
	"result": "deny"
 }

**Comment by McJty** [comment]
Well this rule would make those mobs not spawn in all dimensions from mineandslash. Is that what you want?

**Comment by 2929762171** [comment]
Yes,but it works on other dimensions..

**Comment by McJty** [comment]
Ah you use dimensionmod. That's not supported in 1.15.2. In fact 1.15.2 is ancient. That's not a version I support still

**Comment by 2929762171** [comment]
OK,thanks
