### ISSUE TITLE
Cannot spawn zombies during the day?

### ISSUE THREAD

**Issue by s0c00b0** [McJty/InControl#357]
I'm trying to use the In Control! mod in 1.19.2 to make a "zombie apocalypse" scenario, but the mobs refuse to spawn during the day even though I have turned on `"norestrictions": true`. Other mods I have installed are Lost Cities, Serene Seasons, and Mob Sunscreen.

Here are my files.

>spawner.json

    [
        {
            "mob": "minecraft:zombie",
            "persecond": 1,
            "attempts": 5,
            "amount": {
                "minimum": 10,
                "maximum": 40,
                "groupdistance": 10
            },
            "conditions": {
                "dimension": "minecraft:overworld",
                "inliquid": true,
                "inair": true,
                "norestrictions": true
            }
        }
    ]

>spawn.json

    [
        {
            "mob": "minecraft:zombie",
    
            "healthmultiply": 0.2,
            "damagemultiply": 0.2,
            "speedmultiply": 0.5,
            
            "result": "allow"
        },
        {
            "result": "deny"
        }
    ]

Can you tell me what I did wrong?

Thank you!

**Comment by McJty** [comment]
In spawner.json you said both inliquid: true and inair: true. Those contradict. You can't be both in a liquid and in the air so this will never spawn anything
