### ISSUE TITLE
The "insphere" rule does not work in 1.12

### ISSUE THREAD

**Issue by efficient-efi** [McJty/InControl#358]
When using the "biosphere" in the lost cities mod, I want to prevent monsters from spawning inside the sphere, but using the "insphere" rule does not work.
Please help.

**Comment by McJty** [comment]
I need a LOT more info. What did you do exactly? Show your entire rule file and explain what is happening (or not happening)

**Comment by efficient-efi** [comment]
This is "spawn.json" file.
Monsters spawn inside the city sphere.

[
  {
    "onjoin":true,
    "insphere": true,
    "result": "deny"
  }
]

**Comment by McJty** [comment]
How are you testing this?

**Comment by efficient-efi** [comment]
When I create a world with that setting and set the time to night, the monsters spawn inside the sphere.

**Comment by McJty** [comment]
What mobs are spawning exactly? Vanilla or modded? What happens if you remove the "insphere": true test?

**Comment by efficient-efi** [comment]
All mobs,vanilla and modded are spawning.
And I removed "incities", mobs don't spawn.
It seems that the "in control" itself is working, but the "insphere" rule is not working.

**Comment by McJty** [comment]
incities? You mean insphere I suppose?

**Comment by McJty** [comment]
Try removing "onjoin": true but with "insphere": true

**Comment by efficient-efi** [comment]
I see.

**Comment by efficient-efi** [comment]
hmm,mobs are still spawning.

**Comment by McJty** [comment]
No clue then. It might have been broken in 1.12 but I thought it worked. Anyway I no longer work on 1.12 so if it doesn't work then I'm afraid it will remain not working. Make sure you're using the last version of all my mods though

**Comment by efficient-efi** [comment]
Yes I using latest version.
It doesn't matter if there is no solution.
Thanks for answering my question!

**Comment by efficient-efi** [comment]
Oh, I can do something similar with the "minspawndist" rule! (in "biosphere" the spawn point is inside the sphere)
