### ISSUE TITLE
[1.19.2] spawner.json rules are not spawning

### ISSUE THREAD

**Issue by s0c00b0** [McJty/InControl#359]
Here are my files:

> spawn.json

```
[
    {
        "incontrol": true,
        "result": "allow"
    },
    {
        "result": "deny"
    }
]
```
> spawner.json

```
[
    {
        "mob": "minecraft:zombie",
        "persecond": 1,
        "attempts": 5,
        "amount": {
            "minimum": 10,
            "maximum": 40,
            "groupdistance": 10
        },
        "conditions": {
            "dimension": "minecraft:overworld",
            "norestrictions": true
        }
    }
]
```

If I'm not wrong, the spawner.json data makes a ton of zombies spawn without restriction (AKA during the day, any light level) and the spawn.json data makes **only** the InControl custom zombies able to spawn and disables any other mobs. So what I should be seeing is just a bunch of zombies wandering around with no other mobs at all.

But running this code on a new superflat world makes no mobs spawn at all, even during nighttime.

What is wrong with my code? Is there a required field that I am missing?

**Comment by McJty** [comment]
You got rid of a lot of fields for the 'conditions' block (like minheight and maxheight and so on). I recommend not depending on the defaults as they may not be suitable for flat worlds. Also try with only [] in spawn.json. To test if it works with spawner.json alone

**Comment by s0c00b0** [comment]
Adding in minheight/maxheight/mindist/maxdist worked. Thank you so much!
