### ISSUE TITLE
Crash from Spawner.json utilizing Nightmaremobs

### ISSUE THREAD

**Issue by Ghostcody** [McJty/InControl#362]
Server constantly crashes when more than one player enters.
I have noticed that this also happens with vanilla mobs too.

`[
  {
    "mob": "nmcmobs:mermaid",
    "persecond": 0.2,
    "attempts": 2,
    "amount": {
      "minimum": 2,
      "maximum": 5,
      "groupdistance": 3
    },
    "conditions": {
      "dimension": "minecraft:overworld",
      "inwater": true,
      "minheight": 10,
      "maxheight": 50,
      "maxthis": 20
    }
  },
  {
    "mob": "nmcmobs:merman_soldier",
    "persecond": 0.2,
    "attempts": 2,
    "amount": {
      "minimum": 2,
      "maximum": 5,
      "groupdistance": 3
    },
    "conditions": {
      "dimension": "minecraft:overworld",
      "inwater": true,
      "minheight": 10,
      "maxheight": 50,
      "maxthis": 20
    }
  }
]`

[crash-2022-11-30_00.38.49-server.txt](https://github.com/McJtyMods/InControl/files/10136826/crash-2022-11-30_00.38.49-server.txt)

**Comment by McJty** [comment]
Thanks for reporting. I'll check it out

**Comment by McJty** [comment]
Should be fixed now
