### ISSUE TITLE
Suggestion: Allow NBT Spawn Filtering

### ISSUE THREAD

**Issue by firemaster1294** [McJty/InControl#364]
Feel free to close this issue if this is possible - I haven’t seen a way to do this yet though.

it would be nice to have the ability to allow/disallow spawns if a mob matches a given NBT state. You could have two conditions: hasNBT or hasExactNBT. This would allow for greater control over mob spawns especially with mods that rely heavily on NBT-based mob behaviour instead of different mobs.

To go along with this, it seems Vanilla just overrides the NBT of a mob with whatever is provided by this mod. If there’s a way to extract this info beforehand (as would be needed for the above functions to work), perhaps you could store this NBT data and then give In Control users the option to either merge or override the existing data tag. Just an idea.

Thanks for taking the time to read this suggestion!

**Comment by McJty** [comment]
This is already possible using the "nbt" keyword
