### ISSUE TITLE
Keep Mobspawners

### ISSUE THREAD

**Issue by Kiwicast** [McJty/InControl#367]
Hi,

This is most likely more of a user issue than a mod issue. I am pretty new to modded Minecraft and I am using Create Flavored Modpack on 1.19.2. We had issues with way too many mobs spawning and causing a spamming error in the console. I was suggested your mod by Pebblehost tech support, so i have added it to my server, it seems to be helping a bit and the crashes aren't happening but there's still a  bit of spamming, however I know the mods job is to reduce the spawning of mobs, but we have people in the SMP which has mob farms using spawners, however since the mod has been installed it has been removing their spawners. Is there a way to stop this and can you please instruct me how. Sorry as I say I'm still really new to this.

**Comment by McJty** [comment]
You probalby have a rule denying mob spawns somehow. You can use the "spawner": false keyword to make those rules work only on normal spawns and not on spawners

**Comment by Kiwicast** [comment]
ok sorry to sound dumb here ive never had to edit the config files before. when I looked in the files the only config files i can find were pretty close to empty. which file do i put this in and what do I type

**Comment by McJty** [comment]
Hmm ok. What's in the file spawn.json? Because if it doesn't contain anything then this problem is not caused by In Control

**Comment by Kiwicast** [comment]
This is whats in my spawn.json

[{
        "mob": "minecraft:spider",
        "dimension": "minecraft:overworld",
        "spawner": false,
        "minheight": 32,
        "result": "deny"
    },
    {
        "mob": ["minecraft:phantom", "minecraft:witch", "minecraft:stray", "savage_and_ravage:iceologer"],
        "dimension": "minecraft:overworld",
        "result": "deny"
    },
    {
        "mob": "minecraft:phantom",
        "dimension": "minecraft:the_end",
        "result": "allow"
    }
]

**Comment by McJty** [comment]
That last rule for the phantom is useless. 'allow' is default. Otherwise it looks ok. What kind of spawner isn't working?

**Comment by Kiwicast** [comment]
it deletes spawners i know for sure spiders, and zombies, but maybe blaze as well

**Comment by McJty** [comment]
What types of spawners?

**Comment by McJty** [comment]
I mean vanilla spawners or modded?

**Comment by Kiwicast** [comment]
vanilla i am being told

**Comment by McJty** [comment]
I don't see how that's possible to be honest...

**Comment by Kiwicast** [comment]
if it was modded spawners would that make a difference?

**Comment by McJty** [comment]
It might

**Comment by Kiwicast** [comment]
yea sorry its so vague, im sort of new. do u think it could be caused by another mod?, its just become more noticable since i added the mod though

**Comment by McJty** [comment]
It might. Not enough information on this side though. You'll have to ask more details from your players. What type of spawners do they mean

**Comment by Kiwicast** [comment]
ok i have a guy he will be on tomorrow whos more experienced with this stuff.. i will follow up with him and get back to you.

**Comment by Kiwicast** [comment]
So in the last 24 hours this is the information I have found out, its Vanilla spawners and its mainly Blaze Spawners, placed in the over world. On occasion a zombie or cave spider vanilla spawner disappears but its majoritively the blaze ones.

**Comment by McJty** [comment]
What do you mean? The spawner actually disappears? If that's the case then that's not caused by In Control. It doesn't remove blocks

**Comment by Kiwicast** [comment]
yea my friend just literally saw 7 of them disappear in front of him. do you think it could be because blaze spawners usually arent present in the overwordl?

**Comment by McJty** [comment]
Ok, but if that's happening then that's not In Control. Note that there are other mods that make spawners time out. The RLCraft modpack for example lets spawners disappear if they spawned a number of mobs. I guess you have a mod like that on your server

**Comment by Kiwicast** [comment]
ohhh ok ill have to check with the mod pack developer if they know of a mod in there that has that sort of setting. Thanks for your help

**Comment by T0mt4ru** [comment]
I'll help you out quick, [Create Flavoured] contains the mod [Ageing Spawners]

It changes spawners so that they break after X amount of mob spawns, making spawner farms moot.

Certainly not an [InControl]
 function :)
