### ISSUE TITLE
Mobs spawned by spawner.json spawning on non-full-block blocks

### ISSUE THREAD

**Issue by martinkoeth** [McJty/InControl#370]
I mostly spawn mobs with spawner.json and configure their spawn requirements in special.json and spawn.json. It works fine, however, monsters will also spawn on stairs and other non-full-block blocks.

My configurations:
[special.txt](https://github.com/McJtyMods/InControl/files/10610959/special.txt)
[spawner.txt](https://github.com/McJtyMods/InControl/files/10610960/spawner.txt)
[spawn.txt](https://github.com/McJtyMods/InControl/files/10610961/spawn.txt)

**Comment by McJty** [comment]
This is solved in 1.18+ with the new 'sturdy' keyword in spawner.json
