### ISSUE TITLE
Issue with setting the mob spawn only on one biome.

### ISSUE THREAD

**Issue by dam2452** [McJty/InControl#372]
I tried to set the spawn of the abyssal guardian so that it could spawn only in a small amount in a given biome. After adding the "biome" parameter, nothing changed with respect to the biome and it still respawns in other biomes.
spawn.json
[
	{
    "mob": ["aquaticabyssmod:abyssalguardian"],
    "biome": "aquaticabyssmod:venttrench",
    "perplayer": true,
    "mincount": 40,
    "result": "deny"
  }
]
potentialspawn.json
[
	{
	
		"mobs": [
			{
				"mob": "aquaticabyssmod:halibut",
				"weight": 1,
				"groupcountmin": 1,
				"groupcountmax": 1
			}
		]
	},
	{
	
		"mobs": [
			{
				"mob": "aquaticabyssmod:abyssalguardian",
				"weight": 1,
				"groupcountmin": 1,
				"groupcountmax": 1
			}
		]
	}
	
]

**Comment by McJty** [comment]
You need to use the biome name in 1.12. i.e. Like 'Plains'

**Comment by dam2452** [comment]
So in this case it will be "venttrench" instead of "aquaticabyssmod:venttrench" and it should work?

**Comment by McJty** [comment]
Probably 'Venttrench'. The case mattters. It's the actual name that you see when in F3 I think
