### ISSUE TITLE
"Passengers" nbt tag not working

### ISSUE THREAD

**Issue by TheBeardyPenguin** [McJty/InControl#375]
MC version 1.12.2, forge modloader 14.23.5.2860
The "Passengers" nbt tag in spawn.json which normally allows the spawning of jockeys does not work. The syntax is definitely correct as other tags such as "ArmorItems" work just fine (not that I'd use it thanks to the built in armor tags but it was a useful test). For example, here is my attempt to spawn a wither skeleton with a slime on its head which works just fine with the /summon command. The skeleton is spawned but no slime:

```
{
    "mob": "minecraft:wither_skeleton",
    "nbt":
    {
	"Passengers": [
		{
			"id": "minecraft:slime",
			"Size": 1
		}
	]
    },
    "onjoin": true
}

**Comment by McJty** [comment]
yes, that will not work. The problem is that In Control is not aware of what nbt is passed along and just sets the nbt. However, the corresponding mob will not be spawned. This will not be fixed as I no longer work on 1.12.2 and I'm not even sure how to fix to be honest
