### ISSUE TITLE
Provide CLEAR & UP-TO-DATE conditions on the Wiki page

### ISSUE THREAD

**Issue by wilsoffer** [McJty/InControl#378]
I am on 1.19.2 and I want to added modded mobs to modded biomes.
Despite the simple request, I have found it a pain to do such. The Wiki is inaccurate and out dated. Terms such as biome, biometags, weight, etc. do not exist despite the Wiki suggesting such. I have followed countless tutorials, used examples directly from the Wiki, and even proof-read my json on an online validator. The problem is not me - it is the lack of moderation on the sites dedicated toward providing clear moderation.

**Comment by McJty** [comment]
Tags, biometags, ... all exist. I don't know why you think they don't? Can you provide any examples of where you think they don't exist? The wiki is very up-to-date and I maintain it together with the code

**Comment by McJty** [comment]
Can you show me what you did in order to try to add modded mobs to modded biomes. Because that certainly works if you do it right

**Comment by McJty** [comment]
@wilsoffer Ping?
