### ISSUE TITLE
[1.19.2] Denying all, but mobs still spawning in structures

### ISSUE THREAD

**Issue by pouchrat** [McJty/InControl#381]
Mod version: 1.19-7.1.7
Forge version: 43.2.0

spawn.json:
```json
[
    {
        "result": "deny"
    }
]
```

Bees and structure mobs (e.g. in villages, ruins, or mansions) are still spawning. Everything else seems to be following the rule. I also tried adding a "deny" rule above the blanket deny for `"spawner": true`, but that didn't help. Tested on an instance with no other mods.

**Comment by McJty** [comment]
Add "onjoin": true

**Comment by pouchrat** [comment]
That worked, thank you! Sorry, could have sworn I tried that already.
