### ISSUE TITLE
Discord? Any discuss thread? Help

### ISSUE THREAD

**Issue by Proxwian** [McJty/InControl#383]
Didn't found any discussions about mod, also invite link in CF page is broken as hell.

Also didn't find any information about validspawn condition usage. What the heck is this..

**Comment by McJty** [comment]
The invite link for Discord works perfectly fine. Just tried it
Anyway, here it is again: https://discord.gg/jaPZzxXY5Z

**Comment by Proxwian** [comment]
You need to update it here: https://www.curseforge.com/minecraft/mc-mods/in-control

**Comment by McJty** [comment]
Nope, that link works fine for me
