### ISSUE TITLE
How to use "continue" to control multiple actions

### ISSUE THREAD

**Issue by Tibsalta-IC** [McJty/InControl#384]
May I ask how should I use this keyword? Wikipedia does not provide a detailed definition.
<img width="711" alt="屏幕截图 2023-06-10 170437" src="https://github.com/McJtyMods/InControl/assets/133666394/1eda3096-6f20-4a85-94a5-acf4ec6b1fe9">

**Comment by McJty** [comment]
You just put "continue": true in a rule and that will not stop processing
