### ISSUE TITLE
spawn / spawner.json biome not working

### ISSUE THREAD

**Issue by bobzeus** [McJty/InControl#392]
Endermen spawn outside of the warped forest in the nether with the below spawn.json and spawner.json file setups
(following on from an earlier convo in the discord, files converted to txt so uploadable to github)
just to note, the indent in the incontrol part still gives the issue if its inline with the rest of the text
and the version used is 1.20.1
[spawn.txt](https://github.com/McJtyMods/InControl/files/12327997/spawn.txt)
[spawner.txt](https://github.com/McJtyMods/InControl/files/12327998/spawner.txt)

**Comment by bobzeus** [comment]
just to note, the indent in the incontrol part still gives the issue if its inline with the rest of the text

**Comment by McJty** [comment]
Fixed in 1.20-9.0.1
