### ISSUE TITLE
1.18 mob spawning in 1.12

### ISSUE THREAD

**Issue by MasterCakeX5** [McJty/InControl#394]
Trying to reproduce 1.18+ mob spawning (light level 0 on both surface and caves) in 1.12.
In spawn.json I did
```
[
{
"hostile": true,
"minlight": 1,
"result": "deny"
}
]
```
but nothings spawns at night. Is there any way to ignore the moonlight stuff and only have the block light value as shown in light overlay mods?
Thanks!

**Comment by McJty** [comment]
"deny" will deny spawns. How will that help create ADDITIONAL spawns? With spawn.json you can only lower the amount of spawns. Not increase it. You need to use potentialspawn to add spawns

**Comment by MasterCakeX5** [comment]
Hm maybe I am a bit dumb but I don't understand it correctly. I only want to block spawns, not allow them.
In 1.12 everything spawns at light level 0-7.
In 1.18 everything spawns at light level 0, also on the surface. So in my logic I have to block everything above 0.
So when I set the light level to 1 it should also block spawns at light level 1+ but 0, right? Weirdly it blocks even light level 0 on the surface but not in caves. Is there any workaround for that? I sadly dont understand much about coding..

**Comment by McJty** [comment]
Ah right sorry. Misunderstood you. Hmm what you wrote should work

**Comment by MasterCakeX5** [comment]
Can it be that the mod checks for sky light level and not for block light level? I read that in 1.12 even at night there is always light level 4 because of the moon.. maybe there is a way to check for block light instead?
I think there are a lot of people who would love to have 1.18 mechanic in 1.12, maybe you could try to verify the problem I have in 1.12? Thanks!

**Comment by McJty** [comment]
Hmm it's possible that I'm checking the wrong thing in 1.12. However, I no longer work on 1.12 so can't really do any bugfixes there I'm afraid

**Comment by MasterCakeX5** [comment]
Oh no.. thats sad.. so there is really no way to get this feature? :( I'd even pay for that

**Comment by McJty** [comment]
I hardly have time to work on my 1.20 mods. And the problem is that developing for 1.12 is very hard now since the normal tools are broken. I really don't feel like spending so much time on an ancient version that IMHO shouldn't be used anymore

**Comment by MasterCakeX5** [comment]
Ok I can understand it. Sadly things like RLCraft or Sevtech will never be updated post 1.12... thank you anyway :)

**Comment by McJty** [comment]
Actually the author of RLCraft said he wants to update RLCraft to more modern versions of MC at some point
