### ISSUE TITLE
Issue ingame saying "invalid keywords for spawn.json:amount persecond condition attempts" 

### ISSUE THREAD

**Issue by Macksterz** [McJty/InControl#399]
This is the code I copied from a modshowcase to increase zombie spawnrates on forge 1.18.2 and I keep seeing that message. If there's a problem with the code I copied if I could get a new one to copy that would be helpful. It's minimum rn is 40 and maximum of 130 with a persecond of 6 which I changed from 5.

**Comment by Macksterz** [comment]
ok ive now got access to my whole current code
[

{

"mob": "minecraft:zombie",

"persecond": 6,

"attempts": 40,

"amount": {

"minimum": 40,

"maximum": 130

},

"conditions": {

"dimension": "minecraft:overworld",

"norestrictions": false,

"mindist": 15,

"maxdist": 70,

"minheight": 1,

"maxheight": 256,

"maxthis": 150

}

}

**Comment by McJty** [comment]
That is not for spawn.json. You should put that in spawner.json
