### ISSUE TITLE
"spawner" key for `spawn.json` is not working

### ISSUE THREAD

**Issue by khazenor** [McJty/InControl#401]
forge version: 47.2.4
InControl version: 1.20-9.0.4

tested with just minecraft, forge, and InControl

It seems like the "spawner" key for `spawn.json` is not working?  I have the following in my spawn.json and the hostile mobs are still spawning:
```
[
  {
    "hostile": true,
    "dimension": "minecraft:overworld",
    "spawner": false,
    "result": "deny"
  }
]
```
while the following will prevent the mobs from spawning
```
[
  {
    "hostile": true,
    "dimension": "minecraft:overworld",
    "result": "deny"
  }
]
```

**Comment by McJty** [comment]
Will be fixed in the next version
