### ISSUE TITLE
Using game stages as conditions to deny mob spawning in 1.20.1 causes the mod to not function

### ISSUE THREAD

**Issue by wmafranz** [McJty/InControl#407]
I am wanting to gate certain modded and vanilla mobs behind the game stages introduced by Majrsuz's Difficulty Mod, but it seems that using game stages as conditions for denying mobs from spawning causes inControl to stop working in version 1.20.1. 

The working spawn.json has no game stage condition, and prevents the listed mobs from spawning properly, however, upon adding the game stage condition to spawn.json (the "notworking" version), the mobs, both modded and vanilla, begin to spawn anyways despite the global game stage being "normal". I'm pretty sure I've set it up right but let me know if I've done something wrong!

[spawn(notworking).json](https://github.com/McJtyMods/InControl/files/13921550/spawn.notworking.json)
[spawn(working).json](https://github.com/McJtyMods/InControl/files/13921552/spawn.working.json)

**Comment by McJty** [comment]
Global game stage? What's that? Game stages are per player. If gamestages now supports global gamestages then those will not work for In Control yet. Wasn't even aware that was a thing

**Comment by wmafranz** [comment]
So it turns out "Global Game stages" isn't really a thing, it's just Majrsuz's Difficulty mod calling its "gamestate" feature something misleading :P
