### ISSUE TITLE
The new breakevents.json doesn't like nbt it seems... 

### ISSUE THREAD

**Issue by DanRobzProbz** [McJty/InControl#410]
This example doesn't work for the new breakevents.json.

I just copied the code and pasted it in my breakevents.json from the site examples given, when mining I get a prompt saying that the block can't be mined(which is what I want) but then if I enchant my Iron Pickaxe with Unbreaking(id 34) it doesn't break the block still...
It should be able to be mined if it has that enchantment attached, right?!

I tried many different ench ids and still nothing sadly.
Any help would be appreciated, thanks.
:)

All I wanted was to make players only be able to mine ores if they had silk touch(id 33)

Thanks!
![Screenshot 2024-01-24 091224](https://github.com/McJtyMods/InControl/assets/20096690/34f95a3a-15b6-4b63-96a9-f7e54f9d551a)

**Comment by McJty** [comment]
That's not the correct nbt for an enchantment. See this wiki on the correct tags:

https://minecraft.fandom.com/wiki/Tutorials/Command_NBT_tags

**Comment by DanRobzProbz** [comment]
Okay, thanks.
It might be worth updating the example in case others have the same issue.
:)
