### ISSUE TITLE
1.20.1 crash with spawn and villager doesnt work

### ISSUE THREAD

**Issue by jesuseduardo90** [McJty/InControl#412]
I guess is early stage or something because an example from the wiki doesnt work for me.

in file spawn.json

[
  {
    "mob": "minecraft:zombie",
    "result": "deny"
  }
]

the game or says "conection lost   server close"(SP)  or i got notenoughtcrashes when it crash.
using multiMC.

crash report:

[crash report.txt](https://github.com/McJtyMods/InControl/files/14074607/crash.report.txt)

also tried with "villager" but doesnt work. but i need further testing

**Comment by McJty** [comment]
Fixed in 9.2.1
