### ISSUE TITLE
Singleplayer world creation crash

### ISSUE THREAD

**Issue by Proxwian** [McJty/InControl#413]
[crash-2024-01-28_12.56.06-server.txt](https://github.com/McJtyMods/InControl/files/14075549/crash-2024-01-28_12.56.06-server.txt)

incontrol-1.20-9.2.0.jar

**Comment by Proxwian** [comment]
Also there's two incontrol-1.20-9.2.0.jar in CurseForge page
<img width="856" alt="image" src="https://github.com/McJtyMods/InControl/assets/31781674/109b3a98-3152-401e-aa29-6223fc284c0b">

**Comment by McJty** [comment]
This bug is fixed already in 9.2.1
