### ISSUE TITLE
1.20.1 Forge 47.2.7 Command Help

### ISSUE THREAD

**Issue by Krimatoria** [McJty/InControl#416]
![image](https://github.com/McJtyMods/InControl/assets/106809386/6a0d3114-b8a2-4a25-858a-c420a31e48a2)

Please help with the commands. I don't know English well and I didn't find any examples in your wiki for spawning mobs in a certain dimension, there is only about the ban and it concerns an individual mob, not the whole mod. 

I need to make it so that, for example, certain mobs and from the entire mod, spawn only in a certain dimension. 

Sons Of Sins
sons-of-sins-1.20.1-2.1.6.jar

For example, I have such a mod, I want mobs to spawn only in the Neher, how do I do this? And where will it need to be registered in spawner.json?

**Comment by McJty** [comment]
You can use the examples in the wiki to spawn in the overworld and just change the dimension. It's literally the same. Look for examples on spawner.json

**Comment by Krimatoria** [comment]
> Вы можете использовать примеры в вики, чтобы появиться в обычном мире и просто изменить измерение. Это буквально то же самое. Ищите примеры на spawner.json.

Which of these examples can I use?
![image](https://github.com/McJtyMods/InControl/assets/106809386/56eb3e45-5a56-4588-b331-d8e58573af72)

**Comment by McJty** [comment]
The last ones are all about spawner.json. I suggest you examine them all
