### ISSUE TITLE
Spawn.json is not working when used like this

### ISSUE THREAD

**Issue by Kettle5000** [McJty/InControl#417]
I tried to make mobs from those mods to only spawn in the lost cities dimension. 
I tried first to allow in lostcities:lostcity and deny
but it caused all mobs to not spawn at all which is weird
then i tried to do this and it didnt work at all, mobs from the first mod were able to spawn without any problem.
PD: im fully aware of how forge manages events spawning, so i tried to make a mod to fully remove them from spawning using the MobSpawnEvent.SpawnPlacementCheck and i was succeded in removing from spawning, not sure if this could clarify that the mobs from the flesh that hates follow normal spawning methods.
[spawn.json](https://github.com/McJtyMods/InControl/files/14671202/spawn.json)
I must also clarify that it works when the variable "when" is set to onjoin (probably because you get the entity itself directly), but other methods like "position" do not work at all

**Comment by McJty** [comment]
Yes some mods don't correctly fire all events. That's why you sometimes need to use onjoin. But that's not a bug in InControl. I don't understand the purpose of this ticket?

**Comment by Kettle5000** [comment]
I already tried to check myself if the event is fired and it is, so is not a problem with the mod im trying to change.
The code i tried was able to remove detect it 
but this mod doesnt seem to detect it 

Here is what i was able to achieve:

![image](https://github.com/McJtyMods/InControl/assets/93736713/a5610ab7-f13e-4fca-8131-c5593ff656a0)


so the method above works and removes the entity from spawning
what i dont get is why yours do not and it only happens when i try it the way i sended it in the json.
pd: yeah i didnt know how to check if the event is happening in a dimension so i managed to make it work with strings but works.
PD2: yeh i realized the code has a little problem but that is not the issue rn, still i would lovely appreciate if you show me how should i properly check for dimensions
This is for 1.20.1

**Comment by Kettle5000** [comment]
my bad
the mob spawns anyway just the sound glitches.
