### ISSUE TITLE
common_setup error

### ISSUE THREAD

**Issue by DatAshYK** [McJty/InControl#423]
![image](https://github.com/McJtyMods/InControl/assets/168969028/4a5250ce-2d72-42cd-97b1-c3c330c0b84c)
 ^ When I launch the game it gives me this error, I know what it means and where it comes from but I have no idea how to fix it.
![image](https://github.com/McJtyMods/InControl/assets/168969028/f58d6f3c-c63d-4827-81be-73d073a39b94)
^ This is from the crash log saying the error comes from the spawner file.
![image](https://github.com/McJtyMods/InControl/assets/168969028/02eead30-c515-46ad-9a12-d63e592edb00)
^ This is the spawner file, I was trying to make spawn vanilla cats anywhere like other mobs like sheeps etc would, what's wrong with it? I never used the spawner before.

**Comment by McJty** [comment]
You have a , too much after the dimension line

**Comment by DatAshYK** [comment]
> You have a , too much after the dimension line

what does that mean? It's either that I'm dumb, I know nothing about coding, or both-

**Comment by McJty** [comment]
Remove the comma after overworld
