### ISSUE TITLE
When the player moved about 1500 blocks away, the server crashed.

### ISSUE THREAD

**Issue by AngleNaris** [McJty/InControl#425]
This is crash report.
It seems to be related to "seesky" rule.
[https://logpaste.com/3xNqZDHt](https://logpaste.com/3xNqZDHt)

spawn.json

[
      {
        "hostile": true,
        "area": "spawn",
        "result": "deny"
      },
      {
        "hostile": true,
        "area": "safe",
        "incontrol": true,
        "when": "onjoin",
        "result": "deny"
      },
      {
        "spawner": true,
        "customevent": "addcreeper",
        "when": "onjoin",
        "result": "allow"
      },
      {
        "hostile": true,
        "dimension": "overworldmirror:overworld",
        "result":"deny"
      },
  
      {
        "dimension": "minecraft:overworld",
        "mob": "minecraft:skeleton",
        "mincount": 10,
        "result": "deny"
      },
      {
        "dimension": "minecraft:overworld",
        "hostile":true,
        "mincount": 300,
        "result": "deny"
      },
      {
        "dimension": "minecraft:the_nether",
        "incontrol": true,
        "mincount": {
          "amount": 30,
          "hostile": true,
          "perchunk": true
        },
        "result": "deny"
      },
      {
        "dimension": "minecraft:the_nether",
        "mob":"minecraft:zombified_piglin",
        "mincount": 40,
        "result": "deny"
      },
      {
        "dimension": "minecraft:overworld",
        "mod": ["creeperoverhaul","minecraft:creeper"],
        "mincount": 20,
        "result": "deny"
      },
      {
        "dimension": "minecraft:overworld",
        "mob": "minecraft:spider",
        "mincount": 10,
        "result": "deny"
      },
      {
        "dimension": "minecraft:overworld",
        "mob": "spore:acid_ball",
        "when": "onjoin",
        "mincount": 100,
        "result": "deny"
      },
      {
        "mob": "spore:hindenburg",
        "when": "onjoin",
        "result": "deny"
      },
      {
        "mob": "spore:proto",
        "when": "onjoin",
        "result": "deny"
      },
      
      {
        "mob": ["minecraft:zombie","spore:inf_human","minecraft:spider","minecraft:skeleton","minecraft:creeper"],
        "dimension": ["minecraft:overworld","twilightforest:twilight_forest"],
        "incontrol": true,
        "seesky":false,
        "result": "deny"
      },
      {
        "mob": ["minecraft:zombie","spore:inf_human","minecraft:spider","minecraft:skeleton","minecraft:creeper"],
        "dimension": ["minecraft:overworld","twilightforest:twilight_forest"],
        "incontrol": true,
        "mincount": {
          "amount": 15,
          "hostile": true,
          "perchunk": true
        },
        "result": "deny"
      },

      {
        "mob": ["minecraft:zombie","spore:inf_human","minecraft:spider","minecraft:skeleton","minecraft:creeper"],
        "dimension": "twilightforest:twilight_forest",
        "mincount": 100,
        "result": "deny"
      },

      {
        "dimension": ["minecraft:overworld","twilightforest:twilight_forest"],
        "mob": "minecraft:creeper",
        "mincount": 100,
        "result": "deny"
      },

     
      {
        "mob": ["spore:tendril","spore:mound"],
        "when": "onjoin",
        "area": "none",
        "result": "deny"
      },
      {
        "mob": ["spore:tendril","spore:mound"],
        "when": "onjoin",
        "result": "deny"
      },
 {
        "mob": ["spore:tendril","spore:mound"],
        "when": "onjoin",
        "seesky":false,
        "result": "deny"
      },
      {
        "mob": ["alexsmobs:farseer"],
        "when": "onjoin",
        "result": "deny"
      },
      {
        "mob":"alexsmobs:crimson_mosquito",
        "mincount":2,
        "result":"deny"
      }
]

**Comment by AngleNaris** [comment]
The terrain with a range of 1500 blocks was pre-generated before.

**Comment by McJty** [comment]
Can you update to the latest version and try again? I need to see the log with that version if it still crashes

**Comment by AngleNaris** [comment]
No problem, I will try.
