### ISSUE TITLE
JSON error when using the new "hasstructure" boolean

### ISSUE THREAD

**Issue by lozadajobd** [McJty/InControl#427]
I am currently trying to use In Control! To make mobs only spawn underground. However, I would also like to make mobs spawn in structures that are above ground like Woodland Mansions and Pillager Outposts. 

To accomplish this, I tried using the "hasstructure" boolean like this in spawn.json:
![image](https://github.com/McJtyMods/InControl/assets/68721231/66c7d9ad-ed72-4e48-b0aa-81f6eb84611a)

However, this always results in this error:
![image](https://github.com/McJtyMods/InControl/assets/68721231/737e8fd0-4471-410e-93a5-c5342e65ce4e)

I'm not experienced in java or javascript, so I cannot comment on what this means. However, it seems that I may be using an incompatible data type in the "hasstructure" condition. However, the wiki clearly states that it is a boolean, and I have tried using an array list of structure tags only to get the same error. 

I could also confirm that "hasstructure" is the source of the issue because upon deleting it from the code, the config is able to compile without errors.

Attached here is the full spawn.json file for reference
[spawn.json](https://github.com/McJtyMods/InControl/files/15445775/spawn.json)

**Comment by McJty** [comment]
Sorry for the slow response but should be fixed in the next release
