### ISSUE TITLE
Feature request: custom NBT

### ISSUE THREAD

**Issue by Efimero** [McJty/InControl#43]
Add an option to attach custom NBT to a spawned mob directly, the way the /summon command does, that way we can spawn much more customized mobs and also markers (invisible armor stands) that other commands could execute on to trigger other events (for example, a structure clone for growing a custom tree?).
Generalizing to NBT should be fairly easy and open great potential, while the rest of the system can be kept for a more standard, sensible, easy use.

**Comment by McJty** [comment]
Implemented in next release (3.6.5)
