### ISSUE TITLE
InControl Not working? Bats still over spawn.

### ISSUE THREAD

**Issue by alarmgoose** [McJty/InControl#432]
I'm assuming that I am doing something wrong. I'm trying to make minecraft:bat spawn no more then 5. Here is what is in my .json

{
    "mob": "minecraft:bat",
    "mincount": 5,
    "result": "deny"
}

I placed this in the spawn.json but when I go into game, there are 16 bats in the area. I teleported to them just to be sure, using the mod observable. 

What am I doing wrong?

**Comment by McJty** [comment]
What version?

**Comment by alarmgoose** [comment]
1.20.1

**Comment by McJty** [comment]
Add "when": "onjoin" to the rule

**Comment by alarmgoose** [comment]
Oh and  I used a command to kill all bats, but they instantly respawned to similar numbers. and where do I had the when on join ? anywhere?

**Comment by McJty** [comment]
Anywhere in the rule

**Comment by alarmgoose** [comment]
okay let me give it a try. I'll post back the results in a few mins. Thank you for the quick reply!

**Comment by alarmgoose** [comment]
That worked perfectly! Are there any other things that I should know?  I plan on restricting more mobs from different mods so I'm assuming to use that phrase on them all right? 
And thank you again!

**Comment by McJty** [comment]
You can do it all in one rule by using the list syntax:

"mob": ["minecraft:bat", "othermod:monster", ...],

**Comment by alarmgoose** [comment]
... THANK YOU! I appreciate you answering so fast too. =D
