### ISSUE TITLE
Error with `hasstructure` field in 1.19.2.

### ISSUE THREAD

**Issue by kaisadilla** [McJty/InControl#437]
Hi! I'm learning InControl, so this may perfectly be my fault. I have this small test snippet in spawn.json

`[
    {
        "incontrol": true,
        "seesky": true,
        "armorhelmet": ["minecraft:iron_helmet", "minecraft:golden_helmet"],
        "result": "allow"
    },
    {
        "incontrol": false,
        "hasstructure": false,
        "result": "deny"
    }
]`

This gives me an error in console that says `InControlError: Invalid Keywords for spawn.json: hasstructure`.

I'm using InControl 1.19-7.1.15 for Minecraft 1.19.2.

**Comment by McJty** [comment]
I found out the problem and will fix it in the next release (later today)
