### ISSUE TITLE
[Feature Request] Modify experience drop amounts

### ISSUE THREAD

**Issue by Dragnier** [McJty/InControl#44]
It would be awesome if we could modify xp values as well as loot for all mobs; both individually and as groups.

Examples: 

- Specifying that all passive mobs no longer drop exp.
- Setting individual hostile mob exp drops to adjust level gaining/progression/farming.
- Having an AdditionalExp option to go along with other settings like damageadd in spawn.json.

**Comment by McJty** [comment]
Already implemented in a recent update
