### ISSUE TITLE
Changing the chance of spawning mobs from a certain mod

### ISSUE THREAD

**Issue by Killer-xz** [McJty/InControl#443]
Hello dear developer, I don't know if you remember me or not, but I'm the person who wrote to you asking for help to make a code to reduce the chance of spawning mobs.
So, I abandoned it for a long time because I gave up and spent a lot of time trying to figure it all out, today I decided to come back.
But I'm having a problem in the code again, I've read your wiki, watched almost every possible guide on YouTube, and still I'm getting some kind of error flying out.
Please help me to fix my code, I will be very grateful.

_Version 1.16.5_

Code:
`[
  {
    "dimension": 0,
    "mob": [
      {
        "mob": "kimetsunoyaiba:kokushibo",
        "weight": 10,
        "mingroupcount": 1,
        "maxgroupcount": 1
      }
    ]
  }
]`

**Comment by McJty** [comment]
"dimension": 0 is not a valid dimension. You are looking at the wrong wiki. The dimension is something like "minecraft:overworld".

Also what file did you put that in?

You are also mixing things. If you want to put that in spawn.json then you shouldn't use weight, mingroupcount, etc because those are for spawner.json

**Comment by Killer-xz** [comment]
I put it all in spawn.json, it turns out to change the chance of spawning a mob, you need to write it all in spawner.json?

**Comment by McJty** [comment]
See the wiki for syntax. spawner.json and spawn.json work differently. There are examples on the wiki for both.

If you want to REDUCE spawns you have to do that in spawn.json
If you want to ADD spawns you have to do that in spawner.json (but with totally different syntax)

**Comment by Killer-xz** [comment]
Ok, I get your point, but I'm a little unclear in terms of adding and reducing appearances, for example I have a situation where I need to reduce appearances not in chunk, but in terms of chance of appearance to make a strong mob more rare, in this case I don't understand where I should write

**Comment by McJty** [comment]
If it is 'reduce' then it is spawn.json. It's as simple as that

**Comment by Killer-xz** [comment]
Ok then what conditions should I use in spawn.json to reduce the chance of spawning mobs, you said I don't need to use weight etc in spawn.json

**Comment by McJty** [comment]
There are various possible conditions. It all depends on what you need:
- minlight/maxlight (base on light)
- mincount/maxcount (base on amount of mobs)
- seesky

The wiki has a list and also lots of examples. Also I recommend my discord (link on wiki). It's easier to help there

**Comment by Killer-xz** [comment]
Хорошо, попробую сегодня, и также зайду в Дискорд, спасибо вам, а ещё скажите пожалуйста куда вам писать за помощью в Дискорд

**Comment by Killer-xz** [comment]
Ok, I will try it today and I will also go to Discord, thank you, and also please tell me where to write to you for help in Discord

**Comment by McJty** [comment]
Just go to my channel. There is an incontrol room

**Comment by Killer-xz** [comment]
Ok, thanks
