### ISSUE TITLE
trying to deny all scape and run mobs from spawning in overworld

### ISSUE THREAD

**Issue by Virieas** [McJty/InControl#445]
[
  'onjoin': true
  {
    "dimension": 0,
    "mob": "srparasites",
    "result": "deny"
  }
]

**Comment by McJty** [comment]
There are several things wrong with tihs. First, what is onjoin: true doing outside your rule? It should go inside the {}.
Secondly "srparasites" is not a mob. That's a mod. So you use "mod"

**Comment by Virieas** [comment]
alright ty

**Comment by Virieas** [comment]
ive rewriten it, but now im wondering if this will despawn the parasites as well? that's what im looking for

[
  {
    "onjoion": true,
    "dimension": 0,
    "mod": "srparasites",
    "result": "remove"
  }
]

**Comment by McJty** [comment]
It's 'onjoin'. Not what you wrote.

Also why did you change "deny" to "remove"? That doesn't work

Already spawned mobs are not affected by this
