### ISSUE TITLE
I think anything put in loot.json is crashing the game

### ISSUE THREAD

**Issue by IdkWhatNameThingyToPut** [McJty/InControl#447]
[crash-2024-09-27_16.45.23-client.txt](https://github.com/user-attachments/files/17160208/crash-2024-09-27_16.45.23-client.txt)
Minecraft modded version is 1.12.2 

I was trying my own stuff and getting crashes over and over again, I ended up creating and trying to get things to work on a mini test modpack with very few mods installed and still it was crashing every time, and so I ended up trying your own examples from your wiki and it's still crashing every time on launch. I genuinely think this feature is broken right now. and hoping it can get fixed soon.

[
  {
    "mob": "minecraft:blaze",
    "remove": "minecraft:blaze_rod"
  },
  {
    "mob": "minecraft:blaze",
    "structure": "Fortress",
    "player": true,
    "item": "minecraft:blaze_rod",
    "itemcount": "2-3/3-4/4-6"
  }
]

**Comment by McJty** [comment]
It's crashing because of a problem in spawn.json. Not in loot.json

**Comment by IdkWhatNameThingyToPut** [comment]
Ohh ahahah omg.. so umm the spawn.json and potentialspawn.json are empty but that is the problem, they're literally empty and I've even cleared out the brackets [] accidently. I think I was testing stuff earlier in those other files and had some problems getting things to work that's why I cleared them but I cleared a little too much it seems

Sorry ahahah anyway I love this mod omgg 

You can close this if you want it seems fixed now thank you so much
