### ISSUE TITLE
Control validator confusion

### ISSUE THREAD

**Issue by wExtraBenji** [McJty/InControl#454]
I've been trying to get my incontrol spawn file to work, so I put it through the control validator on the wiki (edit: I'm sorry I saw the source code link at the bottom after writing this :C )
### What I put in was:
[
 {
  "mod": "ars_nouveau",
  "result": "default"
 },
 {
  "mod": "minecraft",
  "hostile": true,
  "mincount": {
   "mod": "minecraft",
   "hostile": true,
   "amount": 15
   },
  "result": "deny"
 },
 {
  "mob": "quark:foxhound",
  "mincount": {
   "amount": 2,
   "perchunk": true
   },
  "result": "deny"
 }
]

### What I got out was:
[
  {
    "result": "default",
    "mod": "ars_nouveau"
  },
  {
    "result": "deny",
    "mod": "minecraft",
    "hostile": true,
    "mincount": {
      "amount": 15,
      "mod": "minecraft",
      "hostile": true
    }
  },
  {
    "result": "deny",
    "mob": "quark:foxhound",
    "mincount": {
      "amount": 2,
      "perchunk": true
    }
  }
]

When I used this, absolutely nothing hostile nor foxhounds spawned. Was wondering if this is a control validator issue or a me skill issue lol.

**Comment by McJty** [comment]
The validator just checks that your json looks ok. It doesn't actually check that the rules are correct because it has no way to know what you actually want to achieve. Does the foxhound spawn naturally? i.e. if you didn't have this spawn.json, would the foxhoud spawn?
