### ISSUE TITLE
Problem defining Areas with negative coordinate values

### ISSUE THREAD

**Issue by LordMoucho** [McJty/InControl#455]
I’m having trouble defining areas in the areas.json file for the inControl mod in Minecraft. When an area is entirely defined with negative coordinates, the system doesn’t seem to detect it properly. I have two areas set up in the JSON file:

An area named "spn" with coordinates in the negative quadrant.
An area named "test" with coordinates in the positive quadrant.
When I run the incontrol area command while the player is within the "test" area, the system detects it correctly and returns the area’s name. However, when I place the player in the "spn" area, the system doesn’t detect the area, and the command doesn’t return its name.

`[
  {
    "dimension": "minecraft:overworld",
    "name": "spn",
    "type": "box",
    "x": -684,
    "y": 103,
    "z": 606,
    "dimx": -649,
    "dimy": 94,
    "dimz": 597
  },
  {
    "dimension": "minecraft:overworld",
    "name": "test",
    "type": "box",
    "x": 0,
    "y": 80,
    "z": 0,
    "dimx": 90,
    "dimy": 100,
    "dimz": 90
  }
]
`

**Comment by McJty** [comment]
A dimension can never be negative. i.e. what do you expect to happen with "dimx" equal to -649? The dim parameters are the size of the area. A size cannot be negative

**Comment by LordMoucho** [comment]
Touche… 😅
but I suggest to clarify it in the wiki for people like me thinking second coordinate isn’t a size but the second opposite corner of te box area.

thanks for your help ❤️

**Comment by GenericJoe** [comment]
Just wanna chime in that i was also having trouble knowing what dimx did, my first thought is that it was just the secondary set of coordinates. spent like an hour digging till i found this ticket. if there could be some more details in the wiki about what you can put in the areas.json file and what those terms mean, that would be awesome.

**Comment by McJty** [comment]
I don't understand the confusion. The name clearly says 'dimx'. That 'dim' stands for dimension. That's a size. But I can clarify it in the documentation. That's no problem
