### ISSUE TITLE
Mobs spawning more than spawn cap

### ISSUE THREAD

**Issue by IdkWhatNameThingyToPut** [McJty/InControl#456]
Hello I'm really confused right now mobs seem to be spawning more than the spawn cap which I've tried to set to 1 with "mincount", at first I thought everything was working fine but once adding in "seesky": true, I could see a lot more spawning in. Not sure if it's bugged or if I'm doing something wrong? Maybe they were spawning heaps in caves below me the whole time and once adding in "seesky": true, it showed that they were spawning heaps because they couldn't spawn a lot in caves anymore? Could I please have some help with this I don't know if I'm doing something wrong or not.

Also this is on minecraft modded 1.12.2

This is what's in PotentialSpawn.json:
[
  {
     "dimension": 0,
      "biometype": ["WARM", "COLD", "FOREST", "JUNGLE", "BEACH", "SNOWY", "SAVANNA", "SPARSE", "MOUNTAIN", "SWAMP", "CONIFEROUS", "HOT", "SPOOKY", "RARE", "MESA", "DRY", "HILLS", "MUSHROOM", "PLAINS", "DEAD", "LUSH", "WASTELAND", "MAGICAL", "TWILIGHT", "NETHER"],
      "mobs": [
          {
            "mob": "ancientbeasts:giant_zombie",
            "weight": 30,
            "groupcountmin": 1,
            "groupcountmax": 2
          }
      ]
  },
  {
     "dimension": 0,
      "biometype": ["WARM", "COLD", "FOREST", "JUNGLE", "BEACH", "SNOWY", "SAVANNA", "SPARSE", "MOUNTAIN", "SWAMP", "CONIFEROUS", "HOT", "SPOOKY", "RARE", "MESA", "DRY", "HILLS", "MUSHROOM", "PLAINS", "DEAD", "LUSH", "WASTELAND", "MAGICAL", "TWILIGHT", "NETHER"],
      "mobs": [
          {
            "mob": "mutantbeasts:mutant_creeper",
            "weight": 30,
            "groupcountmin": 1,
            "groupcountmax": 2
          }
      ]
  }
]

This is what's in Spawn.json:

[
  {
    "mob": "mutantbeasts:mutant_creeper",
    "mincount": {
       "amount": 1
    },
    "result": "deny"
  },
  {
    "mob": "ancientbeasts:giant_zombie",
    "onjoin": true,
    "seesky": true,
    "mincount": {
       "amount": 1
    },
    "result": "deny"
   }
]

**Comment by IdkWhatNameThingyToPut** [comment]
Also the ancientbeasts:giant_zombie is the mob that I'm talking about spawning more than the spawn cap I haven't tested the creeper one fully yet just so you know.

**Comment by McJty** [comment]
It's because you are combining conditions. The giant_zombie rule in spawn.json only succeeds (and denies the spawn) if seesky is true AND mincount is 1. That means that if seesky is not true (like underground) there is no more limit. You need to split the rules

**Comment by IdkWhatNameThingyToPut** [comment]
Sorry but I'm still a little lost I really wish you wouldn't just assume I know where to go from here and close stuff I don't mean to be rude but the reality is I'm still confused and honestly I also want to make sure I'm doing this right because I've tried by myself already that's why I'm here for help in the first place. I really don't wanna argue or anything but if you could please help me get this figured out that would be amazing I hope you can understand.

I can't find a single example on your wiki (atleast on the 1.12.2 page) of you using both mincount and seesky together. I'm just really confused right now and I also want to learn because I do like this mod. So you can't use 2 conditions together in the same rule? Or at all? I don't see it stated anywhere on the wiki either or atleast anything about seesky and mincount not being able to be used together in the same rule?

Are you saying I need to do two different rules for the same mob? Is this correct:

[
{
"mob": "ancientbeasts:giant_zombie",
"onjoin": true,
"mincount": {
"amount": 1
},
"result": "deny"
},
{
"mob": "ancientbeasts:giant_zombie",
"onjoin": true,
"seesky": true,
},
"result": "deny"
}
]

**Comment by IdkWhatNameThingyToPut** [comment]
Expanding on that too can minheight be used with mincount in the same rule or does that also a completely different rule for the same mob if I was ever to use it? Just trying to learn sorry

**Comment by McJty** [comment]
What you did there is almost correct. Just need to remove the extra }, that you have after the seesky true line

**Comment by IdkWhatNameThingyToPut** [comment]
Oh yeah that was a typo but thank you so much for getting back to me really appreciate it. It was just extra hard because not only could I not find examples on the wiki but also on google so that's why I came here because at the end of the day who better to ask then the actual dev who made the mod. Anyway thank you so much. Hope you have a good day I'll let you know here if I have any problems with stuff.
