### ISSUE TITLE
Curseforge upload issue

### ISSUE THREAD

**Issue by uhloin** [McJty/InControl#459]
Please, mark your uploaded .jar-s with some loader type (Forge, Neoforge) or else it's impossible to make right decision for update.

For example for this version it's impossible to understand is it for Forge or NeoForge,:

https://www.curseforge.com/minecraft/mc-mods/in-control/files/5927393

It is not shown in this filter:

https://www.curseforge.com/minecraft/mc-mods/in-control/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=6

**Comment by McJty** [comment]
Oops. I always forget. My automated script doesn't support NeoForge yet. Fixed it now
