### ISSUE TITLE
1.20.1. Spawner.json seemingly ignoring Spawn.json rules

### ISSUE THREAD

**Issue by DiddlyDongo** [McJty/InControl#461]
I’m playing in a modded Minecraft 1.20 version and there are certain mobs from within the mod that I’m trying to limit to certain biomes for theming purposes. My spawner.json seems to be working as intended in accordance to what I saw in the guide, resulting with the mobs I’ve chosen spawning within the nether. However. When I try to outline the rules for the spawner.json to follow through spawn.json. It seems to just ignore the commands I try putting in and makes them spawn in all nether biomes. The only command that seemed to have actually worked was preventing some mobs from spawning in the overworld as some of them used to do naturally.

For reference this is the code I have in spawn currently

`[
     {
        “mob”:[“realmrpg_wyrms:red_wyrm”],
        “dimension”: “minecraft:nether”,
        “biome”:[“biomesoplenty:erupting_inferno] 
         “result”: “default”
       },
      { 
        “mob”:[“realmrpg_creep:creepling”,”realmrpg_creep:halloweed”],
        ”dimension”: “minecraft:nether”,
        “biome”: [“biomesoplenty:undergrowth”],
        ”result”: “allow”
        },
       {
        “mob”:[“realmrpg_wyrms:red_wyrm”,“realmrpg_creep:creepling”,”realmrpg_creep:halloweed”]
         “dimension”: “minecraft:nether”,
         “when”:”onjoin”
         “result”:”deny”
       },
      {
        “mob”:[“realmrpg_creep:creepling”,”realmrpg_creep:halloweed”],
        ”dimension”:”minecraft:overworld”
        “when”:”onjoin”
        ”result”: “deny”
]’

Please let me know what else I can do. I’ve been trying to figure this out and it’s frustrating.

**Comment by McJty** [comment]
It's minecraft:the_nether (you forgot 'the_')

**Comment by DiddlyDongo** [comment]
Big thanks!
