### ISSUE TITLE
I want the mob spawner block to not be affected by the InControl rules

### ISSUE THREAD

**Issue by JulioAlvarez15** [McJty/InControl#463]
So, in some underground structures where there are zombie spawners it doesn't spawn almost anything. I know that seesky at spawn.json has something to do, but honestly I wanna keep that so zombies spawn more naturally above. So, I wanna have zombies that spawn at the overworld naturally and more than in caves, but also normal zombie spawns on underground structures with zombie spawners. There is any way to do it?

spawner.json
[
    {
      "mob": "minecraft:zombie",
      "persecond": 0.5,
      "attempts": 20,
      "amount": {
        "minimum": 2,
        "maximum": 4
      },
      "conditions": {
        "dimension": "minecraft:overworld",
        "norestrictions": true,
        "mindist": 30,
        "maxdist": 100,
        "minheight": 15,
        "maxheight": 256,
        "maxthis": 80
      }
    }
  ]
  
  spawn.json
  [
    {
      "mob": "minecraft:zombie",
      "seesky": true,
      "when": "onjoin",
      "result": "default"
    },
    {
      "mob": "minecraft:zombie",
      "result": "allow",
      "phase": "nighttime",
      "speedmultiply": 1.2
    },
    {
      "hostile": true,
      "result": "allow",
      "phase": "nighttime",
      "speedmultiply": 1.2
    }
  ]

**Comment by McJty** [comment]
If you don't want spawners to be affected then don't use "when": "onjoin"

**Comment by JulioAlvarez15** [comment]
It works, thx!
