### ISSUE TITLE
[Question spawner.json]

### ISSUE THREAD

**Issue by cokolada46** [McJty/InControl#468]
Persecond runs a probability every second
And a limit is between 1 and 0
Example persecond 0.01 will on average fire every 100 seconds.

My question is are there limits how many zeros i can add and do you have it limited in the mod, if i want it to fire for example every half an hour or more
can i add multiple zeros like this;
persecond 0.00002

I

**Comment by McJty** [comment]
There is a limit but I don't really know where. I guess you'll have to try

**Comment by cokolada46** [comment]
In java float has precision limit that can store up to 7 digits past zero
0.0000001 
And double can store up to 15 digits
0.000000000000001

So if you used float for persecond and didn't change anything i guess this is answer to my question
