### ISSUE TITLE
First time trying to setup custom spawns...

### ISSUE THREAD

**Issue by vico93** [McJty/InControl#48]
...and i cant figure out what i'm doing wrong.

Using [this](https://gist.github.com/vpontin/e22f9a2eb3967f961bdf7c778cb41f5b) potentialspawn.json to make parrots and ocelots to spawn in other biomes beyond jungle.

Minecraft 1.12.2, Forge 14.23.1.2600 and incontrol-1.12-3.6.5

**Comment by Lucasterio** [comment]
You're not doing the "Mobs" block:
{
    "dimension": 0,
	"mob": "minecraft:ocelot",
	"biome": [biomes]
	"maxcount": "10,minecraft:ocelot",
    "mobs": [
      {
        "mob": "minecraft:ocelot",
        "weight": 5,
        "groupcountmin": 1,
        "groupcountmax": 2
      }
    ]
  },

I recommend to put a maxcount ALWAYS, otherwise they might spawn to death....

**Comment by vico93** [comment]
Thanks for the help!
