### ISSUE TITLE
Mod order issue when validating mobs

### ISSUE THREAD

**Issue by badmonkey** [McJty/InControl#5]
Looks like there is an issue with validating mobs from the configuration file when InControl starts.

InControl fails to find mobs from primitivemobs (or mobs from any jar alphabetically after "I"). When I rename the primitivemobs jar file to  "aprimitivemobs" (and so will load before InControl) they are then correctly found.

**Comment by McJty** [comment]
Oh good catch. I'll have to think about how to solve that

**Comment by McJty** [comment]
Fixed next release
