### ISSUE TITLE
[Suggestion] Spawn Control using Ore Dictionary

### ISSUE THREAD

**Issue by SSyl** [McJty/InControl#51]
It would be useful if you could control where mobs are able to spawn based on ore dictionary entries.

For example, if I wanted to stop a mob from spawning on wood logs, I'd currently have to add every single wood log block as a rule in spawn.json. So something like this:
```

[
  {
    "mob": "minecraft:creeper",
    "block": ["minecraft:log", "minecraft:log2", "biomesoplenty:log_0", "biomesoplenty:log_1", "natura:overworld_logs", etc...],
    "result": "deny"
  }
]
```

And that's not including all the metadata for each log under each of those entries as well. It would be helpful if I could do something like this instead:

```
[
  {
    "mob": "minecraft:creeper",
    "block": "ore:logWood",
    "result": "deny"
  }
]
```

**Comment by McJty** [comment]
Implemented in the next release
