### ISSUE TITLE
In control wont work 

### ISSUE THREAD

**Issue by SmallEnderman** [McJty/InControl#54]
So i've adde zombie awareness to make my modpack a little bit more hardcore... but then i noticed that zombie were able to spawn from water (which was what i didnt want) and i thought i could fix that with In control. So i've set it towhere zombie dont spawn in water (aswell as less zombies) but then it just keeps crashing. can someone help me?

here's the crash report https://pastebin.com/DBqLu7Kx

**Comment by McJty** [comment]
Your json is wrong. Can you also paste the full json here?

**Comment by SmallEnderman** [comment]
sure
From spawn i assume?

**Comment by SmallEnderman** [comment]
https://pastebin.com/jEgwcJiz
This one is from spawn.json

**Comment by McJty** [comment]
"block": minecraft:water,

This is missing quotes. Should be:

  "block":"minecraft:water",

**Comment by SmallEnderman** [comment]
Okay so the game works again... but the zombie wont despawn from the water (they still keep raising from the ground)

**Comment by McJty** [comment]
What? Why would they despawn? What exactly is the problem? spawn.json only prevents new spawn. Doesn't do anything about mobs that have already spawned

**Comment by SmallEnderman** [comment]
(srry i wrote it wrong) They keep spawning in water. But i've no idea why
Do you think this might be because of ZombieAwareness mod?

**Comment by SmallEnderman** [comment]
So how can i make it towhere the zombies dont spawn on water anymore?

**Comment by McJty** [comment]
Well why are they spawning there in the first place? Probably a mod is placing them there and bypassing the normal rules. In that case there is not much that I can do about it

**Comment by SmallEnderman** [comment]
okay imma check which mod causes it

**Comment by SmallEnderman** [comment]
I've found out that zombieAwareness allows zombie to raise from water and i assume he kinda recoded that. If i wanted it towhere modded zombies (such as the ZombieAwareness... zombie) to not spawn on water, how would i do that

**Comment by McJty** [comment]
Do the zombies still spawn if you have a rule like this in spawn.json:

[
  {
    "mob": "Zombie",
    "result": "deny"
  }
]

**Comment by SmallEnderman** [comment]
they still spawn

**Comment by McJty** [comment]
Then ZombieAwareness does something weird/wrong (i.e. not firing the spawn event) and then there is nothing In Control can do about it. Report to Zombie Awareness

**Comment by SmallEnderman** [comment]
okay thanks
