### ISSUE TITLE
Removing Item from mobs Loot

### ISSUE THREAD

**Issue by LokyLive** [McJty/InControl#55]
Forge version: 14.23.2.2629
incontrol! version: 1.12-3.7.1

[spawn.json](https://hastebin.com/koyumadede.json)
[loot.json](https://hastebin.com/mojocodexe.json)

I'm using PrimalCore 1.12.2-0.6.41 for my armored zombie . They wear their armor but they still drop them...

//////////////////////////

Questions 

Could you give me an example of "helditem" with metadata and NBT ? (maybe i make something wrong but it won't work when i've tryed)

Could you tell me how to change "helditem" for offhand ? Is it possible ?

**Comment by McJty** [comment]
From the wiki:

Note, everywhere in the rules below that you can specify items you can use the following notations:

minecraft:sand (just normal minecraft sand)
minecraft:stained_hardened_clay@13 (adds metadata 13)
With NBT (same format as for /give command): minecraft:stained_hardened_clay@13/{display:{Lore:[\"My Clay\"]}}
