### ISSUE TITLE
[Sevtech Ages] Looting enchantment does not apply to certain mob drops

### ISSUE THREAD

**Issue by TWJedi** [McJty/InControl#57]
Playing in Sevtech Ages, I noticed that the Looting enchantment does not apply to Blazes, Endermen, and Enderminies. I have a Looting 5 Astral Sorcery sword, and those three mobs never drop more than 1 of their respective drops (Blaze Powder, Ender Dust). As far as I can see, all other mobs have normal drops with Looting.

I brought this up to Darkosto and he referred me to this mod.

Minecraft 1.12.2
InControl 3.7.1
Forge 14.23.2.2638
Java 8.161
Sevtech 3.0.4

**Comment by McJty** [comment]
There will be a new tag that you can use in loot.json in the next version ('itemcount')
