### ISSUE TITLE
spawn json nbt syntax

### ISSUE THREAD

**Issue by Boolyman** [McJty/InControl#58]
According to the wiki it should be possible to specify nbt data in the spawn.json but I am having trouble figuring out what syntax is acceptable.  I'm simply trying to change the name on the mobs that spawn.

{
    "dimension": 0,
   "mob": "animalium:bear",  
   "nbt": "{CustomName:<trialname>}"
  },

**Comment by McJty** [comment]
Do it like in the example here:

https://wiki.mcjty.eu/mods/index.php?title=InControl

i.e. just include the nbt as regular json. Don't put it in a string

**Comment by Boolyman** [comment]
I don't see anything on the wiki to let us know how meta data on a loot item should work.  Is it just placed in the string like:
"item": "minecraft:wool:10"

or does it have a seperate tag like:

"item": "minecraft:wool",
"meta": 10

**Comment by McJty** [comment]
The wiki says this:

Note, everywhere in the rules below that you can specify items you can use the following notations:

minecraft:sand (just normal minecraft sand)
minecraft:stained_hardened_clay@13 (adds metadata 13)
With NBT (same format as for /give command): minecraft:stained_hardened_clay@13/{display:{Lore:[\"My Clay\"]}}

**Comment by Boolyman** [comment]
I apologize.  I can't stand people that don't use the available reference material, and now I am one of them.  I coulda swore I looked thoroughly and did not see info on meta.
