### ISSUE TITLE
1.12 conflict with NetherEx mod

### ISSUE THREAD

**Issue by Zygus42** [McJty/InControl#62]
incontrol-1.12-3.8.0
NetherEx-1.12-2.1.13.14
forge-1.12.2-14.23.4.2703-installer-win

The concept was to let all mods handle their own spawn, except where I didn't like what they were doing or it was inappropriate to the dimensons I'm using, but I'm getting no spawn allowed in the Nether (dim -1), not even from spawners like the Blaze spawners in the Nether Fortresses or vanilla mobs like Pigmen.

If I remove either InControl or NetherEx or both, mobs spawn just fine in the Nether.

This is my config file (the only one and converted to a txt file to attach here):
[spawn.json.txt](https://github.com/McJtyMods/InControl/files/2042308/spawn.json.txt)

It does not have a single reference to the Nether, any Nether biomes, dim -1 or the mod NetherEx.

I did try adding this to the start of the file, but made no difference:
{
     "mod": ["netherex"],
     "dimension": [-1],
     "result": "allow"
},

All other spawning in all other dimension appears to be just as specified.

**Comment by LogicTechCorp** [comment]
This is an issue with how NEX reads the biome config. See MineEx/NetherEx#82. I hope to have it fixed for the next update which is a big rewrite/restructuring of the mod.
