### ISSUE TITLE
Mobs spawn on world gen

### ISSUE THREAD

**Issue by MickyMeowse** [McJty/InControl#65]
I'm trying to get rid of most passive mobs but not all. When I put this in, it stops them from spawning in on already loaded chucks. Newly generated chucks spawn all these Mobs still. Any help would be great! Sorry for bad English. 
[
  {
    "mob": ["Sheep", "Chicken", "Horse", "Cow", "Pig", "Bat", "Donkey", "Rabbit"],
    "result": "deny"
  }

]

**Comment by McJty** [comment]
From the documentation:

https://wiki.mcjty.eu/mods/index.php?title=InControl#Spawn_Control

Use the 'onjoin' tag
