### ISSUE TITLE
[Feature Request] Gamestage support for mob spawns and modifiers/armor

### ISSUE THREAD

**Issue by SeriousCreeper** [McJty/InControl#68]
Would it be possible to get gamestage support to control which mobs spawn at a specific stage, including what damage/health/speed modifiers, armor they wear, etc?

**Comment by McJty** [comment]
GameStage support is already present

**Comment by SeriousCreeper** [comment]
Oh but isn't it for the loot table only right now? Unless the wiki is not up to date (was checking this one https://wiki.mcjty.eu/mods/index.php?title=InControl). 

How would one use gamestages for different rules for armor and such then? Just add the "gamestage" property to the rule?

**Comment by McJty** [comment]
Quote:
'This is similar to loot control except that it controls how much experience you get from killing a mob. All keywords from loot control can be used here except the ones that are about damage type (magic, explosion, ...) as that information is not present in this event. There are four outputs that work for these rules:'

There is a typo here but what this means is that you can use everything. And yes. Just use 'gamestage'

**Comment by SeriousCreeper** [comment]
Ahh my bad then! I thought that line only applied to the "Experience" settings. Thanks, will give it a try!
