### ISSUE TITLE
Not able to remove squids from specific biomes

### ISSUE THREAD

**Issue by Y0ungSandwich** [McJty/InControl#69]
Maybe I'm doing something wrong but my entry for potential spawns is:
    {
    "dimension": 0,
    "block": [
      "minecraft:water"
    ],
	"biome": [
	  "Ocean",
	  "Deep Ocean"
	],
    "mobs": [
      {
        "mob": "Squid",
        "weight": 1,
        "groupcountmin": 2,
        "groupcountmax": 6
      }
    ]
  }

But squid keep spawning in rivers and other ares.
I have piranhas spawning in rivers and they kill all the squid but Id like to avoid the mob drops from piling up.

**Comment by taramul** [comment]
Do you have a rule which specifically blocks squids in rivers and other areas? What you have posted here basically says "squids may also spawn in ocean and deep ocean", not "squids may not spawn anywhere but ocean and deep ocean". 

To get rid of squids anywhere but ocean and deep ocean, have this in your **spawn.json**:

```
[ 
 { "dimension":0,
   "biome":["Ocean","DeepOcean"],
   "mob": "Squid",
   "result": "allow"},
 { "mob": "Squid",
   "result":"deny"}
] 
```

The first rule allows squid in Overworld's oceans and deepoceans, the second bans them from everywhere else. 

By the way, how did you get the piranhas? Are these from Mo'Creatures?

**Comment by Y0ungSandwich** [comment]
I use animalium for the Piranhas. They are pretty nasty. Thanks!!

So I just need this in spawns.json. Do I need anything in potential spawns?

**Comment by taramul** [comment]
I don't think so, no. It definitely works for me with those two rules in spawn.json and nothing else in either file.

As far as I can tell, you add rules in potentialspawn.json if you are trying to add a mob to a biome where it isn't already able to spawn, or when you want to modify the mobs being spawned in some way.

**Comment by Y0ungSandwich** [comment]
Worked perfect thanks!

**Comment by Y0ungSandwich** [comment]
@taramul Maybe you could assist with one more? XD 

Again with Squid and Piranha spawns. If I do the above for both mobs in their respective biomes I get hundreds of each mob spawning in a very small area which quickly crashes the game out. Whats the best was to avoid such aggressive spawning? I'm on the wiki but setting weight doesn't seem to help at all.

**Comment by taramul** [comment]
You can define a maximum for spawning of specific mobs, in potentialspawn.json. 
See the example in the wiki about "iron golems in villages with a maximum of three".
I'm not sure how that works exactly, i.e. if the maximum is calculated for the respective biome, or per player, or overall for all mobs currently spawned, I haven't experimented too much with it. I had similar problems though and I managed to fix it this way.
