### ISSUE TITLE
Mob Spawning GameStages support

### ISSUE THREAD

**Issue by GamertechAU** [McJty/InControl#76]
Currently using MobStages to control when specific mobs can spawn, but any mobs I change using InControl ignore the rules and can spawn normally.

There's a GameStage string for loot and xp as per: https://github.com/McJtyMods/InControl/issues/68 , but none for actual spawn control, and adding the string to the spawn rules anyway has no effect.

Is there a way to do this in the current mod build or can support be added for it please?

**Comment by McJty** [comment]
Is this even player? GameStages are player specific and spawning rules have no concept of player. Mobs just spawn regardless of players and there can be multiple players with different game stages

**Comment by GamertechAU** [comment]
From what I understand, MobStages scans for players in the area and permits mobs that their stage allows, blocking spawns of those that aren't.
https://minecraft.curseforge.com/projects/mob-stages

When using MobStages without a rule in InControl, blocked mobs don't spawn at all around a player until they hit the required stage, upon which they spawn following vanilla rules.

If I change a mob's stats in IC, MobStages rules are ignored and mobs spawn freely within vanilla MC spawning rules, and any other IC rules are applied such as hp/damage changes.

**Comment by ofseaandstars** [comment]
I second this request. I would like to use rules, but only up until a specific stage is met, and would then like to disable that same rule after the player achieves a gamestage.

**Comment by Fireztonez** [comment]
I need to stage somes mobs how for some reason doesn't work with mob stages (MatterOverdrive Android). If you can add somes rules for spawn with game stages/mob stages, that will be nice.

I can block the spawn of this mobs with incontrol, I have tried, but I have to add back this mob at a certain stage...

Thanks

**Comment by AttilaPapp** [comment]
I am having the same issue. Meanwhile, it is the best mod to control mob spawning out there it is not working with Mob Stages.

It would be awesome if you could make it work.

Thank you

**Comment by Pival81** [comment]
As @McJty said on discord, it could be done by checking if the mob that's trying to spawn has any players around with the required stage.

**Comment by McJty** [comment]
I will work on this very soon now

**Comment by McJty** [comment]
Implemented in 3.9.14!
