### ISSUE TITLE
Empty spawn.json causes mobs to ignore potentialspawn limits

### ISSUE THREAD

**Issue by darthvader45** [McJty/InControl#86]
I set my potentialspawn.json file to spawn FNAF Universe animatronics naturally, at quite low limits (they're literally instakill, they do 1000 damage, or 500 hearts).  However, despite spawn.json being empty, they ignore the maxspawndistance and maxcount limits, i.e. they spawn all over the place causing insane lag.  I believe this is a bug, as if spawn.json is empty it should be ignored and all rules set in potentialspawn.json should be followed exactly.

**Comment by McJty** [comment]
That's not a bug. If spawn is empty you basically have no rules which means you get the default vanilla mob spawning rules. And then the move you added in potential spawn will use normal spawning rules

**Comment by McJty** [comment]
But can you show me your potential spawn file?

**Comment by darthvader45** [comment]
Here it is.  I've got a sneaking suspicion that FNAF Universe uses global entity stuff like Animals Plus used to, which may be the cause of the endless spawning.  Though if not, then maybe something in potentialspawn needs to change.
`[
  {
    "dimension": 0,
	"maxlight": 7,
	"minspawndistance": 240,
	"maxcount": "3, fnaf:freddy",
    "mobs": [
      {
        "mob": "fnaf:freddy",
        "weight": 20,
        "groupcountmin": 1,
        "groupcountmax": 3
      }
    ]
  },
  {
    "dimension": 0,
    "maxlight": 7,
	"minspawndistance": 240,
	"maxcount": "3, fnaf:bonnie",
    "mobs": [
      {
        "mob": "fnaf:bonnie",
        "weight": 20,
        "groupcountmin": 1,
        "groupcountmax": 3
      }
    ]
  },
  {
    "dimension": 0,
	"maxlight": 7,
	"minspawndistance": 240,
	"maxcount": "3, fnaf:chica",
       "mobs": [
      {
        "mob": "fnaf:chica",
        "weight": 20,
        "groupcountmin": 1,
        "groupcountmax": 3
      }
    ]
  },
  {
    "dimension": 0,
	"maxlight": 7,
	"minspawndistance": 240,
	"maxcount": "3, fnaf:foxy",
       "mobs": [
      {
        "mob": "fnaf:foxy",
        "weight": 20,
        "groupcountmin": 1,
        "groupcountmax": 3
      }
    ]
  },
    {
    "dimension": 0,
	"maxlight": 7,
	"minspawndistance": 240,
	"maxcount": "3, fnaf:springtrap",
       "mobs": [
      {
        "mob": "fnaf:springtrap",
        "weight": 1,
        "groupcountmin": 1,
        "groupcountmax": 1
      }
    ]
  }
  
]`

**Comment by McJty** [comment]
Try removing the spaces in: "maxcount": "3, fnaf:freddy",

My parsing is a bit strict. The space after the ',' could cause issues here

**Comment by darthvader45** [comment]
Trying now.

Edit:  Yep, it worked,  seems FNAF Universe wasn't a problem after all.  Thanks for the help, I owe ya a big one.
