### ISSUE TITLE
[Suggestion] allow item in offhand to count as helditem

### ISSUE THREAD

**Issue by xkforce** [McJty/InControl#89]
eg. suppose you have a few lines of code that specify that an item only drops if a mob is killed while the player is holding a stick.  Currently this only works if the player is holding that stick in their main hand.  AFAIK it isn't possible to create a script where the player either can hold a stick in their offhand and get the drop or where the drop will only happen if the stick is held in the player's offhand.

**Comment by McJty** [comment]
You are right. I can add support for that. I will not modify 'helditem' for this as that could cause compatibility issues with people that don't want that behaviour. I'll add a new tag specifically for this

**Comment by McJty** [comment]
Next release will feature two new tags: 'offhanditem' and 'bothhandsitem'

**Comment by xkforce** [comment]
ooooo neat thank you.
