### ISSUE TITLE
[1.12.2]  incontrol causes major FPS issue

### ISSUE THREAD

**Issue by Morpheus1101** [McJty/InControl#94]
With the setup i currently have, no sooner do mobs start spawning the worse the FPS//Game to the point you cant move its so lagged, removing the setup an just having the default generated config everything works fine. Below is a copy of the spawn json file(renamed to .txt to be able to upload)

[spawn.txt](https://github.com/McJtyMods/InControl/files/2786233/spawn.txt)

Forge v *.5.2808
IC v3.0.3
mcjtylib v3.1.1

**Comment by McJty** [comment]
Hmm In Control is used in many packs with performance problems. So it must be something specific to those rules. Can you try to experiment by removing some of the rules to see which one is the problematic one? Also some kind of profile result might be helpful too. Thanks

**Comment by Morpheus1101** [comment]
Watching the screen it seems as if the rules arent being followed an the spawning of the Zombies in this case are continuing untill the game is overloaded

Profile with Default config:
https://sparkprofiler.github.io/#1Yqaf3lMfF

Profile with the custom config:
https://sparkprofiler.github.io/#PShEUCqjL3


![2019-01-23_20 02 11](https://user-images.githubusercontent.com/10524952/51598740-e49bcc00-1f49-11e9-90d0-85f5b7559dd3.png)

**Comment by McJty** [comment]
I can't view those profiles:
An error occurred whilst loading. Perhaps the data has expired?

**Comment by Morpheus1101** [comment]
I just reloaded the webiste quite fine, not sure why itd error for you.

**Comment by McJty** [comment]
BTW, your first rule basically circumvents the usual 'cannot spawn in light'. I think to circumvent that you might want to limit the amount of zombies using the 'maxcount' rule

**Comment by Morpheus1101** [comment]
I'll try that as a last resort as the spawning rules previously worked quite fine so im now more suspecting something is overriding the default mob cap, so i will look into mod interactions to see if its a mod thats causing this issue to occur.
