### ISSUE TITLE
[solved] a configuration question

### ISSUE THREAD

**Issue by MSandro** [McJty/InControl#95]
Hi I just use the spawn.json to set the spawn conditions for Wither Skeletons and Grue, I whant to deny all other natural spawnings but mob spawner should work. But with my current configruation mob spawner doesn't work. 

https://pastebin.com/QUexqJWF

I don't use onjoin so why mob spawners doesn't work?

**Comment by McJty** [comment]
What kind of mob spawner is it? The vanilla ones?

**Comment by MSandro** [comment]
Yes vanilla mob spawners. I am not sure if this could cause issues, but I use MobsPropertiesRandomness in my modpack too. Because I add custom equipment to wither skeletons.

**Comment by MSandro** [comment]
any help? Cursed Earth from ExtraUtilities is still working, but spawners are broken with my config. Wither Skeleton spawners are working on the defined y levels but not above, why? It would make sense if I've set onjoin, but this isn't set in my config!

**Comment by MSandro** [comment]
Solved, this configuration now works:
```
[
  {
    "dimension": 63,
    "mob": ["minecraft:wither_skeleton"],
    "result": "allow",
    "minheight": 10,
    "maxheight": 30,
    "healthmultiply": 0.5,
    "damagemultiply": 0.5,
    "minlight": 0,
    "maxlight": 1
  },
  {
    "dimension": 63,
    "mob": ["grue:entitygrue"],
    "result": "allow",
    "minheight": 40,
    "maxheight": 90,
    "healthmultiply": 0.1,
    "damagemultiply": 0.1,
    "minlight": 0,
    "maxlight": 1
  },
  {
    "dimension": 63,
    "spawner": true,
    "result": "allow"
  },
  {
    "dimension": 63,
    "spawner": false,
    "result": "deny"
  }
]
```

**Comment by McJty** [comment]
Sorry, have been somewhat busy. Let me read up

**Comment by McJty** [comment]
Seems you solved it :-)
