### ISSUE TITLE
Multiple Item Drops per Mob

### ISSUE THREAD

**Issue by MokahTGS** [McJty/InControl#99]
Not sure if this is working correctly, but I can never tell since the documentation is lacking a lot of details.

  {
    "mob": "thebetweenlands:dreadful_mummy",
    "player": true,
    "item": "variedcommodities:locket",
	"item": "variedcommodities:orb_broken:8"
  }

I'm trying to get a mob to drop multiple items, but it will only drop one, or none, or error...I've tried all sorts of configurations of this script but can't get it to work.  The documentation says that you can do a string of items, but there isn't a correct syntax example anywhere of how to do it.

**Comment by McJty** [comment]
You need to use a list like this:

"item": [ "variedcommodities:locket", "variedcommodities:orb_broken:8" ]
